Repository avo-hq/avo, pull requests merged in 2020-10, with the labels that each got.

#152 fix: attach modal has spacing issues
  app/frontend/js/components/AttachModal.vue
  app/frontend/js/views/ResourceIndex.vue
Labels: fix

#153 fix: header partial throws 500 error
  app/views/partials/_header.html.erb
  lib/generators/avo/templates/views/_header.html.erb
Labels: fix

#154 refactor: change gemspect to support rails >= 6.0
  Gemfile.lock
  avo.gemspec
Labels: refactor

#155 fix: tailwind is missing apearance-none and removed future deprecations
  app/frontend/js/components/ResourceOverview.vue
  tailwind.config.js
Labels: fix

#74 feature: Role based authorization
  .github/workflows/test.yml
  app/controllers/avo/application_controller.rb
  app/controllers/avo/resources_controller.rb
  app/frontend/js/Api.js
  app/frontend/js/Avo.js
  app/frontend/js/components/Index/ItemControls.vue
  app/frontend/js/components/ResourcesSearch.vue
  app/frontend/js/components/Show/HasMany.vue
  app/frontend/js/components/index.js
  app/frontend/js/router.js
  app/frontend/js/views/403.vue
  app/frontend/js/views/AppLayout.vue
  app/frontend/js/views/ResourceEdit.vue
  app/frontend/js/views/ResourceIndex.vue
  app/frontend/js/views/ResourceShow.vue
  app/views/layouts/avo/application.html.erb
  config/routes.rb
  lib/avo/app/app.rb
  lib/avo/app/authorization_service.rb
  lib/avo/app/fields/has_and_belongs_to_many.rb
  lib/avo/app/fields/id_field.rb
  lib/avo/app/resource.rb
  spec/dummy/app/avo/resources/post.rb
  spec/dummy/app/models/user.rb
  spec/dummy/app/policies/application_policy.rb
  spec/dummy/app/policies/user_policy.rb
  spec/dummy/config/environments/development.rb
  spec/dummy/config/routes.rb
  spec/features/avo/authorization/controller_is_admin_spec.rb
  spec/features/avo/authorization/controller_no_methods_in_policy_spec.rb
  spec/features/avo/authorization/controller_no_policy_spec copy.rb
  spec/features/avo/authorization/scopes_spec.rb
  spec/rails_helper.rb
  spec/requests/avo/resource_overview_request_spec.rb
  spec/requests/avo/resources_controller_request_spec.rb
  spec/support/controller_routes.rb
  spec/support/devise.rb
  spec/support/helpers.rb
  spec/system/avo/actions_spec.rb
  spec/system/avo/boolean_group_field_spec.rb
  spec/system/avo/gravatar_field_spec.rb
  spec/system/avo/link_to_resource_spec.rb
  spec/system/avo/user_forms_spec.rb
  tailwind.config.js
Labels: feature

#156 fix: current filter blank crashes resource index
  app/frontend/js/views/ResourceIndex.vue
Labels: fix

#157 refactor: better grid view excerpt
  spec/dummy/app/avo/resources/post.rb
Labels: refactor

#158 refactor: extract resource controller functionality into multiple controllers
  app/controllers/avo/application_controller.rb
  app/controllers/avo/filters_controller.rb
  app/controllers/avo/relations_controller.rb
  app/controllers/avo/resources_controller.rb
  app/controllers/avo/search_controller.rb
  app/frontend/js/Avo.js
  app/frontend/js/components/Show/FieldWrapper.vue
  app/frontend/js/mixins/has-forms.js
  app/frontend/js/mixins/loads-resource.js
  app/frontend/js/views/ResourceNew.vue
  config/routes.rb
  lib/avo/app/authorization_service.rb
  spec/dummy/app/policies/user_policy.rb
  spec/features/avo/authorization/controller_is_admin_spec.rb
  spec/features/avo/authorization/controller_no_methods_in_policy_spec.rb
  spec/features/avo/authorization/controller_no_policy_spec.rb
  spec/features/avo/authorization/scopes_spec.rb
  spec/requests/avo/resources_controller_request_spec.rb
  spec/system/avo/key_value_field_spec.rb
Labels: refactor

#159 feature: add scripts partial
  app/helpers/avo/application_helper.rb
  app/views/layouts/avo/application.html.erb
  lib/generators/avo/templates/views/_scripts.html.erb
Labels: feature

#162 fix: pundit is missing from dependencies
  Gemfile.lock
  avo.gemspec
Labels: fix

#161 refactor: add home link to 403 view
  README.md
  app/frontend/js/views/403.vue
  spec/codecov.yml
Labels: refactor

#160 fix: unauthorized grid item should not have link to resource
  app/frontend/js/components/Index/GridView/GridItem.vue
Labels: fix

#164 refactor: default all application policy methods to false
  app/controllers/avo/application_controller.rb
  app/controllers/avo/resource_overview_controller.rb
  app/controllers/avo/resources_controller.rb
  app/controllers/avo/search_controller.rb
  lib/avo/app/app.rb
  lib/avo/app/authorization_service.rb
  lib/avo/app/resource.rb
  lib/avo/configuration.rb
  package.json
  spec/dummy/app/policies/application_policy.rb
  spec/dummy/app/policies/user_policy.rb
  spec/features/avo/authorization/controller_is_admin_spec.rb
  spec/features/avo/authorization/controller_no_methods_in_policy_spec.rb
  spec/features/avo/authorization/controller_no_policy_spec.rb
  spec/features/avo/authorization/scopes_spec.rb
  spec/features/avo/resource_overview_spec.rb
  spec/features/avo/resources_controller_spec.rb
Labels: refactor

#167 chore: update license regarding community version
  Gemfile.lock
  LICENSE.md
  lib/avo/version.rb
Labels: chore

#168 fix: engine loads same files more than once
  lib/avo/engine.rb
Labels: fix

#169 fix: has many relation link_to has wrong path
  app/frontend/js/mixins/deals-with-has-many-relations.js
  lib/avo/app/resource.rb
  lib/avo/engine.rb
Labels: fix

#171 fix: only_on not working on password and implementation of show_on/hide_on all
  lib/avo/app/fields/field_extensions/visible_in_different_views.rb
  lib/avo/app/fields/password_field.rb
  spec/dummy/app/avo/resources/user.rb
Labels: fix

#173 fix: remove save button from edit when update is restricted
  app/controllers/avo/resources_controller.rb
  app/frontend/js/components/Index/ItemControls.vue
  app/frontend/js/views/ResourceEdit.vue
  app/frontend/js/views/ResourceShow.vue
  lib/avo/app/resource.rb
  spec/features/avo/resources_controller_spec.rb
Labels: fix

#172 fix: link_to_resource removed when show restricted
  app/frontend/js/components/Index/GravatarField.vue
  app/frontend/js/components/Index/IdField.vue
  app/frontend/js/components/Index/TextField.vue
Labels: fix

#175 fix: KeyValue disable options issues
  app/frontend/js/components/Edit/KeyValueField.vue
  app/frontend/js/components/KeyValueComponent.vue
  app/frontend/js/components/KeyValueRow.vue
Labels: fix
