Repository avo-hq/avo, pull requests merged in 2020-11, with the labels that each got.

#179 feat: height option for Code field
  app/frontend/js/components/CodeComponent.vue
  app/frontend/js/components/Edit/CodeField.vue
  app/frontend/js/components/Show/CodeField.vue
  lib/avo/app/fields/code_field.rb
  spec/dummy/app/avo/resources/user.rb
Labels: feature

#137 feature: Markdown field
  app/frontend/js/components/Edit/MarkdownField.vue
  app/frontend/js/components/Edit/TrixField.vue
  app/frontend/js/components/Show/MarkdownField.vue
  app/frontend/js/components/index.js
  app/views/layouts/avo/application.html.erb
  lib/avo/app/fields/markdown_field.rb
  package.json
  spec/dummy/app/avo/resources/project.rb
  spec/dummy/db/migrate/20201026153236_add_description_to_projects.rb
  spec/dummy/db/schema.rb
  spec/system/avo/markdown_field_spec.rb
  yarn.lock
Labels: feature

#180 fix: height option for Markdown field
  app/frontend/js/components/Edit/MarkdownField.vue
  lib/avo/app/fields/markdown_field.rb
  spec/dummy/app/avo/resources/project.rb
Labels: fix

#181 fix: index/show will display dash for wrong input
  app/frontend/js/components/Index/BooleanGroupField.vue
  app/frontend/js/components/Show/BooleanGroupField.vue
Labels: fix

#184 feature: reset button for filters
  app/frontend/js/components/Button.vue
  app/frontend/js/components/Edit/DatetimeField.vue
  app/frontend/js/components/Index/ResourceFilters.vue
  app/frontend/js/views/ResourceIndex.vue
Labels: feature

#178 feature: allow no_confirmation for Actions
  app/frontend/js/components/Edit/BooleanGroupField.vue
  app/frontend/js/components/Edit/FieldWrapper.vue
  app/frontend/js/components/Modals/ActionsModal.vue
  app/frontend/js/components/ResourceActions.vue
  app/frontend/js/components/Show/BooleanGroupField.vue
  app/frontend/js/mixins/is-field-wrapper.js
  lib/avo/app/action.rb
  spec/dummy/app/avo/actions/make_admin.rb
  spec/dummy/app/avo/resources/user.rb
  spec/system/avo/actions_spec.rb
Labels: feature

#183 feature: set now/today button for datetime/date fields
  app/frontend/js/components/Edit/DatetimeField.vue
Labels: feature

#188 refactor: use cache memory store for license calls when null store selected
  .github/workflows/test.yml
  app/controllers/avo/application_controller.rb
  lib/avo.rb
  lib/avo/app/app.rb
  lib/avo/app/licensing/hq.rb
  lib/avo/engine.rb
  spec/dummy/config/boot.rb
  spec/rails_helper.rb
Labels: refactor

#191 fix: markdown field forces autofocus
  app/frontend/js/components/Edit/MarkdownField.vue
Labels: fix

#192 fix: janky page transitions
  app/frontend/css/application.css
  app/frontend/js/components/Panel.vue
  app/views/layouts/avo/application.html.erb
Labels: fix

#190 fix: loaders are not visible on some pages
  app/frontend/js/components/Button.vue
  app/frontend/js/components/Index/ResourceFilters.vue
  app/frontend/js/mixins/loads-resource.js
  app/frontend/js/views/ResourceEdit.vue
  app/frontend/js/views/ResourceIndex.vue
  app/frontend/js/views/ResourceNew.vue
  app/frontend/js/views/ResourceShow.vue
  lib/avo/app/resource.rb
Labels: fix

#193 fix: index pages has wrong label
  app/frontend/js/components/EmptyState.vue
  spec/system/avo/user_forms_spec.rb
Labels: fix

#187 fix: filter tests
  app/controllers/avo/resources_controller.rb
  lib/avo/app/filter.rb
  spec/dummy/app/avo/filters/members_filter.rb
  spec/dummy/app/avo/resources/team.rb
  spec/system/avo/filters_spec.rb
  spec/system/avo/has_one_field_spec.rb
Labels: fix
