Repository avo-hq/avo, pull requests merged in 2021-02, with the labels that each got.

#237 fix: HABTM cant find associations with custom class_name
  lib/avo/app/app.rb
  lib/avo/app/fields/has_and_belongs_to_many.rb
Labels: fix

#226 (AVO-38) feature: Status field
  app/components/avo/resource_controls_component.html.erb
  app/components/avo/resource_edit_component.html.erb
  app/frontend/css/application.css
  app/frontend/css/components/status.css
  app/views/avo/fields/common/_status_field.html.erb
  app/views/avo/fields/edit/_status-field.html.erb
  app/views/avo/fields/index/_status-field.html.erb
  app/views/avo/fields/show/_status-field.html.erb
  lib/avo/app/fields/status_field.rb
  spec/dummy/app/avo/resources/project.rb
  spec/features/avo/status_field_spec.rb
Labels: feature

#222 (AVO-37) feature: Select field
  app/views/avo/fields/edit/_select-field.html.erb
  app/views/avo/fields/index/_select-field.html.erb
  app/views/avo/fields/show/_select-field.html.erb
  db/factories.rb
  lib/avo/app/fields/select_field.rb
  spec/dummy/app/avo/resources/project.rb
  spec/dummy/app/models/project.rb
  spec/features/avo/select_spec.rb
Labels: feature

#239 (AVO-28) feature: file fields
  Gemfile
  Gemfile.lock
  app/components/avo/grid_item_component.html.erb
  app/components/avo/resource_edit_component.html.erb
  app/components/avo/resource_edit_component.rb
  app/components/avo/resource_grid_component.html.erb
  app/components/avo/resource_new_component.html.erb
  app/controllers/avo/application_controller.rb
  app/controllers/avo/attachments_controller.rb
  app/controllers/avo/base_controller.rb
  app/frontend/js/hotwire/controllers/attachments_controller.js
  app/frontend/svgs/document-text.svg
  app/helpers/avo/attachments_helper.rb
  app/views/avo/attachments/show.html.erb
  app/views/avo/fields/common/_file_item.html.erb
  app/views/avo/fields/common/_file_item_controls.html.erb
  app/views/avo/fields/common/_files_list.html.erb
  app/views/avo/fields/edit/_file-field.html.erb
  app/views/avo/fields/edit/_files-field.html.erb
  app/views/avo/fields/index/_file-field.html.erb
  app/views/avo/fields/index/_files-field.html.erb
  app/views/avo/fields/show/_file-field.html.erb
  app/views/avo/fields/show/_files-field.html.erb
  app/views/layouts/avo/application.html.erb
  avo.gemspec
  config/routes.rb
  lib/avo/app/app.rb
  lib/avo/app/fields/belongs_to.rb
  lib/avo/app/fields/boolean_group_field.rb
  lib/avo/app/fields/field.rb
  lib/avo/app/fields/file_field.rb
  lib/avo/app/fields/files_field.rb
  lib/avo/app/fields/key_value_field.rb
  spec/dummy/app/avo/resources/post.rb
  spec/dummy/app/avo/resources/project.rb
  spec/dummy/config/locales/avo.en.yml
  spec/helpers/avo/attachments_helper_spec.rb
  spec/requests/avo/attachments_request_spec.rb
  tailwind.config.js
Labels: feature

#241 (AVO-22) feature: code field
  app/frontend/css/application.css
  app/frontend/css/components/code.css
  app/frontend/js/hotwire/controllers/fields/code_field_controller.js
  app/frontend/js/hotwire/controllers/fields/simple_mde_controller.js
  app/frontend/packs/application_hotwire.js
  app/views/avo/fields/edit/_code-field.html.erb
  app/views/avo/fields/show/_code-field.html.erb
  app/views/layouts/avo/_edit_field_wrapper.html.erb
  lib/avo/app/fields/code_field.rb
  package.json
  spec/dummy/app/avo/resources/user.rb
  yarn.lock
Labels: feature

#254 (AVO-41) feature: trix field
  app/frontend/js/hotwire/controllers/hidden_input_controller.js
  app/views/avo/fields/edit/_trix-field.html.erb
  app/views/avo/fields/show/_trix-field.html.erb
  lib/avo/app/fields/trix_field.rb
  package.json
  spec/dummy/app/avo/resources/post.rb
  yarn.lock
Labels: feature

#255 (AVO-25)(AVO-26)feature: date and datetime fields
  .eslintrc.json
  app/frontend/js/helpers/cast_boolean.js
  app/frontend/js/hotwire/controllers/fields/code_field_controller.js
  app/frontend/js/hotwire/controllers/fields/date_field_controller.js
  app/views/avo/fields/edit/_code-field.html.erb
  app/views/avo/fields/edit/_date-field.html.erb
  app/views/avo/fields/edit/_datetime-field.html.erb
  app/views/avo/fields/edit/_files-field.html.erb
  app/views/avo/fields/index/_date-field.html.erb
  app/views/avo/fields/index/_datetime-field.html.erb
  app/views/avo/fields/show/_code-field.html.erb
  app/views/avo/fields/show/_date-field.html.erb
  app/views/avo/fields/show/_datetime-field.html.erb
  app/views/avo/fields/show/_files-field.html.erb
  app/views/layouts/avo/_javascript.html.erb
  lib/avo/app/fields/date_field.rb
  lib/avo/app/fields/datetime_field.rb
  lib/avo/app/fields/field.rb
  lib/avo/app/fields/select_field.rb
  package.json
  spec/dummy/app/avo/resources/project.rb
  spec/dummy/app/avo/resources/user.rb
  yarn.lock
Labels: feature

#256 (AVO-23)feature: country field
  app/views/avo/fields/edit/_country-field.html.erb
  app/views/avo/fields/index/_country-field.html.erb
  app/views/avo/fields/show/_country-field.html.erb
  lib/avo/app/fields/country_field.rb
  spec/dummy/app/avo/resources/project.rb
Labels: feature

#257 (AVO-20)refactor: resolve truthy values for boolean field
  app/views/avo/fields/show/_number-field.html copy.erb
  lib/avo/app/fields/boolean_field.rb
Labels: feature

#258 (AVO-31)feature: hidden field
  app/views/avo/fields/edit/_hidden-field.html.erb
  spec/dummy/app/avo/resources/user.rb
Labels: feature

#259 (AVO-21)feature: boolean group field
  app/frontend/css/application.css
  app/frontend/js/hotwire/controllers/tippy_controller.js
  app/views/avo/fields/common/_boolean_group_popup.html.erb
  app/views/avo/fields/edit/_boolean-group-field.html.erb
  app/views/avo/fields/index/_boolean-group-field.html.erb
  app/views/avo/fields/show/_boolean-group-field.html.erb
  lib/avo/app/fields/boolean_group_field.rb
  package.json
  spec/dummy/app/avo/resources/project.rb
  spec/dummy/app/avo/resources/team.rb
  spec/dummy/app/avo/resources/team_membership.rb
  spec/dummy/app/avo/resources/user.rb
  yarn.lock
Labels: feature

#260 fix: resource controls have wrong referrer
  app/components/avo/resource_index_component.html.erb
  app/controllers/avo/base_controller.rb
  app/controllers/avo/relations_controller.rb
  app/views/avo/base/index.html.erb
  app/views/avo/partials/_alerts.html.erb
  app/views/layouts/avo/application.html.erb
Labels: fix

#261 (AVO-71)fix: resource show component does not show the computed title
  lib/avo/app/resource.rb
Labels: fix

#263 refactor: view component tweaks
  Gemfile.lock
  app/components/avo/resource_component.rb
  app/components/avo/resource_index_component.rb
  app/components/avo/resource_new_component.html.erb
  app/controllers/avo/base_controller.rb
  app/frontend/packs/application_hotwire.js
  app/views/avo/base/_actions.html.erb
  app/views/avo/base/_boolean_filter.html.erb
  app/views/avo/base/_filters.html.erb
  app/views/avo/base/_view_toggle_button.html.erb
  app/views/avo/base/edit.html.erb
  app/views/avo/base/new.html.erb
  app/views/avo/base/show.html.erb
  spec/dummy/app/avo/resources/post.rb
  spec/dummy/app/avo/resources/user.rb
  spec/dummy/config/locales/avo.en.yml
  yarn.lock
Labels: refactor
