Repository avo-hq/avo, pull requests merged in 2021-05, with the labels that each got.

#376 feature: search
  Gemfile
  Gemfile.lock
  README.md
  app/components/avo/views/resource_index_component.html.erb
  app/controllers/avo/application_controller.rb
  app/controllers/avo/relations_controller.rb
  app/controllers/avo/search_controller.rb
  app/helpers/avo/application_helper.rb
  app/packs/entrypoints/application.css
  app/packs/entrypoints/application.js
  app/packs/js/controllers/search_controller.js
  app/packs/js/helpers/debounce_promise.js
  app/packs/stylesheets/search.css
  app/views/avo/base/index.html.erb
  app/views/avo/base/show.html.erb
  app/views/avo/partials/_global_search.html.erb
  app/views/avo/partials/_resource_search.html.erb
  app/views/avo/partials/_turbo_frame_wrap.html.erb
  app/views/layouts/avo/application.html.erb
  avo.gemspec
  config/routes.rb
  lib/avo/app.rb
  lib/avo/base_resource.rb
  lib/avo/configuration.rb
  lib/avo/fields/base_field.rb
  lib/avo/fields/file_field.rb
  lib/avo/licensing/license.rb
  lib/avo/licensing/license_manager.rb
  lib/avo/licensing/pro_license.rb
  lib/avo/services/authorization_service.rb
  lib/generators/avo/templates/initializer/avo.tt
  lib/generators/avo/templates/resource/resource.tt
  package.json
  spec/dummy/app/avo/actions/toggle_admin.rb
  spec/dummy/app/avo/resources/post_resource.rb
  spec/dummy/app/avo/resources/project_resource.rb
  spec/dummy/app/avo/resources/team_membership_resource.rb
  spec/dummy/app/avo/resources/team_resource.rb
  spec/dummy/app/avo/resources/user_resource.rb
  spec/dummy/config/initializers/avo.rb
  spec/features/avo/license_manager_spec.rb
  spec/features/avo/search_spec.rb
  spec/requests/avo/authorization/scopes_spec.rb
  yarn.lock
Labels: feature

#383 fix: unauthorized sidebar resource showing up
  lib/avo/app.rb
Labels: fix

#384 fix: external image cant be used as avatar
  lib/avo/base_resource.rb
  lib/avo/fields/external_image_field.rb
Labels: fix

#385 refactor: add avo default locales to the rails app
  lib/avo/engine.rb
Labels: refactor

#387 refactor: smaller id columns
  app/components/avo/fields/id_field/index_component.html.erb
Labels: refactor

#394 fix: remove current_user assumption and allow current_user_method to be a symbol
  lib/avo/configuration.rb
  spec/dummy/config/initializers/avo.rb
Labels: fix

#401 feature: unscoped queries on index
  README.md
  app/controllers/avo/base_controller.rb
  lib/avo/base_resource.rb
  spec/dummy/app/avo/resources/project_resource.rb
  spec/dummy/app/models/project.rb
Labels: feature

#404 feature: select options supports a block
  lib/avo/fields/select_field.rb
  spec/dummy/app/avo/resources/team_membership_resource.rb
Labels: feature

#402 feature: support polymorphic belongs_to
  Gemfile.lock
  app/components/avo/edit/field_wrapper_component.html.erb
  app/components/avo/edit/field_wrapper_component.rb
  app/components/avo/fields/belongs_to_field/edit_component.html.erb
  app/components/avo/fields/belongs_to_field/edit_component.rb
  app/packs/js/controllers/fields/belongs_to_field_controller.js
  db/factories.rb
  lib/avo/base_resource.rb
  lib/avo/fields/base_field.rb
  lib/avo/fields/belongs_to_field.rb
  lib/avo/fields/boolean_group_field.rb
  lib/avo/fields/date_time_field.rb
  lib/avo/fields/files_field.rb
  lib/avo/fields/has_one_field.rb
  lib/avo/fields/key_value_field.rb
  lib/avo/fields_collector.rb
  spec/dummy/app/avo/resources/comment_resource.rb
  spec/dummy/app/avo/resources/post_resource.rb
  spec/dummy/app/avo/resources/project_resource.rb
  spec/dummy/app/controllers/avo/comments_controller.rb
  spec/dummy/app/models/comment.rb
  spec/dummy/app/models/post.rb
  spec/dummy/app/models/project.rb
  spec/dummy/app/policies/project_policy.rb
  spec/dummy/db/migrate/20210521085656_create_comments.rb
  spec/dummy/db/schema.rb
  spec/dummy/db/seeds.rb
  spec/features/avo/belongs_to_polymorphic_spec.rb
  spec/features/avo/belongs_to_spec.rb
Labels: feature

#405 fix: badge field values can be symbols too
  app/components/avo/fields/common/badge_viewer_component.html.erb
  spec/dummy/app/policies/project_policy.rb
Labels: fix

#409 fix: license has -> lacks ability
  lib/avo/base_resource.rb
Labels: fix
