Repository avo-hq/avo, pull requests merged in 2022-08, with the labels that each got.

#1107 feature: allow custom fields in resource tools
  app/components/avo/item_switcher_component.html.erb
  app/controllers/avo/application_controller.rb
  app/controllers/avo/base_controller.rb
  lib/avo/base_resource.rb
  spec/dummy/app/avo/resources/fish_resource.rb
  spec/dummy/app/models/fish.rb
  spec/dummy/app/views/avo/resource_tools/_fish_information.html.erb
  spec/dummy/db/migrate/20220727112241_add_type_to_fish.rb
  spec/dummy/db/schema.rb
  spec/features/avo/custom_fields_in_resource_tools_spec.rb
Labels: feature

#1124 fix: heading can't be the first item in your resource
  lib/avo/concerns/has_fields.rb
  lib/avo/hosts/base_host.rb
Labels: fix

#1120 chore: misc tweaks
  CONTRIBUTING.MD
  README.md
  app/components/avo/fields/common/gravatar_viewer_component.html.erb
  app/components/avo/fields/date_field/edit_component.html.erb
  app/components/avo/fields/date_time_field/edit_component.html.erb
  app/components/avo/sidebar_component.html.erb
  app/views/layouts/avo/application.html.erb
  lib/avo/fields/date_field.rb
  lib/avo/fields/field_extensions/has_include_blank.rb
  lib/avo/fields/key_value_field.rb
  lib/avo/licensing/h_q.rb
  lib/avo/menu/builder.rb
  lib/generators/avo/templates/initializer/avo.tt
  spec/dummy/app/avo/resources/person_resource.rb
  spec/dummy/app/avo/resources/post_resource.rb
  spec/dummy/app/avo/resources/review_resource.rb
  spec/dummy/app/avo/resources/spouse_resource.rb
  spec/dummy/app/avo/resources/team_resource.rb
  spec/dummy/app/models/post.rb
  spec/features/avo/resource_description_spec.rb
  tailwind.config.js
Labels: refactor

#1083 feature: customizable resource controls
  app/components/avo/actions_component.html.erb
  app/components/avo/actions_component.rb
  app/components/avo/button_component.rb
  app/components/avo/panel_component.html.erb
  app/components/avo/resource_component.rb
  app/components/avo/views/resource_show_component.html.erb
  app/components/avo/views/resource_show_component.rb
  app/views/avo/debug/report.html.erb
  app/views/avo/private/design.html.erb
  lib/avo/base_resource.rb
  lib/avo/concerns/has_editable_controls.rb
  lib/avo/concerns/has_model.rb
  lib/avo/licensing/pro_license.rb
  lib/avo/resources/controls/action.rb
  lib/avo/resources/controls/actions_list.rb
  lib/avo/resources/controls/back_button.rb
  lib/avo/resources/controls/base_control.rb
  lib/avo/resources/controls/delete_button.rb
  lib/avo/resources/controls/detach_button.rb
  lib/avo/resources/controls/edit_button.rb
  lib/avo/resources/controls/execution_context.rb
  lib/avo/resources/controls/items_holder.rb
  lib/avo/resources/controls/link_to.rb
  lib/generators/avo/templates/action.tt
  lib/generators/avo/templates/resource_tools/partial.tt
  lib/generators/avo/templates/standalone_action.tt
  safelist.txt
  scripts/export-tailwind-safelist.js
  spec/dummy/app/avo/actions/dummy_action.rb
  spec/dummy/app/avo/actions/release_fish.rb
  spec/dummy/app/avo/resources/fish_resource.rb
  spec/dummy/app/avo/resources/post_resource.rb
  spec/dummy/app/avo/resources/user_resource.rb
  spec/dummy/app/models/fish.rb
  spec/dummy/app/models/user.rb
  spec/dummy/app/views/avo/resource_tools/_ann_tool.html.erb
  spec/dummy/app/views/avo/resource_tools/_bob_tool.html.erb
  spec/dummy/app/views/avo/resource_tools/_fish_information.html.erb
  spec/dummy/app/views/avo/resource_tools/_muser_tool.html.erb
  spec/dummy/db/migrate/20220729223019_add_user_id_to_fish.rb
  spec/dummy/db/schema.rb
  spec/features/avo/custom_fields_in_resource_tools_spec.rb
  spec/features/avo/custom_resource_controls_spec.rb
  spec/features/avo/resource_tools_spec.rb
  spec/system/avo/custom_resource_controls_spec.rb
  spec/system/avo/tabs_spec.rb
Labels: feature

#1129 refactor: tweak panel component
  app/components/avo/fields/has_one_field/show_component.html.erb
  app/components/avo/item_switcher_component.html.erb
  app/components/avo/panel_component.rb
  app/components/avo/views/resource_edit_component.html.erb
  app/components/avo/views/resource_index_component.html.erb
  app/components/avo/views/resource_show_component.html.erb
  app/views/avo/dashboards/show.html.erb
  app/views/avo/debug/index.html.erb
  app/views/avo/home/index.html.erb
  app/views/avo/private/design.html.erb
  spec/dummy/app/views/avo/resource_tools/_fish_information.html.erb
  spec/dummy/app/views/avo/resource_tools/_user_tool.html.erb
  spec/dummy/app/views/avo/tools/custom_tool.html.erb
Labels: refactor

#1135 fix: failed forms can't be resubmitted
  app/components/avo/fields/tags_field/show_component.rb
  app/components/avo/tab_group_component.html.erb
  app/components/avo/tab_switcher_component.rb
  app/components/avo/views/resource_edit_component.rb
  app/controllers/avo/base_controller.rb
  app/views/avo/associations/new.html.erb
  lib/avo/fields/base_field.rb
Labels: fix

#1127 Fix sidebar default collapsed state
  app/javascript/js/controllers/menu_controller.js
Labels: fix

#1145 refactor: allow empty show_controls block
  app/components/avo/views/resource_show_component.html.erb
  lib/avo/concerns/has_editable_controls.rb
Labels: refactor

#1139 feature: Custom path and message after create update and delete
  CONTRIBUTING.MD
  app/controllers/avo/base_controller.rb
  spec/dummy/app/controllers/avo/courses_controller.rb
  spec/dummy/app/models/course.rb
  spec/features/avo/exposed_methods_base_controller_spec.rb
Labels: feature

#1152 fix: search pagination unlimited
  app/controllers/avo/search_controller.rb
Labels: fix

#1150 feature: Callable readonly
  app/components/avo/fields/belongs_to_field/edit_component.rb
  app/components/avo/fields/boolean_field/edit_component.html.erb
  app/components/avo/fields/boolean_group_field/edit_component.html.erb
  app/components/avo/fields/code_field/edit_component.html.erb
  app/components/avo/fields/country_field/edit_component.html.erb
  app/components/avo/fields/date_field/edit_component.html.erb
  app/components/avo/fields/date_time_field/edit_component.html.erb
  app/components/avo/fields/external_image_field/edit_component.html.erb
  app/components/avo/fields/file_field/edit_component.html.erb
  app/components/avo/fields/files_field/edit_component.html.erb
  app/components/avo/fields/has_one_field/show_component.html.erb
  app/components/avo/fields/markdown_field/edit_component.html.erb
  app/components/avo/fields/markdown_field/show_component.html.erb
  app/components/avo/fields/number_field/edit_component.html.erb
  app/components/avo/fields/password_field/edit_component.html.erb
  app/components/avo/fields/progress_bar_field/edit_component.html.erb
  app/components/avo/fields/select_field/edit_component.html.erb
  app/components/avo/fields/status_field/edit_component.html.erb
  app/components/avo/fields/tags_field/edit_component.html.erb
  app/components/avo/fields/text_field/edit_component.html.erb
  app/components/avo/fields/textarea_field/edit_component.html.erb
  app/components/avo/fields/trix_field/edit_component.html.erb
  lib/avo/fields/base_field.rb
  lib/avo/fields/concerns/is_readonly.rb
  lib/generators/avo/templates/field/components/edit_component.html.erb.tt
  spec/dummy/app/avo/resources/fish_resource.rb
  spec/dummy/app/components/avo/fields/color_picker_field/edit_component.html.erb
  spec/features/avo/readonly_takes_a_block_spec.rb
  spec/features/avo/required_takes_a_block_spec.rb
Labels: feature

#1141 refactor: use inline_svg gem
  .github/workflows/stale.yml
  Gemfile.lock
  app/assets/svgs/arrow-circle-right.svg
  app/assets/svgs/arrow-down.svg
  app/assets/svgs/arrow-up.svg
  app/assets/svgs/bell.svg
  app/assets/svgs/chevron-right.svg
  app/assets/svgs/exclamation.svg
  app/assets/svgs/information-circle.svg
  app/assets/svgs/logout.svg
  app/assets/svgs/menu.svg
  app/assets/svgs/play.svg
  app/assets/svgs/switch-vertical.svg
  app/assets/svgs/user-circle.svg
  app/assets/svgs/x.svg
  app/components/avo/card_component.html.erb
  app/components/avo/common_field_wrapper_component.html.erb
  app/helpers/avo/application_helper.rb
  avo.gemspec
  spec/dummy/app/assets/images/adjustments.svg
  spec/dummy/app/assets/svgs/annotation.svg
  spec/dummy/config/initializers/avo.rb
Labels: refactor

#1158 fix: redirect back to parent if deleted from parent
  app/components/avo/views/resource_show_component.html.erb
  app/components/avo/views/resource_show_component.rb
Labels: fix

#1157 fix: act_on policy applyed on show and edit views
  app/components/avo/resource_component.rb
  app/components/avo/views/resource_edit_component.html.erb
  app/components/avo/views/resource_index_component.rb
  app/components/avo/views/resource_show_component.html.erb
Labels: fix

#1160 fix: inline_svg path fixes
  app/helpers/avo/application_helper.rb
  lib/avo/svg_finder.rb
  spec/dummy/app/assets/images/dummy-adjustments.svg
  spec/dummy/config/initializers/avo.rb
Labels: fix

#1167 fix: attempt to fix permissions for PR labeler
  .github/workflows/label-pr.yml
Labels: chore

#1164 fix: cancel button path when creating from has many
  app/components/avo/base_component.rb
  app/components/avo/resource_component.rb
  app/components/avo/views/resource_edit_component.rb
Labels: fix

#1163 fix: date value changed on direct submit
  app/javascript/js/controllers/fields/date_field_controller.js
Labels: fix

#1169 chore: add testing for the release fish action
  spec/dummy/app/avo/actions/release_fish.rb
  spec/features/avo/release_fish_spec.rb
Labels: chore

#1177 refactor: progressbar component
  app/components/avo/fields/common/progress_bar_component.html.erb
  app/components/avo/fields/common/progress_bar_component.rb
  app/components/avo/fields/progress_bar_field/index_component.html.erb
  app/components/avo/fields/progress_bar_field/show_component.html.erb
Labels: refactor

#1148 feature: select all records from current index pages
  app/components/avo/index/resource_table_component.html.erb
  app/components/avo/index/resource_table_component.rb
  app/components/avo/views/resource_index_component.html.erb
  app/components/avo/views/resource_index_component.rb
  app/controllers/avo/actions_controller.rb
  app/helpers/avo/resources_helper.rb
  app/javascript/js/controllers/action_controller.js
  app/javascript/js/controllers/item_select_all_controller.js
  app/views/avo/actions/show.html.erb
  app/views/avo/base/index.html.erb
  app/views/avo/partials/_table_header.html.erb
  lib/avo/services/encryption_service.rb
  lib/generators/avo/templates/locales/avo.en.yml
  lib/generators/avo/templates/locales/avo.fr.yml
  lib/generators/avo/templates/locales/avo.nb-NO.yml
  lib/generators/avo/templates/locales/avo.pt-BR.yml
  lib/generators/avo/templates/locales/avo.ro.yml
  spec/dummy/app/avo/resources/fish_resource.rb
  spec/features/avo/record_selector_spec.rb
  spec/system/avo/boolean_filter_spec.rb
  spec/system/avo/select_all_spec.rb
Labels: feature

#1155 feature: pills switcher
  .github/workflows/test.yml
  app/components/avo/button_component.rb
  app/components/avo/item_switcher_component.rb
  app/components/avo/tab_group_component.html.erb
  app/components/avo/tab_group_component.rb
  app/components/avo/tab_switcher_component.html.erb
  app/components/avo/tab_switcher_component.rb
  app/javascript/js/controllers/tabs_controller.js
  app/views/avo/partials/_tabs_toggle.html.erb
  app/views/avo/partials/_view_toggle_button.html.erb
  lib/avo/concerns/has_fields.rb
  lib/avo/configuration.rb
  lib/avo/tab_group.rb
  lib/avo/tab_group_builder.rb
  lib/generators/avo/templates/initializer/avo.tt
  spec/dummy/app/avo/resources/fish_resource.rb
  spec/dummy/app/avo/resources/user_resource.rb
  spec/support/helpers.rb
  spec/system/avo/tabs_spec.rb
Labels: feature, fix

#1186 fix: use secret_key_base off the env variable
  lib/avo/services/encryption_service.rb
Labels: fix

#1175 fix: broken download button for file fields
  app/components/avo/fields/common/single_file_viewer_component.html.erb
Labels: fix

#1199 refactor: ensure better hq error handling
  app/components/avo/sidebar_component.html.erb
  app/controllers/avo/debug_controller.rb
  app/views/avo/debug/index.html.erb
  app/views/avo/sidebar/_license_warnings.html.erb
  lib/avo/app.rb
  lib/avo/licensing/h_q.rb
  lib/avo/licensing/license_manager.rb
Labels: refactor
