Repository avo-hq/avo, pull requests merged in 2022-05, with the labels that each got.

#876 feature: pass record to association scope
  app/components/avo/edit/field_wrapper_component.html.erb
  app/components/avo/edit/field_wrapper_component.rb
  app/components/avo/fields/belongs_to_field/autocomplete_component.html.erb
  app/components/avo/fields/belongs_to_field/autocomplete_component.rb
  app/components/avo/fields/belongs_to_field/edit_component.html.erb
  app/components/avo/views/resource_index_component.rb
  app/controllers/avo/associations_controller.rb
  app/controllers/avo/search_controller.rb
  app/helpers/avo/url_helpers.rb
  app/javascript/js/controllers/search_controller.js
  lib/avo/fields/belongs_to_field.rb
  lib/avo/fields/has_base_field.rb
  lib/avo/hosts/association_scope_host.rb
  lib/avo/services/authorization_service.rb
  spec/dummy/app/avo/resources/review_resource.rb
  spec/dummy/app/avo/resources/user_resource.rb
  spec/features/avo/belongs_to_spec.rb
  spec/features/avo/has_many_field_spec.rb
  spec/features/avo/record_passed_to_scope_spec.rb
Labels: feature

#877 chore: fix standardrb
  .github/workflows/reviewdog.yml
Labels: chore

#875 fix: has many loses scope on per page change
  app/components/avo/paginator_component.html.erb
  app/components/avo/paginator_component.rb
  app/components/avo/views/resource_index_component.html.erb
  app/helpers/avo/url_helpers.rb
Labels: fix

#873 feature: filter change from different filter
  app/components/avo/filters_component.html.erb
  app/components/avo/filters_component.rb
  app/components/avo/views/resource_index_component.html.erb
  app/components/avo/views/resource_index_component.rb
  app/controllers/avo/base_controller.rb
  app/javascript/js/controllers/filter_controller.js
  app/views/avo/base/_boolean_filter.html.erb
  app/views/avo/base/_multiple_select_filter.html.erb
  app/views/avo/base/_select_filter.html.erb
  app/views/avo/base/_text_filter.html.erb
  app/views/avo/base/index.html.erb
  db/factories.rb
  lib/avo/base_resource.rb
  lib/avo/filters/base_filter.rb
  lib/generators/avo/templates/locales/avo.en.yml
  lib/generators/avo/templates/locales/avo.nb-NO.yml
  lib/generators/avo/templates/locales/avo.pt-BR.yml
  lib/generators/avo/templates/locales/avo.ro.yml
  spec/dummy/app/avo/filters/course_city_filter.rb
  spec/dummy/app/avo/filters/course_country_filter.rb
  spec/dummy/app/avo/filters/post_status_filter.rb
  spec/dummy/app/avo/filters/published_filter.rb
  spec/dummy/app/avo/resources/course_resource.rb
  spec/dummy/app/avo/resources/post_resource.rb
  spec/dummy/app/models/course.rb
  spec/dummy/db/migrate/20220502080845_add_country_and_city_to_courses.rb
  spec/dummy/db/schema.rb
  spec/dummy/db/seeds.rb
  spec/features/avo/destroy_record_spec.rb
  spec/system/avo/dynamic_filters_spec.rb
  spec/system/avo/filters_empty_values_message_spec.rb
  spec/system/avo/filters_panel_open_spec.rb
Labels: feature

#882 feature: multiple action alerts
  app/assets/stylesheets/avo.css
  app/assets/stylesheets/css/alerts.css
  app/components/avo/alert_component.html.erb
  app/components/avo/alert_component.rb
  app/controllers/avo/actions_controller.rb
  app/javascript/js/controllers.js
  app/javascript/js/controllers/alerts_controller.js
  lib/avo/base_action.rb
  spec/dummy/app/avo/actions/dummy_action.rb
  spec/features/avo/action_filter_spec.rb
  spec/system/avo/actions_spec.rb
Labels: feature

#880 Feature/associations on edit view
  app/components/avo/resource_component.rb
  app/components/avo/views/resource_edit_component.html.erb
  app/components/avo/views/resource_edit_component.rb
  app/components/avo/views/resource_show_component.rb
  app/controllers/avo/associations_controller.rb
  lib/avo/fields/has_and_belongs_to_many_field.rb
  lib/avo/fields/has_many_field.rb
  lib/avo/fields/has_one_field.rb
  spec/system/avo/has_and_belongs_to_many_field_spec.rb
Labels: enhancement

#883 feature: attach_scope for associations
  app/controllers/avo/associations_controller.rb
  app/controllers/avo/search_controller.rb
  lib/avo/fields/belongs_to_field.rb
  lib/avo/fields/has_base_field.rb
  spec/dummy/app/avo/resources/post_resource.rb
  spec/dummy/app/avo/resources/review_resource.rb
  spec/dummy/app/avo/resources/user_resource.rb
  spec/dummy/app/models/project.rb
  spec/features/avo/has_many_attach_scope_spec.rb
Labels: feature

#871 refactor: minor tweaks
  .github/ISSUE_TEMPLATE/blank_issue.md
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/workflows/stale.yml
  lib/tasks/avo_tasks.rake
  spec/dummy/db/seeds.rb
Labels: chore

#884 refactor: cleaner design
  app/assets/stylesheets/avo.css
  app/assets/stylesheets/css/search.css
  app/assets/svgs/heroicons/solid/user-remove.svg
  app/components/avo/actions_component.html.erb
  app/components/avo/button_component.rb
  app/components/avo/filters_component.html.erb
  app/components/avo/index/field_wrapper_component.html.erb
  app/components/avo/index/grid_cover_empty_state_component.html.erb
  app/components/avo/index/table_row_component.html.erb
  app/components/avo/panel_component.html.erb
  app/components/avo/panel_component.rb
  app/components/avo/sidebar/group_component.html.erb
  app/components/avo/sidebar/heading_component.html.erb
  app/components/avo/sidebar/link_component.html.erb
  app/components/avo/sidebar/link_component.rb
  app/components/avo/sidebar_component.html.erb
  app/components/avo/sidebar_profile_component.html.erb
  app/components/avo/views/resource_edit_component.html.erb
  app/components/avo/views/resource_index_component.html.erb
  app/components/avo/views/resource_new_component.html.erb
  app/components/avo/views/resource_show_component.html.erb
  app/controllers/avo/base_controller.rb
  app/controllers/avo/private_controller.rb
  app/helpers/avo/application_helper.rb
  app/javascript/js/controllers/fields/key_value_controller.js
  app/javascript/js/controllers/filter_controller.js
  app/views/avo/actions/show.html.erb
  app/views/avo/partials/_logo.html.erb
  app/views/avo/partials/_navbar.html.erb
  app/views/avo/partials/_table_header.html.erb
  app/views/avo/private/_links_and_buttons.html.erb
  app/views/layouts/avo/application.html.erb
  lib/avo/engine.rb
  spec/dummy/app/avo/resources/user_resource.rb
  spec/features/avo/create_through_record_spec.rb
  spec/features/avo/resource_description_spec.rb
  spec/support/helpers.rb
  spec/system/avo/filters_panel_open_spec.rb
  tailwind.config.js
Labels: refactor

#847 feature: tags field
  Gemfile
  Gemfile.lock
  app/assets/stylesheets/avo.css
  app/assets/stylesheets/css/tags.css
  app/components/avo/fields/concerns/item_labels.rb
  app/components/avo/fields/tags_field/edit_component.html.erb
  app/components/avo/fields/tags_field/edit_component.rb
  app/components/avo/fields/tags_field/index_component.html.erb
  app/components/avo/fields/tags_field/index_component.rb
  app/components/avo/fields/tags_field/show_component.html.erb
  app/components/avo/fields/tags_field/show_component.rb
  app/components/avo/fields/tags_field/tag_component.html.erb
  app/components/avo/fields/tags_field/tag_component.rb
  app/components/avo/index/resource_table_component.html.erb
  app/javascript/js/application.js
  app/javascript/js/controllers.js
  app/javascript/js/controllers/base_controller.js
  app/javascript/js/controllers/fields/tags_field_controller.js
  app/javascript/js/controllers/fields/tags_field_helpers.js
  db/factories.rb
  gemfiles/rails_6.0_ruby_3.0.3.gemfile
  gemfiles/rails_6.0_ruby_3.0.3.gemfile.lock
  gemfiles/rails_6.0_ruby_3.1.0.gemfile
  gemfiles/rails_6.0_ruby_3.1.0.gemfile.lock
  gemfiles/rails_6.1_ruby_3.0.3.gemfile
  gemfiles/rails_6.1_ruby_3.0.3.gemfile.lock
  gemfiles/rails_6.1_ruby_3.1.0.gemfile
  gemfiles/rails_6.1_ruby_3.1.0.gemfile.lock
  gemfiles/rails_7.0_ruby_3.0.3.gemfile
  gemfiles/rails_7.0_ruby_3.0.3.gemfile.lock
  gemfiles/rails_7.0_ruby_3.1.0.gemfile
  gemfiles/rails_7.0_ruby_3.1.0.gemfile.lock
  lib/avo/base_resource.rb
  lib/avo/concerns/handles_field_args.rb
  lib/avo/fields/base_field.rb
  lib/avo/fields/tags_field.rb
  lib/avo/hosts/record_host.rb
  lib/avo/licensing/pro_license.rb
  lib/generators/avo/templates/locales/avo.en.yml
  package.json
  spec/dummy/app/avo/resources/course_resource.rb
  spec/dummy/app/avo/resources/post_resource.rb
  spec/dummy/app/models/course.rb
  spec/dummy/app/models/post.rb
  spec/dummy/config/initializers/avo.rb
  spec/dummy/db/migrate/20220414174420_acts_as_taggable_on_migration.acts_as_taggable_on_engine.rb
  spec/dummy/db/migrate/20220414174421_add_missing_unique_indices.acts_as_taggable_on_engine.rb
  spec/dummy/db/migrate/20220414174422_add_taggings_counter_cache_to_tags.acts_as_taggable_on_engine.rb
  spec/dummy/db/migrate/20220414174423_add_missing_taggable_index.acts_as_taggable_on_engine.rb
  spec/dummy/db/migrate/20220414174424_change_collation_for_tag_names.acts_as_taggable_on_engine.rb
  spec/dummy/db/migrate/20220414174425_add_missing_indexes_on_taggings.acts_as_taggable_on_engine.rb
  spec/dummy/db/migrate/20220414174426_add_tenant_to_taggings.acts_as_taggable_on_engine.rb
  spec/dummy/db/migrate/20220415123056_add_skills_to_courses.rb
  spec/dummy/db/schema.rb
  spec/dummy/test/models/review_test.rb
  spec/system/avo/avo_collapsable_menus_spec.rb
  spec/system/avo/has_many_spec.rb
  spec/system/avo/tags_spec.rb
  tailwind.config.js
  yarn.lock
Labels: feature

#892 fix: broken search on back action
  app/javascript/js/controllers/search_controller.js
  app/views/avo/partials/_global_search.html.erb
  app/views/avo/partials/_resource_search.html.erb
Labels: fix

#893 chore: add bundler integrity
  Gemfile
  Gemfile.lock
Labels: chore

#902 fix: broken pagination on per page switch
  app/components/avo/paginator_component.html.erb
Labels: fix

#903 feature: authorization in menus
  lib/avo/hosts/base_host.rb
  spec/dummy/config/initializers/avo.rb
  spec/features/avo/belongs_to_polymorphic_spec.rb
  spec/support/wait_for_loaded.rb
Labels: feature

#906 return field name if field is has_one
  app/components/avo/fields/has_one_field/show_component.html.erb
  app/components/avo/views/resource_show_component.html.erb
  app/components/avo/views/resource_show_component.rb
  spec/dummy/app/avo/resources/user_resource.rb
  spec/system/avo/has_one_field_name_spec.rb
Labels: fix

#905 feature: initialize the parent and attach the grandparent in attach_scope
  app/components/avo/fields/belongs_to_field/autocomplete_component.html.erb
  app/controllers/avo/search_controller.rb
  app/javascript/js/controllers/search_controller.js
  spec/dummy/app/avo/resources/team_membership_resource.rb
  spec/dummy/app/avo/resources/team_resource.rb
  spec/dummy/app/models/user.rb
  spec/dummy/config/initializers/avo.rb
  spec/system/avo/query_scope_spec.rb
Labels: feature

#908 chore: minor tweaks
  app/assets/svgs/heroicons/solid/user-remove.svg
  app/components/avo/fields/tags_field/index_component.html.erb
  spec/dummy/app/avo/resources/post_resource.rb
  spec/dummy/app/avo/resources/team_membership_resource.rb
  spec/dummy/app/models/team_membership.rb
  spec/dummy/config/initializers/avo.rb
Labels: chore

#912 refactor: move cards to their own controller
  app/controllers/avo/cards_controller.rb
  app/controllers/avo/dashboards_controller.rb
  app/controllers/avo/home_controller.rb
  app/views/avo/cards/_chartkick_card.html.erb
  app/views/avo/cards/_metric_card.html.erb
  app/views/avo/cards/show.html.erb
  config/routes.rb
  spec/dummy/config/initializers/avo.rb
  spec/features/avo/app_spec.rb
  spec/features/avo/configuration_home_path_spec.rb
Labels: refactor
