Repository avo-hq/avo, pull requests merged in 2022-09, with the labels that each got.

#1197 fix: to_sql crashes for models that live in different schemas
  app/components/avo/index/resource_table_component.rb
Labels: fix

#1171 feature: model to resource mapping
  app/components/avo/base_component.rb
  app/components/avo/resource_component.rb
  app/components/avo/views/resource_edit_component.rb
  app/controllers/avo/team_users_controller.rb
  lib/avo/base_resource.rb
  lib/avo/concerns/fetches_things.rb
  lib/avo/configuration.rb
  lib/generators/avo/templates/initializer/avo.tt
  spec/dummy/app/avo/resources/team_user_resource.rb
  spec/dummy/config/initializers/avo.rb
Labels: feature

#1193 feature: automate tailwind installation to Avo
  .dockerignore
  .gitignore
  CONTRIBUTING.MD
  app/assets/stylesheets/avo.base.css
  app/javascript/avo.base.js
  app/views/layouts/avo/application.html.erb
  lib/generators/avo/base_generator.rb
  lib/generators/avo/tailwindcss/install_generator.rb
  lib/generators/avo/templates/tailwindcss/Procfile.dev
  lib/generators/avo/templates/tailwindcss/avo.tailwind.css
  lib/tasks/avo_tasks.rake
  lib/tasks/tailwindcss_rails.rake
  package.json
Labels: feature

#1195 feature: automate custom JS installation in Avo
  lib/avo/svg_finder.rb
  lib/generators/avo/js/install_generator.rb
  lib/generators/avo/templates/js/avo.custom.js
Labels: feature

#1201 chore: minor assets refactor
  app/views/layouts/avo/application.html.erb
  spec/dummy/app/javascript/avo.custom.js
  spec/dummy/app/views/avo/partials/_head.html.erb
Labels: chore

#1213 fix/standalone_action_render_on_empty_table
  app/javascript/js/controllers/action_controller.js
Labels: fix

#1133 feature: branding
  app/assets/stylesheets/avo.base.css
  app/assets/stylesheets/css/fields/progress.css
  app/assets/stylesheets/css/pagination.css
  app/assets/stylesheets/css/search.css
  app/assets/stylesheets/css/sidebar.css
  app/assets/stylesheets/css/tags.css
  app/assets/svgs/failed_to_load.svg
  app/assets/svgs/grid-empty-state.svg
  app/assets/svgs/table-empty-state.svg
  app/components/avo/actions_component.html.erb
  app/components/avo/actions_component.rb
  app/components/avo/button_component.html.erb
  app/components/avo/button_component.rb
  app/components/avo/fields/boolean_field/edit_component.html.erb
  app/components/avo/fields/common/progress_bar_component.html.erb
  app/components/avo/fields/common/progress_bar_component.rb
  app/components/avo/fields/progress_bar_field/index_component.html.erb
  app/components/avo/fields/progress_bar_field/show_component.html.erb
  app/components/avo/fields/tags_field/edit_component.html.erb
  app/components/avo/index/resource_grid_component.html.erb
  app/components/avo/index/resource_table_component.html.erb
  app/components/avo/profile_item_component.html.erb
  app/components/avo/sidebar_component.html.erb
  app/components/avo/sidebar_profile_component.html.erb
  app/helpers/avo/actions_helper.rb
  app/helpers/avo/attachments_helper.rb
  app/helpers/avo/resources_helper.rb
  app/javascript/avo.base.js
  app/javascript/js/controllers/fields/trix_field_controller.js
  app/javascript/js/controllers/item_select_all_controller.js
  app/javascript/js/controllers/item_selector_controller.js
  app/views/avo/actions/show.html.erb
  app/views/avo/associations/new.html.erb
  app/views/avo/base/_multiple_select_filter.html.erb
  app/views/avo/base/_text_filter.html.erb
  app/views/avo/partials/_branding.html.erb
  app/views/avo/partials/_header.html.erb
  app/views/avo/partials/_logo.html.erb
  app/views/avo/private/_links_and_buttons.html.erb
  app/views/avo/private/design.html.erb
  app/views/kaminari/_first_page.html.erb
  app/views/kaminari/_last_page.html.erb
  app/views/kaminari/_next_page.html.erb
  app/views/kaminari/_page.html.erb
  app/views/kaminari/_prev_page.html.erb
  app/views/layouts/avo/application.html.erb
  lib/avo/configuration.rb
  lib/avo/configuration/branding.rb
  lib/avo/dashboards/chartkick_card.rb
  lib/avo/licensing/pro_license.rb
  lib/generators/avo/templates/initializer/avo.tt
  safelist.txt
  scripts/export-tailwind-safelist.js
  spec/components/avo/empty_state_component_spec.rb
  spec/components/avo/index/grid_cover_empty_state_component_spec.rb
  spec/dummy/config/initializers/avo.rb
  tailwind.config.js
Labels: feature

#1228 fix: minor fiexs around the asset settings
  app/views/layouts/avo/application.html.erb
  lib/avo/configuration/branding.rb
  lib/generators/avo/tailwindcss/install_generator.rb
  lib/generators/avo/templates/initializer/avo.tt
  lib/generators/avo/templates/tailwindcss/Procfile.dev
  lib/tasks/tailwindcss_rails.rake
Labels: fix

#1236 refactor: add pre_head partial
  app/views/avo/partials/_pre_head.html.erb
  app/views/layouts/avo/application.html.erb
  lib/generators/avo/base_generator.rb
  lib/generators/avo/eject_generator.rb
  lib/generators/avo/js/install_generator.rb
  lib/generators/avo/tailwindcss/install_generator.rb
  spec/dummy/app/views/avo/partials/_pre_head.html.erb
Labels: refactor

#1238 fix: has_and_belongs_to_may grid view
  app/components/avo/index/grid_item_component.html.erb
  app/components/avo/index/grid_item_component.rb
  app/components/avo/index/resource_grid_component.html.erb
  app/components/avo/index/resource_grid_component.rb
  app/components/avo/views/resource_index_component.html.erb
Labels: fix

#1241 fix: read-only trix field
  app/components/avo/views/resource_edit_component.html.erb
  app/components/avo/views/resource_edit_component.rb
Labels: fix

#1181 feature: create button on has one association
  app/components/avo/fields/has_one_field/show_component.html.erb
  app/components/avo/fields/has_one_field/show_component.rb
  spec/dummy/app/policies/user_policy.rb
  spec/features/avo/create_has_one_spec.rb
Labels: feature

#1237 feature: add data attributes to sidebar items
  app/components/avo/sidebar/item_switcher_component.html.erb
  app/components/avo/sidebar/link_component.html.erb
  app/components/avo/sidebar/link_component.rb
  lib/avo/menu/base_item.rb
  lib/avo/menu/builder.rb
  spec/dummy/config/initializers/avo.rb
Labels: feature

#1209 feature: skip_show_view
  app/components/avo/fields/belongs_to_field/index_component.html.erb
  app/components/avo/fields/belongs_to_field/show_component.html.erb
  app/components/avo/fields/belongs_to_field/show_component.rb
  app/components/avo/fields/external_image_field/index_component.html.erb
  app/components/avo/fields/file_field/index_component.html.erb
  app/components/avo/fields/gravatar_field/index_component.html.erb
  app/components/avo/fields/id_field/index_component.html.erb
  app/components/avo/fields/index_component.rb
  app/components/avo/fields/text_field/index_component.html.erb
  app/components/avo/index/grid_item_component.html.erb
  app/components/avo/index/grid_item_component.rb
  app/components/avo/index/resource_controls_component.rb
  app/components/avo/index/resource_grid_component.rb
  app/components/avo/resource_component.rb
  app/components/avo/views/resource_edit_component.html.erb
  app/components/avo/views/resource_edit_component.rb
  app/components/avo/views/resource_show_component.rb
  app/controllers/avo/application_controller.rb
  app/controllers/avo/associations_controller.rb
  app/controllers/avo/base_controller.rb
  app/helpers/avo/url_helpers.rb
  lib/avo/base_resource_tool.rb
  lib/avo/configuration.rb
  lib/avo/fields/has_and_belongs_to_many_field.rb
  lib/avo/fields/has_base_field.rb
  lib/avo/fields/has_many_field.rb
  spec/dummy/config/initializers/avo.rb
  spec/features/avo/create_has_one_spec.rb
  spec/features/avo/create_through_record_spec.rb
  spec/features/avo/has_many_field_spec.rb
  spec/features/avo/skip_show_view_spec.rb
Labels: feature

#1251 chore: add product resource
  spec/dummy/app/avo/resources/product_resource.rb
  spec/dummy/app/controllers/avo/products_controller.rb
  spec/dummy/app/models/product.rb
  spec/dummy/config/initializers/avo.rb
  spec/dummy/db/migrate/20220920091039_create_products.rb
  spec/dummy/db/schema.rb
  spec/dummy/db/seed_files/iphone.jpg
  spec/dummy/db/seed_files/ipod.jpg
  spec/dummy/db/seed_files/macbook.jpg
  spec/dummy/db/seed_files/watch.jpg
  spec/dummy/db/seeds.rb
  spec/dummy/test/factories/products.rb
Labels: chore

#1261 fix: recursive resources broken
  app/components/avo/base_component.rb
  app/controllers/avo/base_controller.rb
  spec/dummy/app/models/spouse.rb
  spec/system/recursive_resources_spec.rb
Labels: fix

#1260 fix: date time broken on back action
  app/javascript/js/controllers/fields/date_field_controller.js
Labels: fix

#1263 refactor: moved some things around in the initializer
  spec/dummy/config/initializers/avo.rb
Labels: refactor

#1252 chore: update turbo to 7.2.0
  Gemfile
  Gemfile.lock
  app/javascript/js/controllers/search_controller.js
  avo.gemspec
  spec/features/avo/search_spec.rb
  spec/system/avo/belongs_to_polymorphic_spec.rb
  spec/system/avo/user_forms_spec.rb
  yarn.lock
Labels: chore

#1266 fix: recursive resources duplicated hydration
  app/components/avo/base_component.rb
Labels: fix

#1272 Add turkish support
  lib/generators/avo/templates/locales/avo.tr.yml
Labels: enhancement

#1264 chore: separate tests
  .github/workflows/test.yml
Labels: chore

#1274 fix: add html attributes to grid items
  app/components/avo/index/grid_item_component.html.erb
  spec/dummy/app/avo/resources/product_resource.rb
  spec/features/avo/generators/locales_generator_spec.rb
  spec/features/avo/ordering_spec.rb
  spec/support/wait_for_loaded.rb
Labels: fix

#1277 chore: transform some system tests to feature
  spec/features/avo/badge_field_spec.rb
  spec/features/avo/belongs_to_spec.rb
  spec/features/avo/default_field_spec.rb
  spec/features/avo/gravatar_field_spec.rb
  spec/features/avo/help_text_spec.rb
  spec/features/avo/link_to_resource_spec.rb
  spec/features/avo/nullable_field_spec.rb
  spec/features/avo/placeholders_spec.rb
  spec/features/avo/status_field_spec.rb
  spec/features/avo/text_field_spec.rb
  spec/system/avo/belongs_to_spec.rb
  spec/system/avo/currency_field_spec.rb
  spec/system/avo/status_field_spec.rb
Labels: chore
