Repository avo-hq/avo, pull requests merged in 2022-11, with the labels that each got.

#1385 fix: destroy the search modal when disconnected
  app/javascript/js/controllers/search_controller.js
Labels: fix

#1387 fix: don't raise errors on community when pundit is missing
  lib/avo.rb
  lib/avo/services/authorization_clients/nil_client.rb
  lib/avo/services/authorization_service.rb
Labels: fix

#1388 fix: malformed root url for javascript
  app/helpers/avo/application_helper.rb
Labels: fix

#1389 feature: default executes in host
  app/javascript/js/controllers/search_controller.js
  lib/avo/fields/base_field.rb
  lib/avo/fields/concerns/has_default.rb
  lib/avo/fields/concerns/is_readonly.rb
  lib/avo/fields/concerns/is_required.rb
  lib/avo/hosts/resource_view_record_host.rb
  spec/features/avo/default_field_spec.rb
Labels: feature

#1298 feature: filter visibility
  app/components/avo/actions_component.rb
  app/controllers/avo/base_controller.rb
  lib/avo/base_action.rb
  lib/avo/filters/base_filter.rb
  lib/avo/hosts/visibility_host.rb
  lib/avo/resources/controls/action.rb
  lib/generators/avo/templates/action.tt
  lib/generators/avo/templates/filters/boolean_filter.tt
  lib/generators/avo/templates/filters/multiple_select_filter.tt
  lib/generators/avo/templates/filters/select_filter.tt
  lib/generators/avo/templates/filters/text_filter.tt
  spec/dummy/app/avo/actions/dummy_action.rb
  spec/dummy/app/avo/actions/toggle_admin.rb
  spec/dummy/app/avo/filters/name_filter.rb
Labels: feature, Stale, hacktoberfest

#1379 feature: persistent filters
  app/components/avo/filters_component.html.erb
  app/components/avo/filters_component.rb
  app/controllers/avo/base_controller.rb
  lib/avo/concerns/filters_session_handler.rb
  lib/avo/configuration.rb
  lib/generators/avo/templates/initializer/avo.tt
  spec/dummy/app/avo/filters/comment_body_filter.rb
  spec/dummy/app/avo/resources/comment_resource.rb
  spec/system/avo/filters/persist_filters_spec.rb
Labels: feature

#1395 fix: issue of showing custom label for actionlist
  app/components/avo/actions_component.html.erb
  app/components/avo/actions_component.rb
  app/components/avo/views/resource_show_component.html.erb
  spec/dummy/app/avo/resources/fish_resource.rb
  spec/features/avo/custom_resource_controls_spec.rb
Labels: enhancement

#1402 chore: remove comment from tempalte file and remove manifester gem
  Gemfile
  Gemfile.lock
  lib/generators/avo/templates/resource/controller.tt
Labels: chore

#1408 feature: make sign-out path name configurable
  app/components/avo/sidebar_profile_component.rb
  bin/test
  lib/avo/configuration.rb
  spec/components/avo/sidebar_profile_component_spec.rb
  spec/rails_helper.rb
Labels: feature

#1432 fix & refactor: select field
  app/components/avo/fields/select_field/edit_component.html.erb
  lib/avo/fields/select_field.rb
  spec/dummy/app/avo/resources/product_resource.rb
  spec/dummy/app/models/city.rb
  spec/features/avo/native_fields_spec.rb
  spec/features/avo/select_field_spec.rb
Labels: fix, refactor

#1403 feature: arguments on filters and actions
  app/components/avo/card_component.html.erb
  app/components/avo/card_component.rb
  app/controllers/avo/actions_controller.rb
  app/controllers/avo/base_controller.rb
  lib/avo/base_action.rb
  lib/avo/base_card.rb
  lib/avo/base_resource.rb
  lib/avo/concerns/breadcrumbs.rb
  lib/avo/dashboards/base_dashboard.rb
  lib/avo/filters/base_filter.rb
  lib/avo/hosts/visibility_host.rb
  spec/dummy/app/avo/actions/dummy_action.rb
  spec/dummy/app/avo/dashboards/dashy.rb
  spec/dummy/app/avo/filters/name_filter.rb
  spec/dummy/app/avo/resources/fish_resource.rb
  spec/dummy/app/views/avo/cards/_custom_card.html.erb
Labels: feature

#1455 fix: get correct search results count
  app/controllers/avo/search_controller.rb
Labels: fix

#1454 fix: select all when query can't be converted to_sql
  app/components/avo/index/resource_table_component.rb
  app/javascript/js/controllers/item_select_all_controller.js
Labels: fix

#1446 fix: resource getting wrong model
  app/controllers/avo/application_controller.rb
  app/controllers/avo/associations_controller.rb
  app/controllers/avo/base_controller.rb
  lib/avo/base_action.rb
  lib/avo/filters/base_filter.rb
  lib/avo/hosts/visibility_host.rb
Labels: fix

#1442 fix: time fields without relative don't cast the time
  lib/avo/concerns/handles_field_args.rb
  lib/avo/fields/base_field.rb
  spec/components/avo/sidebar_profile_component_spec.rb
  spec/dummy/app/avo/resources/comment_resource.rb
  spec/dummy/app/avo/resources/team_resource.rb
  spec/system/avo/date_time_fields/date_time_eastern_spec.rb
  spec/system/avo/date_time_fields/date_time_utc_spec.rb
  spec/system/avo/date_time_fields/date_time_western_spec.rb
Labels: fix

#1465 feature: callable action message
  app/views/avo/actions/show.html.erb
  lib/avo/base_action.rb
  lib/avo/hosts/resource_record_host.rb
  spec/dummy/app/avo/actions/release_fish.rb
  spec/system/avo/custom_resource_controls_spec.rb
Labels: feature
