Repository avo-hq/avo, pull requests merged in 2022-03, with the labels that each got.

#708 turbo_frame_wrap: render alerts only for turbo requests
  app/components/avo/turbo_frame_wrapper_component.html.erb
  app/controllers/avo/application_controller.rb
Labels: refactor

#710 fix: missing inverse_of crashes has_many association
  lib/avo/base_resource.rb
  spec/dummy/app/models/user.rb
Labels: fix

#712 feature: reorder records
  Gemfile
  Gemfile.lock
  app/assets/svgs/arrow-down.svg
  app/assets/svgs/arrow-up.svg
  app/assets/svgs/download-solid-reversed.svg
  app/assets/svgs/download-solid.svg
  app/assets/svgs/switch-vertical.svg
  app/components/avo/base_component.rb
  app/components/avo/index/grid_item_component.html.erb
  app/components/avo/index/ordering/base_component.rb
  app/components/avo/index/ordering/button_component.html.erb
  app/components/avo/index/ordering/button_component.rb
  app/components/avo/index/ordering/buttons_component.html.erb
  app/components/avo/index/ordering/buttons_component.rb
  app/components/avo/index/resource_controls_component.html.erb
  app/components/avo/index/resource_controls_component.rb
  app/components/avo/index/table_row_component.html.erb
  app/components/avo/resource_component.rb
  app/controllers/avo/base_controller.rb
  app/helpers/avo/url_helpers.rb
  app/javascript/js/application.js
  config/routes.rb
  gemfiles/rails_6.0_ruby_3.0.3.gemfile
  gemfiles/rails_6.0_ruby_3.0.3.gemfile.lock
  gemfiles/rails_6.0_ruby_3.1.0.gemfile
  gemfiles/rails_6.0_ruby_3.1.0.gemfile.lock
  gemfiles/rails_6.1_ruby_3.0.3.gemfile
  gemfiles/rails_6.1_ruby_3.0.3.gemfile.lock
  gemfiles/rails_6.1_ruby_3.1.0.gemfile
  gemfiles/rails_6.1_ruby_3.1.0.gemfile.lock
  gemfiles/rails_7.0_ruby_3.0.3.gemfile
  gemfiles/rails_7.0_ruby_3.0.3.gemfile.lock
  gemfiles/rails_7.0_ruby_3.1.0.gemfile
  gemfiles/rails_7.0_ruby_3.1.0.gemfile.lock
  lib/avo/base_resource.rb
  lib/avo/licensing/pro_license.rb
  package.json
  spec/dummy/app/avo/resources/course_link_resource.rb
  spec/dummy/app/avo/resources/course_resource.rb
  spec/dummy/app/models/course.rb
  spec/dummy/app/models/course/link.rb
  spec/dummy/config/locales/avo.en.yml
  spec/dummy/db/migrate/20220302214148_add_position_to_course_links.rb
  spec/dummy/db/schema.rb
  spec/system/avo/ordering_spec.rb
  yarn.lock
Labels: feature

#717 fix: resource ordering broken in association
  Gemfile.lock
  app/components/avo/base_component.rb
  app/components/avo/index/ordering/base_component.rb
  app/components/avo/index/ordering/button_component.html.erb
  app/components/avo/index/ordering/button_component.rb
  app/components/avo/index/ordering/buttons_component.html.erb
  app/components/avo/index/ordering/buttons_component.rb
  app/components/avo/index/resource_controls_component.html.erb
  app/components/avo/index/resource_controls_component.rb
  app/components/avo/resource_component.rb
  app/controllers/avo/base_controller.rb
  app/controllers/avo/relations_controller.rb
  avo.gemspec
  config/routes.rb
  lib/avo/base_resource.rb
  lib/avo/hosts/ordering.rb
  spec/dummy/app/avo/resources/course_link_resource.rb
  spec/dummy/app/models/course/link.rb
Labels: fix

#730 chore: release drafter 1.x
  .github/release-drafter-1x.yml
  .github/workflows/release-notes.yml
Labels: chore

#732 chore: release drafter 1.x (#730)
  .github/release-drafter-1x.yml
  .github/workflows/release-notes.yml
Labels: chore

#734 chore: release drafter 1.x (#730) (#732)
  .github/release-drafter-1x.yml
  .github/workflows/release-notes.yml
Labels: chore

#736 chore: minor tweaks
  Gemfile.lock
  README.md
  app/components/avo/alert_component.html.erb
  app/components/avo/button_component.rb
  app/components/avo/fields/common/single_file_viewer_component.html.erb
  app/components/avo/panel_component.html.erb
  app/components/avo/panel_component.rb
  app/components/avo/sidebar_profile_component.html.erb
  app/components/avo/views/resource_index_component.html.erb
  app/controllers/avo/associations_controller.rb
  app/controllers/avo/base_controller.rb
  app/javascript/avo.js
  app/views/avo/associations/new.html.erb
  app/views/avo/partials/_view_toggle_button.html.erb
  avo.gemspec
  config/routes.rb
  lib/avo/base_resource.rb
  lib/avo/dynamic_router.rb
  public/avo-assets/logo-on-white.png
  scripts/build.sh
  spec/dummy/app/avo/dashboards/bashy.rb
  spec/dummy/app/avo/dashboards/sales.rb
  spec/features/avo/resource_description_spec.rb
  spec/system/avo/avo_dashboards_spec.rb
  spec/system/avo/date_spec.rb
  spec/system/avo/has_and_belongs_to_many_field_spec.rb
Labels: chore

#746 fix: records with no title have show view broken
  lib/avo/base_resource.rb
  spec/features/avo/show_page_spec.rb
Labels: fix

#748 fix: alert dropdowns on small screens
  app/components/avo/actions_component.html.erb
  app/components/avo/panel_component.html.erb
  app/components/avo/panel_component.rb
Labels: fix

#749 fix: downloads in actions won't work for forms with data-remote=true
  lib/avo/base_action.rb
Labels: fix

#750 chore: add debug message on failed frames
  app/javascript/avo.js
  app/views/avo/home/failed_to_load.html.erb
  app/views/avo/partials/_failed_state.html.erb
  spec/dummy/app/avo/resources/user_resource.rb
Labels: chore

#758 fix: has_many turbo frame crash
  app/components/avo/blank_field_component.html.erb
  app/components/avo/blank_field_component.rb
  lib/avo/fields/base_field.rb
  spec/components/avo/blank_field_component_spec.rb
Labels: fix

#761 fix: use local on forms
  .github/release-drafter.yml
  .github/workflows/release-notes.yml
  app/components/avo/actions_component.html.erb
  app/components/avo/index/resource_controls_component.html.erb
  app/components/avo/panel_component.html.erb
  app/components/avo/panel_component.rb
  app/components/avo/views/resource_edit_component.html.erb
  app/components/avo/views/resource_show_component.html.erb
  app/views/avo/actions/show.html.erb
  app/views/avo/associations/new.html.erb
Labels: fix

#762 fix: wrong redirect after validation failed when wediting a has many association
  app/components/avo/referrer_params_component.html.erb
  app/components/avo/referrer_params_component.rb
  app/components/avo/views/resource_edit_component.html.erb
  app/components/avo/views/resource_new_component.html.erb
  app/controllers/avo/base_controller.rb
  spec/components/avo/referrer_params_component_spec.rb
  spec/dummy/app/models/comment.rb
Labels: fix

#765 feature: optionally show buttons on footer forms
  app/components/avo/panel_component.html.erb
  app/components/avo/panel_component.rb
  app/components/avo/views/resource_edit_component.html.erb
  app/components/avo/views/resource_new_component.html.erb
  lib/avo/configuration.rb
Labels: feature

#744 feature: dashboards visibility
  app/assets/svgs/save.svg
  app/components/avo/sidebar_component.rb
  app/controllers/avo/application_controller.rb
  app/controllers/avo/dashboards_controller.rb
  lib/avo/app.rb
  lib/avo/dashboards/base_dashboard.rb
  lib/avo/hosts/dashboard_visibility.rb
  lib/generators/avo/templates/dashboards/dashboard.tt
  spec/dummy/app/avo/dashboards/dashy.rb
  spec/dummy/app/avo/dashboards/hidden_dash.rb
  spec/system/avo/dashboards_spec.rb
Labels: feature

#767 feature: hide resources from global search
  app/controllers/avo/search_controller.rb
  lib/avo/base_resource.rb
  spec/dummy/app/avo/resources/team_membership_resource.rb
  spec/features/avo/hidden_from_global_search_spec.rb
  spec/rails_helper.rb
  spec/support/request_helpers.rb
Labels: feature

#768 fix: file index field does not apply constraints to the image
  app/components/avo/fields/badge_field/index_component.html.erb
  app/components/avo/fields/boolean_field/index_component.html.erb
  app/components/avo/fields/external_image_field/index_component.html.erb
  app/components/avo/fields/file_field/index_component.html.erb
  app/components/avo/fields/file_field/index_component.rb
  app/components/avo/fields/gravatar_field/index_component.html.erb
  app/components/avo/fields/progress_bar_field/index_component.html.erb
  app/components/avo/index/field_wrapper_component.html.erb
  app/components/avo/index/field_wrapper_component.rb
  lib/avo/fields/external_image_field.rb
  spec/dummy/app/avo/resources/post_resource.rb
  spec/dummy/app/components/avo/fields/color_picker_field/index_component.html.erb
Labels: fix
