Repository avo-hq/avo, pull requests merged in 2022-12, with the labels that each got.

#1470 fix: card missing current_user
  app/controllers/avo/dashboards/cards_controller.rb
  lib/avo/base_card.rb
  spec/dummy/app/avo/cards/metric_from_param.rb
  spec/dummy/app/avo/dashboards/dashy.rb
  spec/dummy/config/boot.rb
  spec/features/avo/metric_receives_params_spec.rb
Labels: fix

#1476 refactor: trix id not unique when used as native
  app/components/avo/fields/trix_field/edit_component.html.erb
  app/components/avo/fields/trix_field/edit_component.rb
Labels: refactor

#1474 fix: flash messages
  app/controllers/avo/base_controller.rb
Labels: fix

#1479 fix: expose the parent record from association policy methods
  app/components/avo/resource_component.rb
  spec/dummy/app/policies/team_policy.rb
  spec/features/avo/authorization_spec.rb
  spec/support/wait_for_loaded.rb
Labels: fix

#1471 feature: add disabled option
  app/components/avo/fields/belongs_to_field/edit_component.rb
  app/components/avo/fields/boolean_field/edit_component.html.erb
  app/components/avo/fields/boolean_group_field/edit_component.html.erb
  app/components/avo/fields/code_field/edit_component.html.erb
  app/components/avo/fields/country_field/edit_component.html.erb
  app/components/avo/fields/date_field/edit_component.html.erb
  app/components/avo/fields/date_time_field/edit_component.html.erb
  app/components/avo/fields/edit_component.rb
  app/components/avo/fields/external_image_field/edit_component.html.erb
  app/components/avo/fields/file_field/edit_component.html.erb
  app/components/avo/fields/files_field/edit_component.html.erb
  app/components/avo/fields/has_one_field/show_component.html.erb
  app/components/avo/fields/markdown_field/edit_component.html.erb
  app/components/avo/fields/markdown_field/show_component.html.erb
  app/components/avo/fields/number_field/edit_component.html.erb
  app/components/avo/fields/password_field/edit_component.html.erb
  app/components/avo/fields/progress_bar_field/edit_component.html.erb
  app/components/avo/fields/select_field/edit_component.html.erb
  app/components/avo/fields/show_component.rb
  app/components/avo/fields/status_field/edit_component.html.erb
  app/components/avo/fields/tags_field/edit_component.html.erb
  app/components/avo/fields/text_field/edit_component.html.erb
  app/components/avo/fields/textarea_field/edit_component.html.erb
  app/components/avo/fields/time_field/edit_component.html.erb
  app/components/avo/fields/trix_field/edit_component.html.erb
  lib/avo/fields/base_field.rb
  lib/avo/fields/concerns/is_disabled.rb
  lib/generators/avo/templates/field/components/edit_component.html.erb.tt
  spec/dummy/app/components/avo/fields/color_picker_field/edit_component.html.erb
Labels: feature

#1484 fix: correctly parse and build the trix attachment path
  app/javascript/js/controllers/fields/trix_field_controller.js
Labels: fix

#1489 fix: valid association authorization scope
  app/controllers/avo/associations_controller.rb
  spec/dummy/app/policies/team_policy.rb
  spec/features/avo/authorization_spec.rb
Labels: fix

#1486 refactor: allow nil user in authorization service
  lib/avo/services/authorization_service.rb
Labels: refactor

#1491 feature: dashboards authorization
  app/controllers/avo/application_controller.rb
  app/controllers/avo/dashboards_controller.rb
  lib/avo/dashboards/base_dashboard.rb
  spec/dummy/app/avo/dashboards/dashy.rb
Labels: feature

#1492 chore: update ruby requirement
  Gemfile.lock
  avo.gemspec
Labels: chore, Security
