Repository avo-hq/avo, pull requests merged in 2022-04, with the labels that each got.

#789 feature: after create/update path
  app/controllers/avo/base_controller.rb
  lib/avo/base_resource.rb
  spec/dummy/app/avo/resources/comment_resource.rb
  spec/features/avo/after_create_update_path_spec.rb
  spec/features/avo/belongs_to_polymorphic_spec.rb
Labels: feature

#790 chore: display invalid fields errors
  app/components/avo/alert_component.html.erb
  app/components/avo/alert_component.rb
  app/components/avo/views/resource_show_component.html.erb
  app/components/avo/views/resource_show_component.rb
  lib/avo/base_action.rb
  lib/avo/base_resource.rb
  lib/avo/fields_collector.rb
  spec/features/avo/invalid_field_spec.rb
Labels: chore

#795 fix: add support for namespaced models
  .github/workflows/release-notes.yml
  app/helpers/avo/url_helpers.rb
  app/views/avo/partials/_profile_dropdown.html.erb
  lib/avo/base_resource.rb
  spec/dummy/config/application.rb
Labels: fix

#796 fix: add support for namespaced models
  Gemfile.lock
  app/helpers/avo/url_helpers.rb
  lib/avo/base_resource.rb
  spec/dummy/config/application.rb
Labels: fix

#798 fix: missing target for controller in profile image
  app/components/avo/filters_component.html.erb
  app/components/avo/sidebar_profile_component.html.erb
  spec/dummy/app/avo/resources/person_resource.rb
  spec/dummy/app/avo/resources/post_resource.rb
  spec/dummy/app/avo/resources/team_resource.rb
Labels: fix

#800 chore: autoreload lib directory and initializer in development
  .github/workflows/test.yml
  lib/avo/dynamic_router.rb
  lib/avo/engine.rb
  lib/avo/reloader.rb
  spec/system/avo/has_many_spec.rb
Labels: chore

#808 chore: add hotwire livereload
  Gemfile
  Gemfile.lock
  app/views/layouts/avo/application.html.erb
  spec/dummy/config/environments/development.rb
Labels: chore

#809 fix: save button broken on safari
  app/components/avo/button_component.rb
  app/components/avo/views/resource_edit_component.html.erb
  app/components/avo/views/resource_new_component.html.erb
  app/components/avo/views/resource_show_component.html.erb
  app/javascript/js/controllers/loading_button_controller.js
  spec/features/avo/destroy_record_spec.rb
Labels: fix

#810 feature: hide record selector
  app/components/avo/index/grid_item_component.html.erb
  app/components/avo/index/table_row_component.html.erb
  app/views/avo/partials/_table_header.html.erb
  lib/avo/base_resource.rb
  spec/dummy/app/avo/resources/comment_resource.rb
  spec/features/avo/record_selector_spec.rb
Labels: feature

#811 feature: allow via detaching
  app/components/avo/fields/belongs_to_field/autocomplete_component.html.erb
  app/components/avo/fields/belongs_to_field/edit_component.rb
  lib/avo/fields/belongs_to_field.rb
  spec/dummy/app/avo/resources/review_resource.rb
  spec/dummy/config/environments/development.rb
  spec/features/avo/allow_via_detaching_spec.rb
Labels: feature

#817 fix: panel component title alignment
  app/components/avo/panel_component.html.erb
  lib/avo/reloader.rb
Labels: fix

#818 fix: unscrollable searchable belongs_to
  app/javascript/js/controllers/search_controller.js
Labels: fix

#819 fix: resource description truncated
  app/components/avo/panel_component.html.erb
Labels: fix

#821 fix: xss vulnerability in search
  app/javascript/js/controllers/search_controller.js
Labels: fix

#823 feature: text-align right and center on index view
  .github/release-drafter.yml
  app/components/avo/index/field_wrapper_component.rb
  lib/avo/fields/base_field.rb
  spec/dummy/app/avo/resources/project_resource.rb
Labels: feature

#827 fix: trix attach action
  app/controllers/avo/application_controller.rb
Labels: fix

#840 fix: change param from locale->set_locale
  app/controllers/avo/application_controller.rb
Labels: fix

#849 fix: reloader broke the initializer
  lib/avo/reloader.rb
Labels: fix

#850 refactor: use default cllapsed state for menus
  .codeclimate.yml
  app/components/avo/sidebar/group_component.html.erb
  app/components/avo/sidebar/heading_component.html.erb
  app/components/avo/sidebar/heading_component.rb
  app/components/avo/sidebar/section_component.html.erb
  app/javascript/avo.js
  app/javascript/js/controllers/menu_controller.js
  spec/dummy/config/initializers/avo.rb
Labels: refactor

#854 fix: authorization logic error
  lib/avo/services/authorization_service.rb
Labels: fix

#855 chore: add annotate gem
  CONTRIBUTING.MD
  Gemfile
  Gemfile.lock
  spec/dummy/app/models/comment.rb
  spec/dummy/app/models/course.rb
  spec/dummy/app/models/course/link.rb
  spec/dummy/app/models/fish.rb
  spec/dummy/app/models/person.rb
  spec/dummy/app/models/post.rb
  spec/dummy/app/models/project.rb
  spec/dummy/app/models/review.rb
  spec/dummy/app/models/spouse.rb
  spec/dummy/app/models/team.rb
  spec/dummy/app/models/team_membership.rb
  spec/dummy/app/models/user.rb
  spec/dummy/config/environments/development.rb
Labels: chore

#863 WIP Fix/toggle without search query
  CONTRIBUTING.MD
  app/components/avo/views/resource_index_component.html.erb
  app/controllers/avo/actions_controller.rb
Labels: fix

#857 fix: filter defaults not applied if more filters have values
  app/controllers/avo/base_controller.rb
  app/javascript/js/controllers/filter_controller.js
  app/javascript/js/controllers/multiple_select_filter_controller.js
  app/javascript/js/controllers/select_filter_controller.js
  app/views/avo/base/_boolean_filter.html.erb
  app/views/avo/base/_multiple_select_filter.html.erb
  app/views/avo/base/_select_filter.html.erb
  app/views/avo/base/_text_filter.html.erb
  lib/avo/filters/base_filter.rb
  lib/avo/filters/boolean_filter.rb
  lib/avo/filters/multiple_select_filter.rb
  lib/avo/filters/text_filter.rb
  spec/dummy/app/avo/filters/dummy_multiple_select_filter.rb
  spec/dummy/app/avo/filters/featured_filter.rb
  spec/dummy/app/avo/filters/is_admin.rb
  spec/dummy/app/avo/filters/members_filter.rb
  spec/dummy/app/avo/filters/people_2_filter.rb
  spec/dummy/app/avo/filters/post_status_filter.rb
  spec/dummy/app/avo/filters/published_filter.rb
  spec/dummy/app/avo/filters/user_names_filter.rb
  spec/dummy/app/avo/resources/user_resource.rb
  spec/dummy/app/models/user.rb
  spec/system/avo/filters/filter_keep_defaults_spec.rb
Labels: fix

#704 Hide header, sidebar and footer when print in browser
  app/components/avo/sidebar_component.html.erb
  app/views/avo/partials/_footer.html.erb
  app/views/avo/partials/_navbar.html.erb
  lib/avo/configuration.rb
  lib/generators/avo/templates/initializer/avo.tt
Labels: feature

#864 fix: remove mailer
  app/mailers/avo/application_mailer.rb
Labels: fix

#867 fix: menu display, license cache & debug tools
  app/assets/stylesheets/css/components/code.css
  app/components/avo/profile_item_component.html.erb
  app/components/avo/profile_item_component.rb
  app/components/avo/sidebar_component.html.erb
  app/components/avo/sidebar_profile_component.html.erb
  app/controllers/avo/application_controller.rb
  app/controllers/avo/debug_controller.rb
  app/javascript/js/controllers.js
  app/javascript/js/controllers/copy_to_clipboard_controller.js
  app/javascript/js/controllers/fields/code_field_controller.js
  app/views/avo/debug/index.html.erb
  app/views/avo/debug/report.html.erb
  config/routes.rb
  lib/avo/app.rb
  lib/avo/engine.rb
  lib/avo/fields/code_field.rb
  lib/avo/licensing/h_q.rb
  lib/avo/licensing/license.rb
  lib/avo/licensing/license_manager.rb
  lib/avo/version.rb
  lib/tasks/avo_tasks.rake
  spec/features/avo/destroy_record_spec.rb
  spec/features/avo/h_q_spec.rb
  spec/support/download_helpers.rb
Labels: fix

#874 fix: eject command broken for sidebar
  app/views/avo/partials/_sidebar_extra.html.erb
  lib/generators/avo/eject_generator.rb
Labels: fix
