Repository avo-hq/avo, pull requests merged in 2022-06, with the labels that each got.

#931 fix: translation keys for resources and fields
  lib/avo/base_resource.rb
  lib/avo/fields/base_field.rb
Labels: refactor

#935 fix: show proper breadbcrumbs on associated create view
  app/controllers/avo/base_controller.rb
Labels: fix

#936 fix: search broken for uncountable resources
  app/components/avo/views/resource_index_component.html.erb
Labels: fix

#937 refactor: enable range in all cards
  app/components/avo/card_component.html.erb
  lib/avo/base_card.rb
  lib/generators/avo/templates/cards/chartkick_card_sample.tt
  lib/generators/avo/templates/cards/metric_card_sample.tt
  spec/dummy/app/avo/cards/example_area_chart.rb
  spec/dummy/app/avo/cards/example_custom_partial.rb
  spec/dummy/app/views/avo/cards/_custom_card.html.erb
Labels: fix

#938 refactor: logo partial tweaks
  app/views/avo/partials/_logo.html.erb
  app/views/avo/partials/_navbar.html.erb
  public/avo-assets/logomark.png
Labels: refactor

#941 fix: sidebar menu collapsed state
  app/javascript/js/controllers/menu_controller.js
Labels: fix

#940 feature: add the ability to run an action silently
  app/components/avo/alert_component.rb
  app/controllers/avo/actions_controller.rb
  lib/avo/base_action.rb
  spec/dummy/app/avo/actions/toggle_inactive.rb
Labels: feature

#948 chore: ping avohq.io on a PR merge
  .github/publish-release-to-avo-hq-io.js
  .github/workflows/release-notes.yml
  .github/workflows/release.yml
Labels: chore

#949 chore: add Equipe Technique sponsor
  README.md
Labels: chore

#951 fix: trix styles
  README.md
  app/assets/stylesheets/avo.css
  app/assets/stylesheets/css/fields/code.css
  app/assets/stylesheets/css/fields/progress.css
  app/assets/stylesheets/css/fields/status.css
  app/assets/stylesheets/css/fields/trix.css
  app/components/avo/fields/trix_field/edit_component.html.erb
  app/components/avo/fields/trix_field/show_component.html.erb
  app/controllers/avo/base_controller.rb
Labels: fix

#954 fix: right align table headers
  app/views/avo/partials/_table_header.html.erb
Labels: fix

#956 feature: add label to some menu items
  app/components/avo/sidebar/item_switcher_component.html.erb
  lib/avo/menu/base_item.rb
  lib/avo/menu/dashboard.rb
  lib/avo/menu/resource.rb
  spec/dummy/config/initializers/avo.rb
  spec/features/avo/app_spec.rb
Labels: feature

#955 feature: required takes a block
  app/components/avo/common_field_wrapper_component.html.erb
  lib/avo/fields/base_field.rb
  lib/avo/fields/concerns/is_required.rb
  lib/avo/hosts/view_record_host.rb
  spec/dummy/app/avo/resources/fish_resource.rb
  spec/features/avo/required_takes_a_block_spec.rb
Labels: feature

#953 fix: use resource name for url instead of model name
  app/helpers/avo/url_helpers.rb
  lib/avo/base_resource.rb
  lib/avo/dynamic_router.rb
  spec/dummy/app/avo/resources/membership_resource.rb
  spec/dummy/app/avo/resources/team_resource.rb
  spec/dummy/app/controllers/avo/memberships_controller.rb
  spec/dummy/app/controllers/avo/team_memberships_controller.rb
  spec/features/avo/hidden_from_global_search_spec.rb
  spec/features/avo/multiple_names_model_spec.rb
  spec/features/avo/resource_name_urls_spec.rb
  spec/features/avo/resources_hidden_from_sidebar_spec.rb
  spec/system/avo/default_field_spec.rb
Labels: fix

#960 fix: load user translation files not Avo's
  lib/avo/engine.rb
  lib/generators/avo/install_generator.rb
  spec/dummy/config/environments/development.rb
  spec/dummy/config/environments/test.rb
Labels: fix

#963 chore: add generators dir to zetwerk ignore
  lib/avo.rb
Labels: chore

#969 fix: proper action data tag for belongs to field
  app/components/avo/fields/belongs_to_field/edit_component.rb
Labels: fix

#964 chore: alert developer about missing model
  app/views/avo/partials/_custom_tools_alert.html.erb
  lib/avo/app.rb
  lib/avo/concerns/fetches_things.rb
  spec/features/avo/resource_missing_model_spec.rb
Labels: chore

#970 refactor: use same component for new and edit resource page
  app/components/avo/views/resource_edit_component.html.erb
  app/components/avo/views/resource_edit_component.rb
  app/components/avo/views/resource_new_component.html.erb
  app/components/avo/views/resource_new_component.rb
  app/views/avo/base/edit.html.erb
  app/views/avo/base/new.html.erb
  spec/components/avo/views/resource_new_component_spec.rb
  spec/dummy/app/avo/resources/user_resource.rb
Labels: refactor

#991 fix: hard-coded policy action called on ResourceEditComponent
  app/components/avo/views/resource_edit_component.rb
Labels: fix

#996 fix: model class with encryption broken
  lib/avo/base_resource.rb
  lib/avo/concerns/model_class_constantized.rb
  spec/dummy/app/avo/resources/membership_resource.rb
  spec/system/avo/date_spec.rb
Labels: fix
