Repository avo-hq/avo, pull requests merged in 2022-10, with the labels that each got.

#1282 refactor: minor tweaks
  .github/workflows/test.yml
  app/components/avo/field_wrapper_component.html.erb
  app/components/avo/fields/boolean_field/show_component.html.erb
  app/components/avo/fields/boolean_group_field/show_component.html.erb
  app/components/avo/fields/code_field/show_component.html.erb
  app/components/avo/fields/files_field/show_component.html.erb
  spec/dummy/.env.sample
  spec/dummy/app/views/avo/resource_tools/_city_editor.html.erb
  spec/dummy/config/initializers/avo.rb
  spec/system/avo/tabs_spec.rb
Labels: refactor

#1285 fix: multiple resources per model brakes sidebar
  lib/avo/menu/builder.rb
Labels: fix

#1290 Prevent filter buttons from overlapping filter popovers
  app/components/avo/actions_component.html.erb
  app/components/avo/filters_component.html.erb
  app/components/avo/index/ordering/buttons_component.html.erb
  app/components/avo/sidebar_profile_component.html.erb
Labels: fix, hacktoberfest

#1281 fix: dangerous send methods
  .github/workflows/lint.yml
  Gemfile
  Gemfile.lock
  app/components/avo/base_component.rb
  app/components/avo/views/resource_show_component.rb
  app/controllers/avo/actions_controller.rb
  app/controllers/avo/application_controller.rb
  app/controllers/avo/associations_controller.rb
  app/controllers/avo/attachments_controller.rb
  app/controllers/avo/base_controller.rb
  app/controllers/avo/search_controller.rb
  app/views/avo/home/failed_to_load.html copy.erb
  app/views/avo/home/failed_to_load.html.erb
  config/brakeman.ignore
  lib/avo/base_resource.rb
  spec/dummy/app/avo/resources/comment_resource.rb
  spec/dummy/app/avo/resources/project_resource.rb
  spec/dummy/app/views/avo/resource_tools/_city_editor.html.erb
Labels: fix

#1295 fix: disable icon on disabled action
  app/components/avo/actions_component.html.erb
Labels: fix

#1296 chore: minor style tweak
  lib/avo/reloader.rb
  lib/generators/avo/templates/initializer/avo.tt
Labels: chore

#1242 fix: belongs_to link inside tabs
  app/components/avo/fields/belongs_to_field/show_component.html.erb
  lib/avo/concerns/has_fields.rb
  lib/avo/fields/belongs_to_field.rb
  spec/dummy/app/avo/resources/comment_resource.rb
Labels: fix, hacktoberfest

#1299 refactor: minor tab improvements
  app/components/avo/tab_switcher_component.html.erb
  app/javascript/js/controllers/actions_picker_controller.js
  app/javascript/js/controllers/tabs_controller.js
  package.json
  yarn.lock
Labels: refactor

#1307 fix: change belongs to target to turbo frame
  app/components/avo/fields/belongs_to_field/show_component.html.erb
Labels: fix

#1205 feature: resource_sidebar
  app/components/avo/field_wrapper_component.html.erb
  app/components/avo/field_wrapper_component.rb
  app/components/avo/fields/common/heading_component.html.erb
  app/components/avo/fields/common/heading_component.rb
  app/components/avo/fields/edit_component.rb
  app/components/avo/fields/file_field/edit_component.html.erb
  app/components/avo/fields/files_field/edit_component.html.erb
  app/components/avo/fields/heading_field/edit_component.html.erb
  app/components/avo/fields/heading_field/show_component.html.erb
  app/components/avo/fields/show_component.rb
  app/components/avo/panel_component.html.erb
  app/components/avo/panel_component.rb
  app/components/avo/resource_component.rb
  app/components/avo/resource_sidebar_component.html.erb
  app/components/avo/resource_sidebar_component.rb
  app/components/avo/views/resource_edit_component.html.erb
  app/components/avo/views/resource_show_component.html.erb
  app/views/avo/actions/show.html.erb
  lib/avo/concerns/has_fields.rb
  lib/avo/concerns/is_resource_item.rb
  lib/avo/fields/heading_field.rb
  lib/avo/items_holder.rb
  lib/avo/licensing/pro_license.rb
  lib/avo/sidebar.rb
  lib/avo/sidebar_builder.rb
  spec/dummy/app/avo/resources/team_resource.rb
  spec/dummy/app/avo/resources/user_resource.rb
  spec/features/avo/resource_controls_placement_spec.rb
  spec/features/avo/resource_sidebar_spec.rb
Labels: feature, Stale exempt, hacktoberfest

#1308 refactor: support optional policy scope
  Gemfile.lock
  app/controllers/avo/associations_controller.rb
  lib/avo/services/authorization_service.rb
  spec/dummy/app/avo/resources/photo_comment_resource.rb
Labels: refactor

#1312 Normalize and fixes missing locales
  Gemfile
  Gemfile.lock
  config/i18n-tasks.yml
  gemfiles/rails_6.0_ruby_3.0.3.gemfile
  gemfiles/rails_6.0_ruby_3.0.3.gemfile.lock
  gemfiles/rails_6.0_ruby_3.1.0.gemfile
  gemfiles/rails_6.0_ruby_3.1.0.gemfile.lock
  gemfiles/rails_6.1_ruby_3.0.3.gemfile
  gemfiles/rails_6.1_ruby_3.0.3.gemfile.lock
  gemfiles/rails_6.1_ruby_3.1.0.gemfile
  gemfiles/rails_6.1_ruby_3.1.0.gemfile.lock
  gemfiles/rails_7.0_ruby_3.0.3.gemfile
  gemfiles/rails_7.0_ruby_3.0.3.gemfile.lock
  gemfiles/rails_7.0_ruby_3.1.0.gemfile
  gemfiles/rails_7.0_ruby_3.1.0.gemfile.lock
  lib/generators/avo/templates/locales/avo.en.yml
  lib/generators/avo/templates/locales/avo.fr.yml
  lib/generators/avo/templates/locales/avo.nb.yml
  lib/generators/avo/templates/locales/avo.nn.yml
  lib/generators/avo/templates/locales/avo.pt-BR.yml
  lib/generators/avo/templates/locales/avo.ro.yml
  lib/generators/avo/templates/locales/avo.tr.yml
  spec/system/i18n_spec.rb
Labels: refactor, hacktoberfest

#1319 chore: unlock view_component
  Gemfile.lock
  avo.gemspec
  gemfiles/rails_6.0_ruby_3.0.3.gemfile.lock
  gemfiles/rails_6.0_ruby_3.1.0.gemfile.lock
  gemfiles/rails_6.1_ruby_3.0.3.gemfile.lock
  gemfiles/rails_6.1_ruby_3.1.0.gemfile.lock
  gemfiles/rails_7.0_ruby_3.0.3.gemfile.lock
  gemfiles/rails_7.0_ruby_3.1.0.gemfile.lock
Labels: chore

#1324 refactor: white-panel-classes helper global
  .github/workflows/stale.yml
  app/components/avo/panel_component.html.erb
  app/components/avo/panel_component.rb
  app/components/avo/tab_switcher_component.html.erb
  app/components/avo/tab_switcher_component.rb
  app/helpers/avo/application_helper.rb
  spec/features/avo/resource_controls_placement_spec.rb
Labels: refactor

#1332 chore: update nokogiri
  Gemfile.lock
  gemfiles/rails_6.0_ruby_3.0.3.gemfile.lock
  gemfiles/rails_6.0_ruby_3.1.0.gemfile.lock
  gemfiles/rails_6.1_ruby_3.0.3.gemfile.lock
  gemfiles/rails_6.1_ruby_3.1.0.gemfile.lock
  gemfiles/rails_7.0_ruby_3.0.3.gemfile.lock
  gemfiles/rails_7.0_ruby_3.1.0.gemfile.lock
Labels: chore

#1309 fix: attachment destroy button broken
  app/components/avo/button_component.rb
  app/components/avo/fields/common/single_file_viewer_component.html.erb
  app/components/avo/index/resource_controls_component.html.erb
  app/components/avo/sidebar_profile_component.html.erb
  app/components/avo/views/resource_edit_component.html.erb
  app/components/avo/views/resource_show_component.html.erb
  lib/avo/fields/base_field.rb
  spec/dummy/app/controllers/avo/courses_controller.rb
  spec/features/avo/sign_out_dropdown_spec.rb
  spec/system/avo/exposed_methods_base_controller_spec.rb
  spec/system/avo/skip_show_view_spec.rb
Labels: fix

#1340 fix: the panels overflow hides the filters popup
  app/components/avo/panel_component.html.erb
  app/components/avo/views/resource_index_component.html.erb
  spec/features/avo/resource_controls_placement_spec.rb
Labels: fix

#1345 fix: panel too tall
  app/components/avo/panel_component.html.erb
  app/components/avo/views/resource_show_component.html.erb
Labels: fix

#1346 fix: action fileds default option broken
  app/controllers/avo/actions_controller.rb
  app/views/avo/actions/show.html.erb
  lib/avo/base_action.rb
  spec/dummy/app/avo/actions/toggle_inactive.rb
  spec/dummy/app/avo/actions/toggle_published.rb
  spec/system/avo/actions_spec.rb
Labels: fix

#1344 fix: broken timezone time
  CONTRIBUTING.MD
  app/components/avo/fields/date_field/edit_component.html.erb
  app/components/avo/fields/date_time_field/edit_component.html.erb
  app/components/avo/fields/date_time_field/index_component.html.erb
  app/components/avo/fields/date_time_field/show_component.html.erb
  app/components/avo/fields/time_field/edit_component.html.erb
  app/javascript/js/controllers/fields/date_field_controller.js
  lib/avo/base_resource.rb
  lib/avo/concerns/can_replace_fields.rb
  lib/avo/fields/date_time_field.rb
  lib/avo/fields/time_field.rb
  package.json
  spec/dummy/app/avo/resources/course_resource.rb
  spec/dummy/app/avo/resources/project_resource.rb
  spec/support/helpers.rb
  spec/support/timezone.rb
  spec/system/avo/date_time_field/date_time_eastern_disabled.rb
  spec/system/avo/date_time_field/date_time_western_disabled.rb
  spec/system/avo/date_time_fields/date_spec.rb
  spec/system/avo/date_time_fields/date_time_eastern_spec.rb
  spec/system/avo/date_time_fields/date_time_spec.rb
  spec/system/avo/date_time_fields/date_time_utc_spec.rb
  spec/system/avo/date_time_fields/date_time_western_spec.rb
  spec/system/avo/date_time_fields/time_spec.rb
  spec/system/avo/time_field_spec.rb
Labels: fix

#1348 refactor: restore panel shadow and overflow
  app/components/avo/index/resource_table_component.html.erb
  app/components/avo/panel_component.html.erb
  app/components/avo/views/resource_index_component.html.erb
  app/components/avo/views/resource_show_component.html.erb
Labels: refactor

#1300 Extract pundit to client
  app/controllers/avo/application_controller.rb
  app/controllers/avo/associations_controller.rb
  lib/avo.rb
  lib/avo/configuration.rb
  lib/avo/services/authorization_clients/pundit_client.rb
  lib/avo/services/authorization_service.rb
  lib/generators/avo/templates/initializer/avo.tt
  spec/dummy/app/avo/resources/photo_comment_resource.rb
  spec/dummy/app/policies/post_policy.rb
  spec/dummy/config/initializers/avo.rb
  spec/requests/avo/authorization/custom_policies_spec.rb
  spec/requests/avo/authorization/raise_error_on_missing_policy_spec.rb
Labels: enhancement, hacktoberfest

#1280 refactor: require only the needed rails dependencies
  Gemfile
  Gemfile.lock
  app/controllers/avo/cards_controller.rb
  app/views/avo/cards/chartkick_missing.html.erb
  avo.gemspec
  gemfiles/rails_6.0_ruby_3.0.3.gemfile
  gemfiles/rails_6.0_ruby_3.0.3.gemfile.lock
  gemfiles/rails_6.0_ruby_3.1.0.gemfile
  gemfiles/rails_6.0_ruby_3.1.0.gemfile.lock
  gemfiles/rails_6.1_ruby_3.0.3.gemfile
  gemfiles/rails_6.1_ruby_3.0.3.gemfile.lock
  gemfiles/rails_6.1_ruby_3.1.0.gemfile
  gemfiles/rails_6.1_ruby_3.1.0.gemfile.lock
  gemfiles/rails_7.0_ruby_3.0.3.gemfile
  gemfiles/rails_7.0_ruby_3.0.3.gemfile.lock
  gemfiles/rails_7.0_ruby_3.1.0.gemfile
  gemfiles/rails_7.0_ruby_3.1.0.gemfile.lock
  lib/avo/engine.rb
  lib/avo/fields/country_field.rb
  spec/dummy/app/channels/application_cable/channel.rb
  spec/dummy/app/channels/application_cable/connection.rb
  spec/dummy/config/application.rb
  spec/dummy/config/environments/test.rb
  spec/dummy/config/initializers/assets.rb
Labels: refactor, hacktoberfest

#1349 feature: stacked fields by default
  app/components/avo/field_wrapper_component.rb
  app/components/avo/fields/edit_component.rb
  app/components/avo/fields/show_component.rb
  app/components/avo/item_switcher_component.html.erb
  lib/avo/configuration.rb
  lib/avo/fields/base_field.rb
  lib/generators/avo/templates/initializer/avo.tt
  spec/dummy/app/avo/resources/user_resource.rb
  spec/dummy/config/initializers/avo.rb
  spec/features/avo/stacked_wrapper_layout_spec.rb
  spec/support/helpers.rb
Labels: feature

#1350 feature: label and content available in the html option
  app/components/avo/field_wrapper_component.html.erb
  app/components/avo/field_wrapper_component.rb
  app/components/avo/views/resource_edit_component.html.erb
  app/components/avo/views/resource_index_component.html.erb
  app/components/avo/views/resource_show_component.html.erb
  db/factories.rb
  lib/avo/html/builder.rb
  spec/dummy/app/avo/resources/product_resource.rb
  spec/features/avo/html_attribute_spec.rb
Labels: feature

#1369 fix: include pundit if available
  app/controllers/avo/application_controller.rb
Labels: fix

#1359 Don't swallow errors with labels and descriptions
  lib/avo/base_resource.rb
Labels: fix

#1373 fix: move cards controller to avoid conflicts
  app/controllers/avo/cards_controller.rb
  app/controllers/avo/dashboards/cards_controller.rb
  app/views/avo/dashboards/cards/_chartkick_card.html.erb
  app/views/avo/dashboards/cards/_metric_card.html.erb
  app/views/avo/dashboards/cards/chartkick_missing.html.erb
  app/views/avo/dashboards/cards/show.html.erb
  config/routes.rb
Labels: fix

#1375 fix: placeholder to public dir
  lib/avo/configuration/branding.rb
  public/avo-assets/placeholder.svg
  spec/dummy/config/initializers/avo.rb
Labels: fix

#1376 fix: readonly vulnerability
  lib/avo/fields/base_field.rb
Labels: fix

#1377 fix: sidebar field visibility block
  app/components/avo/resource_component.rb
  lib/avo/sidebar.rb
Labels: fix

#1378 fix: visibility issues for tabs panels and sidebars
  app/components/avo/item_switcher_component.html.erb
  app/components/avo/resource_sidebar_component.rb
  app/components/avo/tab_group_component.rb
  lib/avo/concerns/has_fields.rb
  lib/avo/concerns/visible_items.rb
  lib/avo/panel.rb
  lib/avo/sidebar.rb
  lib/avo/tab.rb
  spec/features/avo/tabs_panels_and_sidebar_visibility_spec.rb
Labels: fix

#1333 refactor: zeiwerk eager load resource dir
  Gemfile
  Gemfile.lock
  avo.gemspec
  config/routes.rb
  gemfiles/rails_6.0_ruby_3.0.3.gemfile
  gemfiles/rails_6.0_ruby_3.0.3.gemfile.lock
  gemfiles/rails_6.0_ruby_3.1.0.gemfile
  gemfiles/rails_6.0_ruby_3.1.0.gemfile.lock
  gemfiles/rails_6.1_ruby_3.0.3.gemfile
  gemfiles/rails_6.1_ruby_3.0.3.gemfile.lock
  gemfiles/rails_6.1_ruby_3.1.0.gemfile
  gemfiles/rails_6.1_ruby_3.1.0.gemfile.lock
  gemfiles/rails_7.0_ruby_3.0.3.gemfile
  gemfiles/rails_7.0_ruby_3.0.3.gemfile.lock
  gemfiles/rails_7.0_ruby_3.1.0.gemfile
  gemfiles/rails_7.0_ruby_3.1.0.gemfile.lock
  lib/avo.rb
  lib/avo/app.rb
  lib/avo/concerns/visible_items.rb
  lib/avo/dynamic_router.rb
  lib/avo/engine.rb
  spec/dummy/config/application.rb
Labels: refactor
