Repository avo-hq/avo, pull requests merged in 2022-02, with the labels that each got.

#615 chore: add repobeats analytics
  README.md
Labels: chore

#616 feature: HABTM create record
  app/components/avo/resource_component.rb
  app/components/avo/views/resource_index_component.rb
  app/components/avo/views/resource_new_component.html.erb
  app/controllers/avo/base_controller.rb
  lib/avo/base_resource.rb
  spec/dummy/app/avo/resources/person_resource.rb
  spec/dummy/app/models/person.rb
  spec/dummy/app/models/user.rb
  spec/dummy/db/migrate/20220201135401_add_spouse_id_person.rb
  spec/dummy/db/schema.rb
  spec/features/avo/create_through_record_spec.rb
Labels: feature

#619 feature: text filter generator
  lib/generators/avo/filter_generator.rb
  lib/generators/avo/templates/filters/text_filter.tt
  spec/dummy/app/avo/filters/user_names_filter.rb
  spec/dummy/app/avo/resources/user_resource.rb
Labels: feature

#621 chore: fix tailwind 3 warnings
  app/assets/stylesheets/css/search.css
  app/components/avo/edit/field_wrapper_component.html.erb
  app/components/avo/fields/common/files_list_viewer_component.html.erb
  app/components/avo/fields/common/heading_component.html.erb
  app/components/avo/index/field_wrapper_component.html.erb
  app/components/avo/index/table_row_component.html.erb
  app/components/avo/show/field_wrapper_component.html.erb
  app/helpers/avo/application_helper.rb
  app/views/avo/actions/show.html.erb
  app/views/avo/base/_actions.html.erb
  app/views/avo/base/_filters.html.erb
  app/views/avo/home/_actions.html.erb
  app/views/avo/home/_filters.html.erb
  app/views/avo/home/_resources.html.erb
  app/views/avo/partials/_paginator.html.erb
  app/views/avo/partials/_table_header.html.erb
  app/views/layouts/avo/application.html.erb
  safelist.txt
  tailwind.config.js
Labels: chore

#622 chore: different os search icon
  app/assets/stylesheets/avo.css
  app/javascript/avo.js
  app/views/avo/partials/_global_search.html.erb
  app/views/layouts/avo/application.html.erb
Labels: chore

#624 fix: button spinner attribute breaks helpers
  app/helpers/avo/application_helper.rb
  app/views/avo/partials/_footer.html.erb
  docker/Dockerfile
Labels: fix

#626 chore: add dynamic router module
  .github/ISSUE_TEMPLATE/blank_issue.md
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  config/routes.rb
  lib/avo/app.rb
  lib/avo/dynamic_router.rb
Labels: chore

#636 feature: custom labels for associations
  app/components/avo/panel_component.html.erb
  app/components/avo/resource_component.rb
  app/components/avo/views/resource_index_component.rb
  app/components/avo/views/resource_show_component.html.erb
  app/components/avo/views/resource_show_component.rb
  lib/avo/fields/base_field.rb
  spec/dummy/app/avo/resources/user_resource.rb
  spec/dummy/config/locales/avo.en.yml
  spec/features/avo/i18n_spec.rb
Labels: feature

#637 feature: add scopes to associations
  app/controllers/avo/relations_controller.rb
  lib/avo/base_resource.rb
  lib/avo/fields/has_base_field.rb
  spec/dummy/app/avo/resources/user_resource.rb
  spec/dummy/app/models/comment.rb
  spec/features/avo/has_many_field_spec.rb
Labels: feature

#639 feature: description for resource
  .github/PULL_REQUEST_TEMPLATE.md
  app/components/avo/panel_component.html.erb
  app/components/avo/panel_component.rb
  app/components/avo/views/resource_edit_component.html.erb
  app/components/avo/views/resource_index_component.html.erb
  app/components/avo/views/resource_new_component.html.erb
  app/components/avo/views/resource_show_component.html.erb
  lib/avo/base_resource.rb
  spec/dummy/app/avo/resources/person_resource.rb
  spec/dummy/app/avo/resources/user_resource.rb
  spec/features/avo/resource_description_spec.rb
Labels: feature

#642 fix: broken form scope for namespaced models
  .github/PULL_REQUEST_TEMPLATE.md
  app/components/avo/index/resource_controls_component.rb
  app/components/avo/resource_component.rb
  app/components/avo/views/resource_edit_component.html.erb
  app/components/avo/views/resource_index_component.rb
  app/components/avo/views/resource_new_component.html.erb
  app/components/avo/views/resource_show_component.rb
  app/controllers/avo/base_controller.rb
  db/factories.rb
  lib/avo/base_resource.rb
  lib/avo/services/authorization_service.rb
  spec/dummy/app/avo/resources/course_link_resource.rb
  spec/dummy/app/avo/resources/course_resource.rb
  spec/dummy/app/controllers/avo/course_links_controller.rb
  spec/dummy/app/controllers/avo/courses_controller.rb
  spec/dummy/app/models/course.rb
  spec/dummy/app/models/course/link.rb
  spec/dummy/db/migrate/20220207085343_create_courses.rb
  spec/dummy/db/migrate/20220207085352_create_course_links.rb
  spec/dummy/db/schema.rb
  spec/features/avo/create_through_record_spec.rb
  spec/features/avo/has_many_field_spec.rb
Labels: fix

#641 feature: advanced autorizations for associations
  Gemfile
  Gemfile.lock
  app/components/avo/index/resource_controls_component.html.erb
  app/components/avo/index/resource_controls_component.rb
  app/components/avo/resource_component.rb
  app/components/avo/views/resource_index_component.html.erb
  app/components/avo/views/resource_index_component.rb
  lib/avo/services/authorization_service.rb
  spec/dummy/app/avo/resources/team_resource.rb
  spec/dummy/app/models/team.rb
  spec/dummy/app/policies/team_policy.rb
  spec/dummy/app/policies/user_policy.rb
  spec/dummy/db/seeds.rb
  spec/features/avo/multiple_names_model_spec.rb
  spec/requests/avo/authorization/associations_spec.rb
  spec/system/avo/filters_spec.rb
Labels: feature

#643 fix: hide the resource description on the association page
  app/components/avo/views/resource_index_component.html.erb
  app/components/avo/views/resource_index_component.rb
  gemfiles/rails_6.0_ruby_3.0.3.gemfile
  gemfiles/rails_6.0_ruby_3.0.3.gemfile.lock
  gemfiles/rails_6.0_ruby_3.1.0.gemfile
  gemfiles/rails_6.0_ruby_3.1.0.gemfile.lock
  gemfiles/rails_6.1_ruby_3.0.3.gemfile
  gemfiles/rails_6.1_ruby_3.0.3.gemfile.lock
  gemfiles/rails_6.1_ruby_3.1.0.gemfile
  gemfiles/rails_6.1_ruby_3.1.0.gemfile.lock
  gemfiles/rails_7.0_ruby_3.0.3.gemfile
  gemfiles/rails_7.0_ruby_3.0.3.gemfile.lock
  gemfiles/rails_7.0_ruby_3.1.0.gemfile
  gemfiles/rails_7.0_ruby_3.1.0.gemfile.lock
  spec/features/avo/resource_description_spec.rb
Labels: fix

#648 feature: hydrate resource with model in authorization service
  app/components/avo/resource_component.rb
Labels: feature

#657 chore: misc support files tweks
  .github/PULL_REQUEST_TEMPLATE.md
  docker/Dockerfile
Labels: chore

#665 fix: related belongs to does not allow for proper resource creation
  app/components/avo/fields/belongs_to_field/edit_component.html.erb
  spec/features/avo/belongs_to_spec.rb
Labels: fix

#667 chore: minor tweaks
  db/factories.rb
  spec/dummy/app/avo/resources/course_link_resource.rb
Labels: chore

#669 fix: date object alters date based on timezone
  .github/PULL_REQUEST_TEMPLATE.md
  app/javascript/js/controllers/fields/date_field_controller.js
  spec/system/avo/date_spec.rb
Labels: fix

#674 fix: some fields are hidden on the has_many view
  app/javascript/js/controllers/item_selector_controller.js
  lib/avo/base_resource.rb
  spec/system/avo/has_many_spec.rb
Labels: fix

#678 fix: notifications delayed in turbo frames
  README.md
  app/views/avo/partials/_turbo_frame_wrap.html.erb
  db/factories.rb
  spec/dummy/app/avo/resources/comment_resource.rb
  spec/dummy/app/models/comment.rb
  spec/dummy/db/seeds.rb
  spec/system/avo/has_many_spec.rb
Labels: fix

#683 refactor: move the root_path link in the logo partial
  app/views/avo/partials/_logo.html.erb
  app/views/avo/sidebar/_sidebar.html.erb
  spec/features/avo/app_spec.rb
Labels: refactor

#685 feature: Allow Avo::NavigationLinkComponent to accept an optional target param
  app/components/avo/navigation_link_component.html.erb
  app/components/avo/navigation_link_component.rb
Labels: feature

#655 fix: fill model beofre authorizing an action
  app/controllers/avo/application_controller.rb
  app/controllers/avo/base_controller.rb
Labels: fix

#686 fix: Support older version of Pundit
  app/controllers/avo/application_controller.rb
Labels: fix

#691 fix: duplicated alerts
  app/javascript/avo.js
  app/views/avo/partials/_turbo_frame_wrap.html.erb
  spec/rails_helper.rb
  spec/support/helpers.rb
  spec/system/avo/app_spec.rb
Labels: fix

#690 fix: belongs to polymorphic fails to save record
  Gemfile.lock
  app/components/avo/fields/belongs_to_field/autocomplete_component.rb
  app/components/avo/fields/belongs_to_field/edit_component.html.erb
  app/components/avo/fields/select_field/edit_component.html.erb
  app/controllers/avo/base_controller.rb
  app/controllers/avo/relations_controller.rb
  app/javascript/js/controllers/fields/belongs_to_field_controller.js
  app/views/avo/relations/new.html.erb
  db/factories.rb
  lib/avo/fields/base_field.rb
  lib/avo/fields/belongs_to_field.rb
  spec/dummy/app/avo/resources/course_link_resource.rb
  spec/dummy/app/avo/resources/project_resource.rb
  spec/dummy/app/avo/resources/review_resource.rb
  spec/dummy/app/models/course.rb
  spec/dummy/app/models/person.rb
  spec/dummy/app/models/review.rb
  spec/features/avo/belongs_to_polymorphic_spec.rb
  spec/features/avo/belongs_to_searchable_spec.rb
  spec/features/avo/select_field/enum_array_display_value_false_spec.rb
  spec/support/helpers.rb
Labels: fix

#694 fix: some association fields are invisible in has_many index views
  .github/ISSUE_TEMPLATE/bug_report.md
  db/factories.rb
  lib/avo/base_resource.rb
  lib/avo/fields/belongs_to_field.rb
  spec/dummy/app/avo/resources/user_resource.rb
  spec/features/avo/belongs_to_spec.rb
  spec/system/avo/belongs_to_spec.rb
Labels: fix

#696 chore: update stimulus js
  app/javascript/js/application.js
  app/javascript/js/controllers/action_controller.js
  app/javascript/js/controllers/actions_picker_controller.js
  app/javascript/js/controllers/alerts_controller.js
  app/javascript/js/controllers/attachments_controller.js
  app/javascript/js/controllers/fields/belongs_to_field_controller.js
  app/javascript/js/controllers/fields/code_field_controller.js
  app/javascript/js/controllers/fields/date_field_controller.js
  app/javascript/js/controllers/fields/key_value_controller.js
  app/javascript/js/controllers/fields/simple_mde_controller.js
  app/javascript/js/controllers/fields/trix_field_controller.js
  app/javascript/js/controllers/filter_controller.js
  app/javascript/js/controllers/hidden_input_controller.js
  app/javascript/js/controllers/item_select_all_controller.js
  app/javascript/js/controllers/item_selector_controller.js
  app/javascript/js/controllers/loading_button_controller.js
  app/javascript/js/controllers/modal_controller.js
  app/javascript/js/controllers/per_page_controller.js
  app/javascript/js/controllers/search_controller.js
  app/javascript/js/controllers/tippy_controller.js
  app/javascript/js/controllers/toggle_panel_controller.js
  package.json
  yarn.lock
Labels: chore

#695 fix: wrong key deleted in key-value
  app/javascript/js/controllers/fields/key_value_controller.js
  app/javascript/js/controllers/filter_controller.js
  app/javascript/js/controllers/item_select_all_controller.js
  spec/system/avo/key_value_field/key_value_field_spec.rb
Labels: fix

#697 fix: sidebar navigation link default target forces reload
  app/components/avo/navigation_link_component.rb
  app/controllers/avo/base_controller.rb
  spec/dummy/app/avo/resources/person_resource.rb
  spec/dummy/app/models/person.rb
Labels: fix

#699 chode: fix flaky tests (wait for search)
  app/javascript/js/controllers/search_controller.js
  spec/features/avo/belongs_to_polymorphic_spec.rb
  spec/support/wait_for_loaded.rb
Labels: chore

#698 chore: initial locale support
  Gemfile.lock
  app/controllers/avo/application_controller.rb
  spec/support/wait_for_loaded.rb
Labels: chore

#701 fix: turbo breaks action downloads
  app/javascript/js/controllers/modal_controller.js
  app/views/avo/actions/show.html.erb
  lib/avo/base_action.rb
  spec/dummy/app/avo/actions/download_file.rb
  spec/dummy/app/avo/resources/user_resource.rb
  spec/dummy/dummy-file.txt
  spec/rails_helper.rb
  spec/support/download_helpers.rb
  spec/system/avo/actions_spec.rb
Labels: fix

#702 chore: add a few more exceptions to hq response
  lib/avo/licensing/h_q.rb
Labels: chore

#706 refactor: some very used partials converted to view_components
  app/components/avo/alert_component.html.erb
  app/components/avo/alert_component.rb
  app/components/avo/alerts_component.html.erb
  app/components/avo/alerts_component.rb
  app/components/avo/turbo_frame_wrapper_component.html.erb
  app/components/avo/turbo_frame_wrapper_component.rb
  app/helpers/avo/application_helper.rb
  app/views/avo/partials/_alerts.html.erb
  app/views/layouts/avo/application.html.erb
Labels: refactor, performance
