Repository avo-hq/avo, pull requests merged in 2022-07, with the labels that each got.

#1010 fix: key value field new->create view
  app/components/avo/fields/common/key_value_component.html.erb
Labels: fix

#1020 fix: key value labels missing
  lib/avo/fields/key_value_field.rb
Labels: fix

#1031 fix: root_path breaks avo on community
  app/controllers/avo/application_controller.rb
Labels: fix

#1032 fix: broken release script (update nokogiri)
  Gemfile.lock
Labels: fix

#1027 chore: don't crash Avo if SSL error raised
  lib/avo/licensing/h_q.rb
  spec/features/avo/h_q_spec.rb
Labels: chore

#1036 fix: standardrb v1.x
  .github/workflows/reviewdog.yml
Labels: chore

#1033 fix: card generators broken; added tests; show avo version
  lib/avo/base_resource.rb
  lib/avo/configuration.rb
  lib/generators/avo/action_generator.rb
  lib/generators/avo/base_generator.rb
  lib/generators/avo/card/chartkick_generator.rb
  lib/generators/avo/card/metric_generator.rb
  lib/generators/avo/card/partial_generator.rb
  lib/generators/avo/chartkick_card_generator.rb
  lib/generators/avo/controller_generator.rb
  lib/generators/avo/dashboard_generator.rb
  lib/generators/avo/eject_generator.rb
  lib/generators/avo/field_generator.rb
  lib/generators/avo/filter_generator.rb
  lib/generators/avo/install_generator.rb
  lib/generators/avo/locales_generator.rb
  lib/generators/avo/metric_card_generator.rb
  lib/generators/avo/named_base_generator.rb
  lib/generators/avo/partial_card_generator.rb
  lib/generators/avo/resource_generator.rb
  lib/generators/avo/resource_tool_generator.rb
  lib/generators/avo/tool_generator.rb
  lib/generators/avo/version_generator.rb
  spec/features/avo/generators/action_generator_spec.rb
  spec/features/avo/generators/cards_generator_spec.rb
  spec/features/avo/generators/controller_generator_spec.rb
  spec/features/avo/generators/dashboard_generator_spec.rb
  spec/features/avo/generators/field_generator_spec.rb
  spec/features/avo/generators/filter_generator_spec.rb
  spec/features/avo/generators/locales_generator_spec.rb
  spec/features/avo/generators/resource_generator_spec.rb
  spec/features/avo/generators/resource_tool_generator_spec.rb
  spec/features/avo/resource_missing_model_spec.rb
  spec/support/helpers.rb
Labels: chore, fix

#1038 chore: stale bot improvements; release messages
  .github/workflows/merge-message.yml
  .github/workflows/stale.yml
  RELEASE.MD
Labels: chore

#1044 feature: add accept option for file/files field
  app/components/avo/fields/file_field/edit_component.html.erb
  app/components/avo/fields/files_field/edit_component.html.erb
  lib/avo/fields/file_field.rb
  lib/avo/fields/files_field.rb
  spec/dummy/app/avo/resources/post_resource.rb
Labels: enhancement

#1021 feature: add include_blank to select and country fields
  .github/workflows/merge-message.yml
  app/components/avo/fields/country_field/edit_component.html.erb
  app/components/avo/fields/select_field/edit_component.html.erb
  lib/avo/fields/base_field.rb
  lib/avo/fields/country_field.rb
  lib/avo/fields/field_extensions/has_include_blank.rb
  lib/avo/fields/select_field.rb
  spec/dummy/app/avo/resources/person_resource.rb
  spec/dummy/app/avo/resources/project_resource.rb
  spec/features/avo/country_field_spec.rb
  spec/features/avo/select_field/enum_array_display_value_false_spec.rb
  spec/features/avo/select_field/enum_hash_display_value_true_spec.rb
  spec/features/avo/select_field_spec.rb
  spec/system/avo/boolean_filter_spec.rb
Labels: feature

#995 fix: date time field broken on edit for different timezones
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/PULL_REQUEST_TEMPLATE.md
  .github/pr-labeler.yml
  Gemfile.lock
  app/components/avo/fields/date_field/edit_component.html.erb
  app/components/avo/fields/date_field/index_component.html.erb
  app/components/avo/fields/date_field/show_component.html.erb
  app/components/avo/fields/date_time_field/edit_component.html.erb
  app/components/avo/fields/date_time_field/index_component.html.erb
  app/components/avo/fields/date_time_field/show_component.html.erb
  app/javascript/js/controllers/fields/date_field_controller.js
  db/factories.rb
  gemfiles/rails_6.0_ruby_3.0.3.gemfile.lock
  gemfiles/rails_6.0_ruby_3.1.0.gemfile.lock
  gemfiles/rails_6.1_ruby_3.0.3.gemfile.lock
  gemfiles/rails_6.1_ruby_3.1.0.gemfile.lock
  gemfiles/rails_7.0_ruby_3.0.3.gemfile.lock
  gemfiles/rails_7.0_ruby_3.1.0.gemfile.lock
  lib/avo/app.rb
  lib/avo/concerns/handles_field_args.rb
  lib/avo/fields/date_field.rb
  lib/avo/fields/date_time_field.rb
  spec/dummy/app/avo/resources/comment_resource.rb
  spec/dummy/app/avo/resources/user_resource.rb
  spec/dummy/app/models/comment.rb
  spec/dummy/db/migrate/20210421064037_add_color_to_teams.rb
  spec/dummy/db/migrate/20210423075924_add_progress_to_projects.rb
  spec/dummy/db/migrate/20210525143134_add_slug_to_users.rb
  spec/dummy/db/migrate/20220705172707_add_posted_at_to_comments.rb
  spec/dummy/db/schema.rb
  spec/rails_helper.rb
  spec/support/timezone.rb
  spec/system/avo/date_spec.rb
  spec/system/avo/date_time_field/date_time_eastern_disabled.rb
  spec/system/avo/date_time_field/date_time_utc_spec.rb
  spec/system/avo/date_time_field/date_time_western_disabled.rb
  spec/system/avo/tabs_spec.rb
Labels: fix

#1048 Revert "chore: rename via_relation_class->via_resource_class"
  app/components/avo/fields/belongs_to_field/autocomplete_component.html.erb
  app/components/avo/referrer_params_component.html.erb
  app/components/avo/views/resource_edit_component.rb
  app/components/avo/views/resource_index_component.rb
  app/controllers/avo/base_controller.rb
  lib/avo/base_resource.rb
  spec/features/avo/belongs_to_polymorphic_spec.rb
  spec/features/avo/belongs_to_spec.rb
  spec/features/avo/create_through_record_spec.rb
  spec/features/avo/has_many_field_spec.rb
  spec/features/avo/search_spec.rb
  spec/system/avo/belongs_to_spec.rb
  spec/system/avo/tabs_spec.rb
Labels: chore

#1053 fix: order routes clash
  app/components/avo/index/ordering/button_component.rb
  app/controllers/avo/reorder_controller.rb
  app/helpers/avo/url_helpers.rb
  config/routes.rb
Labels: fix

#1055 fix: search with namespaced models broken
  app/components/avo/views/resource_index_component.html.erb
  spec/features/avo/search_spec.rb
Labels: fix

#1057 fix: search broken with relative_url_root
  app/helpers/avo/application_helper.rb
  app/views/avo/partials/_javascript.html.erb
  spec/dummy/config.ru
  spec/dummy/config/application.rb
Labels: fix

#1058 refactor: better force locale
  app/controllers/avo/application_controller.rb
  spec/dummy/app/views/home/index.html.erb
Labels: refactor

#1060 fix: locale configuration broken
  app/controllers/avo/application_controller.rb
  lib/avo/app.rb
  lib/avo/configuration.rb
  spec/dummy/config/application.rb
  spec/dummy/config/initializers/avo.rb
Labels: fix

#1061 fix: inverse of crashing association screen
  lib/avo/concerns/has_fields.rb
Labels: fix

#1069 feature: add path helpers to actions
  lib/avo/base_action.rb
  lib/avo/base_resource.rb
  lib/avo/has_context.rb
Labels: feature

#1080 fix: date field wrongly subtracts time zone offsets
  app/components/avo/fields/date_time_field/index_component.html.erb
  app/components/avo/fields/date_time_field/show_component.html.erb
  app/javascript/js/controllers/fields/date_field_controller.js
  spec/dummy/app/avo/resources/project_resource.rb
Labels: fix

#1081 fix: external path detector
  .github/ISSUE_TEMPLATE/bug_report.md
  app/components/avo/sidebar/link_component.rb
  app/controllers/avo/base_controller.rb
  spec/dummy/app/controllers/avo/tools_controller.rb
  spec/dummy/app/views/avo/sidebar/items/_custom_tool.html.erb
  spec/dummy/app/views/avo/sidebar/items/_dashboard.html.erb
  spec/dummy/app/views/avo/tools/custom_tool.html.erb
  spec/dummy/app/views/avo/tools/dashboard.html.erb
  spec/dummy/config/initializers/avo.rb
  spec/dummy/config/routes.rb
  spec/features/avo/app_spec.rb
  spec/features/avo/breadcrumbs_spec.rb
  spec/features/avo/custom_tools_spec.rb
  spec/features/avo/h_q_spec.rb
  spec/features/avo/license_tinkering_in_application_controller_spec.rb
  spec/system/avo/avo_collapsable_menus_spec.rb
Labels: fix

#1071 fix: form footer buttons in the wrong place
  .github/PULL_REQUEST_TEMPLATE.md
  Gemfile.lock
  app/components/avo/item_switcher_component.rb
  app/components/avo/panel_component.html.erb
  app/components/avo/panel_component.rb
  app/components/avo/resource_component.rb
  app/components/avo/tab_group_component.html.erb
  app/components/avo/views/resource_edit_component.html.erb
  app/components/avo/views/resource_edit_component.rb
  app/components/avo/views/resource_show_component.html.erb
  app/components/avo/views/resource_show_component.rb
  app/views/avo/base/edit.html.erb
  spec/system/avo/tabs_spec.rb
Labels: fix

#1084 chore: revert view_component to 2.60
  Gemfile
  Gemfile.lock
  avo.gemspec
  gemfiles/rails_6.0_ruby_3.0.3.gemfile
  gemfiles/rails_6.0_ruby_3.0.3.gemfile.lock
  gemfiles/rails_6.0_ruby_3.1.0.gemfile
  gemfiles/rails_6.0_ruby_3.1.0.gemfile.lock
  gemfiles/rails_6.1_ruby_3.0.3.gemfile
  gemfiles/rails_6.1_ruby_3.0.3.gemfile.lock
  gemfiles/rails_6.1_ruby_3.1.0.gemfile
  gemfiles/rails_6.1_ruby_3.1.0.gemfile.lock
  gemfiles/rails_7.0_ruby_3.0.3.gemfile
  gemfiles/rails_7.0_ruby_3.0.3.gemfile.lock
  gemfiles/rails_7.0_ruby_3.1.0.gemfile
  gemfiles/rails_7.0_ruby_3.1.0.gemfile.lock
Labels: chore

#1087 feature: hide sidebar on desktop
  app/assets/stylesheets/avo.css
  app/assets/stylesheets/css/sidebar.css
  app/components/avo/sidebar_component.html.erb
  app/controllers/avo/application_controller.rb
  app/javascript/js/controllers.js
  app/javascript/js/controllers/mobile_controller.js
  app/javascript/js/controllers/sidebar_controller.js
  app/views/avo/partials/_javascript.html.erb
  app/views/avo/partials/_navbar.html.erb
  app/views/layouts/avo/application.html.erb
  lib/avo.rb
  package.json
  spec/support/helpers.rb
  spec/system/avo/avo_sidebars_spec.rb
  yarn.lock
Labels: feature

#1089 fix: overriden data attributes should take precendence
  lib/avo/concerns/has_html_attributes.rb
  spec/dummy/app/avo/resources/review_resource.rb
  spec/system/avo/nullable_field_spec.rb
Labels: fix

#1064 fix: authorization actions broken for some associations
  app/components/avo/fields/has_one_field/show_component.html.erb
  app/components/avo/fields/has_one_field/show_component.rb
  app/components/avo/index/resource_controls_component.rb
  app/components/avo/index/resource_table_component.html.erb
  app/components/avo/index/resource_table_component.rb
  app/components/avo/index/table_row_component.html.erb
  app/components/avo/index/table_row_component.rb
  app/components/avo/resource_component.rb
  app/components/avo/tab_switcher_component.rb
  app/components/avo/views/resource_edit_component.rb
  app/components/avo/views/resource_index_component.html.erb
  app/components/avo/views/resource_index_component.rb
  app/components/avo/views/resource_show_component.html.erb
  app/components/avo/views/resource_show_component.rb
  app/controllers/avo/application_controller.rb
  app/controllers/avo/associations_controller.rb
  app/controllers/avo/base_controller.rb
  app/views/avo/base/index.html.erb
  app/views/avo/base/show.html.erb
  gemfiles/rails_6.1_ruby_3.0.3.gemfile.lock
  lib/avo/concerns/has_fields.rb
  lib/avo/fields/has_base_field.rb
  lib/avo/services/authorization_service.rb
  spec/dummy/app/policies/post_policy.rb
  spec/dummy/app/policies/team_policy.rb
  spec/requests/avo/authorization/associations_spec.rb
  spec/support/helpers.rb
  spec/system/avo/belongs_to_polymorphic_spec.rb
  spec/system/avo/boolean_group_field_spec.rb
  spec/system/avo/has_one_field_name_spec.rb
Labels: fix

#1090 feature: protocol option for text field
  app/components/avo/fields/text_field/index_component.html.erb
  app/components/avo/fields/text_field/show_component.html.erb
  lib/avo/fields/text_field.rb
  spec/dummy/app/avo/resources/user_resource.rb
Labels: feature

#1097 refactor: change failed to load illustration
  app/assets/svgs/failed_to_load.svg
  app/views/avo/home/failed_to_load.html copy.erb
  app/views/avo/home/failed_to_load.html.erb
Labels: refactor

#1098 chore: add `avo_debug` param
  app/components/avo/common_field_wrapper_component.html.erb
  app/components/avo/index/field_wrapper_component.html.erb
  docker/Dockerfile
Labels: chore

#1091 feature: resource controls on the left
  app/components/avo/index/resource_controls_component.html.erb
  app/components/avo/index/table_row_component.html.erb
  app/views/avo/partials/_table_header.html.erb
  lib/avo/configuration.rb
  lib/avo/configuration/resource_configuration.rb
  spec/dummy/.env.sample
  spec/dummy/config/initializers/avo.rb
  spec/features/avo/resource_controls_placement_spec.rb
Labels: feature

#1102 fix: allow tools to come before fields
  lib/avo/concerns/has_fields.rb
Labels: fix

#1105 fix: multiple tabs flow out of the screen
  CONTRIBUTING.MD
  app/assets/stylesheets/avo.css
  app/assets/stylesheets/css/scrollbar.css
  app/components/avo/sidebar_component.html.erb
  app/components/avo/tab_switcher_component.html.erb
  app/components/avo/views/resource_index_component.html.erb
  app/javascript/avo.js
  spec/dummy/app/avo/resources/fish_resource.rb
Labels: fix

#1111 fix: has one field show only main panel
  app/components/avo/views/resource_show_component.html.erb
Labels: fix
