Repository avo-hq/avo, pull requests merged in 2023-12, with the labels that each got.

#2049 fix: create new record from belongs_to associations
  app/components/avo/fields/belongs_to_field/edit_component.rb
  spec/dummy/app/models/course/link.rb
  spec/features/avo/has_many_field_spec.rb
  spec/features/avo/search_spec.rb
  spec/system/avo/create_via_belongs_to_spec.rb
Labels: fix

#2065 fix: firefox record selection persists on reload & firefox row border
  app/components/avo/index/table_row_component.html.erb
  app/helpers/avo/resources_helper.rb
Labels: fix

#2079 feature: assign stimulus to actions
  Gemfile.lock
  app/components/avo/field_wrapper_component.rb
  app/controllers/avo/actions_controller.rb
  app/views/avo/actions/show.html.erb
  lib/avo/base_action.rb
  lib/avo/base_resource.rb
  lib/avo/concerns/has_action_stimulus_controllers.rb
  lib/avo/concerns/has_resource_stimulus_controllers.rb
  lib/avo/fields/base_field.rb
  lib/avo/fields/concerns/has_html_attributes.rb
  spec/dummy/app/avo/actions/show_current_time.rb
  spec/dummy/app/avo/resources/course.rb
  spec/dummy/app/javascript/avo.custom.js
  spec/dummy/app/javascript/avo_custom/city_in_country_controller.js
  spec/dummy/app/models/course.rb
  spec/system/avo/stimulus_spec.rb
Labels: feature

#2086 fix: belongs_to row forms layout
  app/components/avo/fields/belongs_to_field/edit_component.html.erb
  app/components/avo/fields/belongs_to_field/edit_component.rb
Labels: fix

#2088 chore: update eslint
  .eslintrc.json
  package.json
  yarn.lock
Labels: chore

#2091 fix: `via_resource_class` on `belongs_to` fields
  app/components/avo/fields/has_one_field/show_component.rb
  spec/features/avo/create_has_one_spec.rb
Labels: fix

#2095 fix: main_panel extraction
  lib/avo/concerns/has_items.rb
Labels: fix

#2094 fix: links from 2.0 to 3.0
  app/views/avo/home/_actions.html.erb
  app/views/avo/home/_dashboards.html.erb
  app/views/avo/home/_filters.html.erb
  app/views/avo/home/_resources.html.erb
  lib/avo/resources/resource_manager.rb
  spec/features/avo/resource_missing_model_spec.rb
Labels: fix

#2087 feature: durable and bookmarkable tabs
  app/components/avo/button_component.rb
  app/components/avo/fields/edit_component.rb
  app/components/avo/fields/has_many_field/show_component.html.erb
  app/components/avo/fields/has_many_field/show_component.rb
  app/components/avo/fields/index_component.rb
  app/components/avo/fields/show_component.rb
  app/components/avo/items/switcher_component.rb
  app/components/avo/tab_group_component.html.erb
  app/components/avo/tab_group_component.rb
  app/components/avo/tab_switcher_component.html.erb
  app/components/avo/tab_switcher_component.rb
  app/javascript/avo.base.js
  app/javascript/js/controllers/tabs_controller.js
  app/javascript/js/local-storage-service.js
  lib/avo/base_resource.rb
  lib/avo/concerns/has_items.rb
  lib/avo/resources/items/holder.rb
  lib/avo/resources/items/tab.rb
  lib/avo/resources/items/tab_group.rb
  lib/avo/test_helpers.rb
  safelist.txt
  spec/dummy/app/avo/resources/user.rb
  spec/system/avo/app_spec.rb
  spec/system/avo/belongs_to_polymorphic_spec.rb
  spec/system/avo/fields_across_multiple_methods_spec.rb
  spec/system/avo/has_many_spec.rb
  spec/system/avo/tabs_spec.rb
  spec/system/avo/test_helpers_spec.rb
Labels: feature

#2093 fix: allow all chars on text filters
  app/controllers/avo/base_controller.rb
  app/javascript/js/controllers/filter_controller.js
  lib/avo/filters/base_filter.rb
  spec/system/avo/filters/filters_spec.rb
Labels: fix

#2098 fix: tabs visibility
  lib/avo/concerns/has_items.rb
Labels: fix

#2104 fix: dynamic filters
  app/controllers/avo/base_controller.rb
Labels: fix

#2101 fix: search current_user
  app/controllers/avo/search_controller.rb
Labels: fix

#2191 fix: status-field dynamic filter missing some options
  lib/avo/fields/status_field.rb
Labels: Fix

#2193 chore: unlock turbo_power version lock
  Gemfile
  avo.gemspec
  gemfiles/rails_6.0_ruby_3.0.3.gemfile
  gemfiles/rails_6.0_ruby_3.2.2.gemfile
  gemfiles/rails_6.1_ruby_3.0.3.gemfile
  gemfiles/rails_6.1_ruby_3.2.2.gemfile
  gemfiles/rails_7.0_ruby_3.0.3.gemfile
  gemfiles/rails_7.0_ruby_3.2.2.gemfile
  gemfiles/rails_7.1_ruby_3.0.3.gemfile
  gemfiles/rails_7.1_ruby_3.2.2.gemfile
Labels: Chore

#2194 chore: update workflow files
  .github/pr-labeler.yml
  .github/release-drafter.yml
  .github/workflows/stale.yml
  spec/dummy/app/avo/resources/project.rb
Labels: Chore

#2196 chore: try Turbo 8
  Gemfile.lock
  app/javascript/js/application.js
  app/javascript/js/custom-stream-actions.js
  app/views/avo/associations/create.turbo_stream.erb
  app/views/layouts/avo/application.html.erb
  avo.gemspec
  lib/avo/engine.rb
  package.json
  yarn.lock
Labels: Chore

#2188 fix: action authorize variables, direct access to `view` and `resource` instead `action.resource.view`
  lib/avo/base_action.rb
Labels: Fix

#2189 fix: applied filters when filters are dynamic
  lib/avo/filters/base_filter.rb
Labels: Fix

#2102 fix: `belongs_to` index field name
  lib/avo/fields/belongs_to_field.rb
Labels: Fix

#2062 Feature/better error for missing resource
  app/controllers/avo/application_controller.rb
  db/factories.rb
  lib/avo.rb
  lib/avo/fields/base_field.rb
  lib/avo/fields/belongs_to_field.rb
  lib/avo/fields/has_base_field.rb
  spec/dummy/app/avo/resources/course.rb
  spec/dummy/app/avo/resources/event.rb
  spec/dummy/app/avo/resources/store.rb
  spec/dummy/app/avo/resources/team.rb
  spec/dummy/app/controllers/avo/events_controller.rb
  spec/dummy/app/controllers/avo/stores_controller.rb
  spec/dummy/app/models/city.rb
  spec/dummy/app/models/course.rb
  spec/dummy/app/models/event.rb
  spec/dummy/app/models/location.rb
  spec/dummy/app/models/store.rb
  spec/dummy/app/models/team.rb
  spec/dummy/config/initializers/avo.rb
  spec/dummy/db/migrate/20231126035843_create_locations.rb
  spec/dummy/db/migrate/20231205153910_create_courses_locations.rb
  spec/dummy/db/migrate/20231206095919_add_location_to_events.rb
  spec/dummy/db/migrate/20231206112806_create_stores.rb
  spec/dummy/db/migrate/20231206113153_add_store_to_locations.rb
  spec/dummy/db/migrate/20231212231204_make_team_id_nullable_on_locations.rb
  spec/dummy/db/schema.rb
  spec/dummy/db/seeds.rb
  spec/features/avo/generators/resource_generator_spec.rb
  spec/features/avo/model_missing_resource_spec.rb
Labels: Feature

#2259 chore: revert bad turbo 8 merge
  Gemfile.lock
  app/javascript/js/application.js
  app/javascript/js/custom-stream-actions.js
  app/views/avo/associations/create.turbo_stream.erb
  app/views/layouts/avo/application.html.erb
  avo.gemspec
  gemfiles/rails_6.0_ruby_3.0.3.gemfile.lock
  gemfiles/rails_6.0_ruby_3.2.2.gemfile.lock
  gemfiles/rails_6.1_ruby_3.0.3.gemfile.lock
  gemfiles/rails_6.1_ruby_3.2.2.gemfile.lock
  gemfiles/rails_7.0_ruby_3.0.3.gemfile.lock
  gemfiles/rails_7.0_ruby_3.2.2.gemfile.lock
  gemfiles/rails_7.1_ruby_3.0.3.gemfile.lock
  gemfiles/rails_7.1_ruby_3.2.2.gemfile.lock
  lib/avo/engine.rb
  package.json
  yarn.lock
Labels: Chore

#2260 fix: stimulus attributes crashing on grid view
  lib/avo/fields/concerns/has_html_attributes.rb
Labels: Fix

#2256 chore: remove ujs
  app/components/avo/resource_component.rb
  app/components/avo/sidebar_profile_component.html.erb
  app/javascript/avo.base.js
  package.json
  spec/system/avo/belongs_to_polymorphic_spec.rb
  spec/system/avo/sign_out_dropdown_spec.rb
  yarn.lock
Labels: Chore

#2267 refactor: equal width columns in rows
  app/components/avo/field_wrapper_component.html.erb
  app/components/avo/row_component.html.erb
  spec/system/avo/app_spec.rb
Labels: Refactor

#2281 fix: custom_streams_actions.js
  app/javascript/js/custom-stream-actions.js
Labels: Fix

#2286 create ja locale
  config/initializers/pagy.rb
  lib/generators/avo/templates/locales/avo.ja.yml
  spec/features/avo/generators/locales_generator_spec.rb
Labels: Chore

#2288 chore: expose query to scopes
  app/components/avo/views/resource_index_component.rb
  lib/generators/avo/templates/scope.tt
Labels: Chore

#2290 chore: remove brakeman
  Gemfile
  Gemfile.lock
  gemfiles/rails_6.0_ruby_3.0.3.gemfile
  gemfiles/rails_6.0_ruby_3.2.2.gemfile
  gemfiles/rails_6.1_ruby_3.0.3.gemfile
  gemfiles/rails_6.1_ruby_3.2.2.gemfile
  gemfiles/rails_7.0_ruby_3.0.3.gemfile
  gemfiles/rails_7.0_ruby_3.2.2.gemfile
  gemfiles/rails_7.1_ruby_3.0.3.gemfile
  gemfiles/rails_7.1_ruby_3.2.2.gemfile
Labels: Chore

#2278 fix: tabs persistence when tab name has spaces
  app/components/avo/tab_group_component.rb
  app/components/avo/tab_switcher_component.rb
  lib/avo/resources/items/tab_group.rb
  spec/system/avo/tabs_spec.rb
Labels: Fix

#2297 fix: secret key base warning
  lib/avo/services/encryption_service.rb
  spec/dummy/config/boot.rb
  spec/rails_helper.rb
Labels: Fix
