Repository avo-hq/avo, pull requests merged in 2023-06, with the labels that each got.

#1774 fix: sidebar broken on mobile view
  .github/ISSUE_TEMPLATE/blank_issue.md
  .github/ISSUE_TEMPLATE/bug_report.md
  app/components/avo/panel_component.html.erb
Labels: fix

#1779 fix: broken non-poly belongs to
  lib/avo/fields/belongs_to_field.rb
Labels: fix, codeball:approved

#1780 feature: add method and params to link_to method in the profile menu
  app/components/avo/profile_item_component.html.erb
  app/components/avo/profile_item_component.rb
  app/components/avo/sidebar_profile_component.html.erb
  app/views/avo/partials/_profile_menu_extra.html.erb
  lib/avo/menu/link.rb
  lib/generators/avo/eject_generator.rb
  spec/dummy/config/initializers/avo.rb
Labels: feature, codeball:needs-review

#1785 fix: remove unpermitted param from action run method
  app/controllers/avo/actions_controller.rb
Labels: fix, codeball:approved

#1787 refactor: remove default i18n load dir
  lib/avo/engine.rb
Labels: refactor, codeball:approved

#1784 fix: allow extra pagy i8n load
  config/initializers/pagy.rb
  spec/dummy/config/initializers/pagy.rb
  spec/features/avo/discreet_pagination_spec.rb
Labels: fix, codeball:needs-review

#1789 fix: prevent eager loading of computed file fields
  app/components/avo/fields/file_field/index_component.rb
  app/components/avo/fields/index_component.rb
  app/controllers/avo/application_controller.rb
  lib/avo/base_resource.rb
  spec/dummy/app/avo/resources/user_resource.rb
Labels: fix, codeball:approved

#1800 fix: menu icons on community license
  app/components/avo/sidebar_component.html.erb
Labels: fix, codeball:needs-review

#1806 fix: hide tags field on community license
  lib/avo/concerns/has_fields.rb
  lib/avo/items_holder.rb
  spec/dummy/db/seeds.rb
Labels: fix

#1797 feature: format_using and update_using field options
  app/components/avo/fields/area_field/edit_component.html.erb
  app/components/avo/fields/boolean_field/edit_component.html.erb
  app/components/avo/fields/code_field/edit_component.html.erb
  app/components/avo/fields/country_field/edit_component.html.erb
  app/components/avo/fields/markdown_field/edit_component.html.erb
  app/components/avo/fields/number_field/edit_component.html.erb
  app/components/avo/fields/password_field/edit_component.html.erb
  app/components/avo/fields/progress_bar_field/edit_component.html.erb
  app/components/avo/fields/status_field/edit_component.html.erb
  app/components/avo/fields/text_field/edit_component.html.erb
  app/components/avo/fields/textarea_field/edit_component.html.erb
  app/components/avo/fields/trix_field/edit_component.html.erb
  app/components/avo/views/resource_edit_component.html.erb
  lib/avo/base_resource.rb
  lib/avo/execution_context.rb
  lib/avo/fields/base_field.rb
  spec/dummy/app/avo/resources/city_resource.rb
  spec/dummy/app/avo/resources/comment_resource.rb
  spec/dummy/app/avo/resources/photo_comment_resource.rb
  spec/dummy/app/avo/resources/post_resource.rb
  spec/dummy/app/avo/resources/product_resource.rb
  spec/dummy/app/avo/resources/team_resource.rb
  spec/dummy/app/avo/resources/user_resource.rb
  spec/dummy/app/avo/resources/z_post_resource.rb
  spec/dummy/app/models/city.rb
  spec/dummy/app/views/avo/resource_tools/_city_editor.html.erb
  spec/features/avo/native_fields_spec.rb
  spec/system/avo/date_time_fields/date_time_eastern_spec.rb
  spec/system/avo/date_time_fields/date_time_utc_spec.rb
  spec/system/avo/date_time_fields/date_time_western_spec.rb
Labels: feature, codeball:needs-careful-review

#1804 refactor: stop checking the license if in test env
  .editorconfig
  lib/avo/licensing/h_q.rb
  lib/avo/licensing/license.rb
  lib/avo/licensing/license_manager.rb
  lib/avo/licensing/nil_license.rb
  spec/features/avo/h_q_spec.rb
  spec/system/avo/filters/filters_spec.rb
Labels: refactor, codeball:approved

#1817 fix: stored_as for location field broken
  Gemfile.lock
  app/components/avo/fields/area_field/edit_component.html.erb
  db/factories.rb
  lib/avo/fields/location_field.rb
  spec/components/avo/index/resource_map_component_spec.rb
  spec/dummy/app/avo/resources/city_resource.rb
  spec/dummy/app/models/city.rb
  spec/system/avo/area_field_spec.rb
  spec/system/avo/location_field_spec.rb
Labels: fix
