Repository avo-hq/avo, pull requests merged in 2023-05, with the labels that each got.

#1723 Upgrade css-loader npm library
  package.json
  yarn.lock
Labels: codeball:needs-review

#1716 Remove outdated @tailwindcss/jit
  package.json
  yarn.lock
Labels: codeball:needs-review

#1722 Upgrade eslint NPM packages
  package.json
  yarn.lock
Labels: codeball:needs-careful-review

#1721 Upgrade postcss-* npm packages
  package.json
  yarn.lock
Labels: codeball:needs-review

#1714 Add autocomplete field option
  app/components/avo/fields/country_field/edit_component.html.erb
  app/components/avo/fields/number_field/edit_component.html.erb
  app/components/avo/fields/password_field/edit_component.html.erb
  app/components/avo/fields/select_field/edit_component.html.erb
  app/components/avo/fields/text_field/edit_component.html.erb
  lib/avo/fields/base_field.rb
Labels: codeball:needs-careful-review

#1679 Resource index map component
  app/assets/stylesheets/avo.base.css
  app/assets/svgs/map-empty-state.svg
  app/assets/svgs/map-view-type.svg
  app/components/avo/index/resource_map_component.html.erb
  app/components/avo/index/resource_map_component.rb
  app/components/avo/views/resource_index_component.html.erb
  app/views/avo/partials/_view_toggle_button.html.erb
  lib/avo/base_resource.rb
  spec/components/avo/index/resource_map_component_spec.rb
  spec/dummy/app/avo/resources/city_resource.rb
  spec/system/avo/resource_index_map_spec.rb
Labels: codeball:needs-careful-review

#1728 refactor: use Host for map view proc
  app/components/avo/index/resource_map_component.rb
  spec/dummy/app/avo/resources/city_resource.rb
Labels: refactor, codeball:needs-careful-review

#1712 fix: hydrate resource properly on form submission
  app/controllers/avo/application_controller.rb
Labels: fix, codeball:needs-careful-review

#1720 [Fix] When initializing an Action any class variables should be set to nil if appropriate
  lib/avo/base_action.rb
  spec/dummy/app/avo/actions/release_fish.rb
Labels: fix, codeball:needs-review

#1732 Refer to cache class without calling them
  lib/avo/app.rb
Labels: codeball:needs-review

#1740 Include pagination on resource index map view
  app/components/avo/views/resource_index_component.html.erb
Labels: codeball:needs-review

#1741 chore: better memory store lookup
  lib/avo/app.rb
  lib/avo/concerns/fetches_things.rb
Labels: chore, codeball:approved

#1742 Add space after `overflow-auto` class
  app/components/avo/index/resource_map_component.html.erb
Labels: fix, codeball:needs-review

#1746 refactor: enable action namespacing
  app/components/avo/actions_component.rb
  app/views/avo/actions/show.html.erb
  config/routes.rb
  lib/avo/base_action.rb
  lib/avo/resources/controls/action.rb
  spec/dummy/app/avo/actions/sub/dummy_action.rb
  spec/dummy/app/avo/resources/fish_resource.rb
  spec/dummy/app/avo/resources/team_resource.rb
  spec/dummy/app/avo/resources/user_resource.rb
  spec/features/avo/custom_resource_controls_spec.rb
Labels: refactor, codeball:needs-review

#1737 feature: when installing Avo detect if User model exists and create a resource for it
  lib/generators/avo/install_generator.rb
Labels: codeball:needs-review

#1749 fix(searchControllerJs): encodes special chars in query
  app/javascript/js/controllers/search_controller.js
  spec/features/avo/search_spec.rb
Labels: codeball:needs-review

#1729 Replace SimpleMDE with EasyMDE
  app/assets/stylesheets/avo.base.css
  app/components/avo/fields/markdown_field/edit_component.html.erb
  app/components/avo/fields/markdown_field/show_component.html.erb
  app/javascript/js/controllers.js
  app/javascript/js/controllers/fields/easy_mde_controller.js
  package.json
  yarn.lock
Labels: codeball:needs-careful-review

#1755 fix: default field option as a block in actions
  lib/avo/base_action.rb
Labels: fix, codeball:approved

#1756 fix: through reflection in generator
  lib/generators/avo/resource_generator.rb
Labels: fix, codeball:approved

#1757 feature: callable app_name
  lib/avo/configuration.rb
  spec/dummy/config/initializers/avo.rb
  spec/features/avo/app_spec.rb
Labels: feature, codeball:approved

#1762 fix: valid file cache store path
  lib/avo/app.rb
Labels: fix, codeball:needs-careful-review
