Repository avo-hq/avo, pull requests merged in 2023-07, with the labels that each got.

#1825 chore: minor tweaks
  app/components/avo/fields/belongs_to_field/edit_component.rb
  app/components/avo/sidebar/link_component.html.erb
  app/components/avo/views/resource_edit_component.rb
Labels: chore

#1827 fix: updatable row inputs
  app/controllers/avo/base_controller.rb
  lib/avo/concerns/has_fields.rb
Labels: fix

#1829 chore: add the attachment resource as a demo
  spec/dummy/app/avo/resources/attachment_resource.rb
  spec/dummy/app/avo/resources/post_resource.rb
  spec/dummy/app/avo/resources/project_resource.rb
  spec/dummy/app/controllers/avo/attachments_controller.rb
Labels: chore

#1830 fix: rename clashing controller
  spec/dummy/app/avo/resources/active_record_attachment_resource.rb
  spec/dummy/app/controllers/avo/active_record_attachments_controller.rb
Labels: fix

#1826 fix: tab visibility
  app/components/avo/tab_switcher_component.rb
  lib/avo/fields/field_extensions/visible_in_different_views.rb
  lib/avo/tab.rb
  spec/system/avo/tabs_spec.rb
Labels: fix

#1831 fix: use resource find record on search instead model direct find
  app/controllers/avo/search_controller.rb
Labels: fix

#1832 fix: allow nil values on grid cover
  app/components/avo/index/grid_item_component.html.erb
Labels: fix

#1833 fix: action visibility on show controls
  app/components/avo/views/resource_show_component.html.erb
  lib/avo/resources/controls/action.rb
  spec/features/avo/custom_resource_controls_spec.rb
Labels: fix

#1835 Added zoom to location fields
  app/components/avo/fields/location_field/show_component.html.erb
  lib/avo/fields/location_field.rb
Labels: enhancement

#1846 fix: location field new view
  lib/avo/base_resource.rb
  lib/avo/fields/base_field.rb
  lib/avo/fields/location_field.rb
  spec/system/avo/location_field_spec.rb
Labels: fix

#1847 fix: belongs to field target inside tab -> panel -> row
  lib/avo/concerns/has_fields.rb
Labels: fix

#1848 fix: authorize show controls actions
  app/components/avo/resource_component.rb
  app/components/avo/views/resource_edit_component.html.erb
  app/components/avo/views/resource_index_component.html.erb
  app/components/avo/views/resource_show_component.html.erb
  app/components/avo/views/resource_show_component.rb
Labels: fix

#1849 fix: markdown field not appearing on edit in tab
  app/javascript/js/controllers/fields/easy_mde_controller.js
Labels: fix

#1852 fix: trix attachment broken for GCP
  app/controllers/avo/attachments_controller.rb
Labels: fix

#1854 chore: yarn audit fix
  yarn.lock
Labels: chore

#1856 fix: don't render detach button when can't detach record
  app/components/avo/index/resource_controls_component.rb
  app/components/avo/resource_component.rb
  app/controllers/avo/associations_controller.rb
  spec/dummy/app/models/course/link.rb
  spec/dummy/app/models/person.rb
  spec/dummy/app/models/project.rb
  spec/dummy/app/models/spouse.rb
  spec/dummy/app/models/team.rb
  spec/dummy/app/models/user.rb
Labels: fix

#1863 add with_bare_sidebar to PanelComponent
  app/components/avo/panel_component.html.erb
  app/components/avo/panel_component.rb
Labels: enhancement

#1865 fix: action view set to new
  app/controllers/avo/actions_controller.rb
  spec/dummy/app/avo/actions/sub/dummy_action.rb
Labels: fix

#1874 fix: warning instead raising error when can't find the inverse_of
  app/components/avo/resource_component.rb
  spec/dummy/app/models/project.rb
  spec/rails_helper.rb
Labels: fix
