Repository avo-hq/avo, pull requests merged in 2023-01, with the labels that each got.

#1504 fix: JS root path without query param
  app/helpers/avo/application_helper.rb
  app/javascript/js/controllers/search_controller.js
Labels: fix

#1508 feature: timezone callable
  lib/avo/fields/date_time_field.rb
  lib/avo/fields/time_field.rb
  spec/dummy/app/avo/resources/course_resource.rb
Labels: feature

#1525 feature: enable using field components without a form object
  app/helpers/avo/application_helper.rb
Labels: feature

#1526 fix: belongs to (non/)searchable uses same scoping
  lib/avo/fields/belongs_to_field.rb
Labels: fix

#1528 fix: searchable belongs_to uses valid view
  app/components/avo/fields/belongs_to_field/edit_component.html.erb
  app/components/avo/fields/belongs_to_field/edit_component.rb
  spec/support/helpers.rb
Labels: fix

#1529 refactor: base field initializes with a resource
  lib/avo/fields/base_field.rb
  spec/dummy/app/avo/resource_tools/team_membership_tool_playground.rb
  spec/dummy/app/avo/resources/membership_resource.rb
  spec/dummy/app/views/avo/resource_tools/_team_membership_tool_playground.html.erb
Labels: refactor

#1537 feature: add data attributes to table headers
  app/views/avo/partials/_table_header.html.erb
Labels: feature

#1552 fix: resource generator several fixes
  lib/generators/avo/resource_generator.rb
Labels: fix
