Repository avo-hq/avo, pull requests merged in 2023-11, with the labels that each got.

#1994 feature: multi action flow
  Gemfile
  Gemfile.lock
  app/controllers/avo/actions_controller.rb
  app/javascript/js/application.js
  avo.gemspec
  gemfiles/rails_6.0_ruby_3.0.3.gemfile
  gemfiles/rails_6.0_ruby_3.0.3.gemfile.lock
  gemfiles/rails_6.0_ruby_3.2.2.gemfile
  gemfiles/rails_6.0_ruby_3.2.2.gemfile.lock
  gemfiles/rails_6.1_ruby_3.0.3.gemfile
  gemfiles/rails_6.1_ruby_3.0.3.gemfile.lock
  gemfiles/rails_6.1_ruby_3.2.2.gemfile
  gemfiles/rails_6.1_ruby_3.2.2.gemfile.lock
  gemfiles/rails_7.0_ruby_3.0.3.gemfile
  gemfiles/rails_7.0_ruby_3.0.3.gemfile.lock
  gemfiles/rails_7.0_ruby_3.2.2.gemfile
  gemfiles/rails_7.0_ruby_3.2.2.gemfile.lock
  lib/avo/base_action.rb
  package.json
  spec/dummy/app/avo/actions/pre_update.rb
  spec/dummy/app/avo/actions/update.rb
  spec/dummy/app/avo/resources/user_resource.rb
  spec/system/avo/action_filter_spec.rb
  spec/system/avo/multiple_actions_flux_spec.rb
  yarn.lock
Labels: feature

#2020 fix: create belongs_to from associations with buttons on form footers
  app/components/avo/views/resource_edit_component.html.erb
Labels: fix

#1998 feature: countless pagination
  app/components/avo/index/resource_table_component.html.erb
  app/components/avo/index/resource_table_component.rb
  app/components/avo/paginator_component.html.erb
  app/components/avo/paginator_component.rb
  app/controllers/avo/application_controller.rb
  app/controllers/avo/base_controller.rb
  config/initializers/pagy.rb
  lib/avo/base_resource.rb
  lib/avo/concerns/pagination.rb
  lib/generators/avo/templates/locales/avo.en.yml
  lib/generators/avo/templates/locales/avo.fr.yml
  lib/generators/avo/templates/locales/avo.pt-BR.yml
  lib/generators/avo/templates/locales/avo.pt.yml
  lib/generators/avo/templates/locales/avo.ro.yml
  spec/system/avo/select_all_spec.rb
Labels: feature

#2038 fix: redirect on action when no_confirmation = true
  app/javascript/js/controllers/action_controller.js
  lib/avo/base_action.rb
  spec/system/avo/actions_spec.rb
Labels: fix

#2034 fix: detach should not destroy attachment
  app/controllers/avo/associations_controller.rb
Labels: fix

#2048 fix: create new record from belongs_to associations
  app/components/avo/fields/belongs_to_field/edit_component.rb
  spec/dummy/app/models/course/link.rb
  spec/dummy/config/locales/avo.es.yml
  spec/system/avo/create_via_belongs_to_spec.rb
Labels: fix

#2053 fix: extract fields from sidebar and add them to permitted params
  lib/avo/concerns/has_items.rb
  spec/dummy/app/avo/resources/user.rb
  spec/system/avo/resource_sidebar_spec.rb
Labels: fix

#2055 fix: sidebars on community tier
  app/components/avo/resource_component.rb
Labels: fix

#2068 chore: fix actions spec
  spec/dummy/app/avo/actions/test/no_confirmation_redirect.rb
  spec/dummy/app/avo/resources/user.rb
  spec/system/avo/actions_spec.rb
Labels: chore

#2069 chore: fix actions spec
  spec/dummy/app/avo/actions/test/no_confirmation_redirect.rb
  spec/dummy/app/avo/resources/user_resource.rb
  spec/system/avo/actions_spec.rb
Labels: chore

#2070 fix: ignore application js file
  avo.gemspec
Labels: fix
