Repository avo-hq/avo, pull requests merged in 2023-03, with the labels that each got.

#1610 Add greenhats as a sponsor
  README.md
Labels: chore

#1606 feature: card visibility
  lib/avo/base_card.rb
  lib/avo/concerns/visible_in_dashboard.rb
  lib/avo/dashboards/base_dashboard.rb
  lib/avo/dashboards/base_divider.rb
  lib/avo/hosts/card_visibility.rb
  spec/dummy/app/avo/cards/example_pie_chart.rb
  spec/dummy/app/avo/dashboards/dashy.rb
  spec/dummy/app/views/avo/partials/_footer.html.erb
Labels: feature

#1621 chore: create unlogged tables in test env
  spec/dummy/app/avo/resources/user_resource.rb
  spec/dummy/config/environments/test.rb
Labels: chore

#1620 feature: add use resource option to belongs to field
  lib/avo/fields/belongs_to_field.rb
  lib/avo/fields/concerns/use_resource.rb
  lib/avo/fields/has_base_field.rb
  spec/dummy/app/avo/resources/comment_resource.rb
  spec/dummy/app/avo/resources/compact_user_resource.rb
  spec/dummy/app/controllers/avo/compact_users_controller.rb
  spec/features/avo/use_resource_spec.rb
  spec/system/avo/belongs_to_polymorphic_spec.rb
Labels: feature

#1623 feature: fetch_labels option for tags field
  lib/avo/fields/tags_field.rb
  spec/dummy/app/avo/actions/toggle_inactive.rb
  spec/system/avo/tags_spec.rb
Labels: feature

#1625 feature: field level file authorization
  app/components/avo/fields/common/single_file_viewer_component.html.erb
  app/components/avo/fields/common/single_file_viewer_component.rb
  app/components/avo/fields/file_field/edit_component.html.erb
  app/components/avo/fields/file_field/edit_component.rb
  app/components/avo/fields/files_field/edit_component.html.erb
  app/components/avo/fields/files_field/edit_component.rb
  app/controllers/avo/attachments_controller.rb
  lib/avo/fields/concerns/file_authorization.rb
  spec/dummy/app/policies/post_policy.rb
  spec/dummy/app/policies/project_policy.rb
  spec/dummy/app/policies/user_policy.rb
  spec/system/avo/tags_spec.rb
Labels: feature

#1627 refactor: loose file authorization
  app/components/avo/fields/file_field/edit_component.html.erb
  app/components/avo/fields/files_field/edit_component.html.erb
  lib/avo/fields/concerns/file_authorization.rb
Labels: refactor

#1637 feature: date field support for string columns
  .github/release-drafter.yml
  lib/avo/fields/date_field.rb
  spec/dummy/app/avo/resources/post_resource.rb
Labels: feature

#1634 feature: add search_result_url and search_policy_class
  CONTRIBUTING.MD
  app/components/avo/views/resource_index_component.html.erb
  app/components/avo/views/resource_index_component.rb
  app/controllers/avo/search_controller.rb
  lib/avo/base_resource.rb
  lib/avo/hosts/base_host.rb
  lib/avo/services/authorization_service.rb
  lib/generators/avo/templates/initializer/avo.tt
  spec/dummy/app/avo/resources/city_resource.rb
  spec/dummy/app/policies/application_policy.rb
  spec/dummy/app/policies/course_link_policy.rb
  spec/dummy/app/policies/course_policy.rb
  spec/dummy/app/policies/post_policy.rb
  spec/dummy/app/policies/team_policy.rb
  spec/dummy/app/policies/user_policy.rb
  spec/dummy/config/initializers/avo.rb
  spec/features/avo/hidden_from_global_search_spec.rb
  spec/features/avo/search_with_custom_path.rb
  spec/rails_helper.rb
Labels: feature

#1646 fix: attachment delete action does not respond
  app/components/avo/fields/common/single_file_viewer_component.html.erb
  app/views/layouts/avo/application.html.erb
Labels: fix

#1642 fix: better mount point discovery
  app/helpers/avo/application_helper.rb
  lib/avo/configuration.rb
  lib/generators/avo/templates/initializer/avo.tt
  spec/dummy/config.ru
  spec/dummy/config/application.rb
  spec/dummy/config/initializers/avo.rb
  spec/dummy/config/routes.rb
Labels: fix

#1652 fix: failing to find record on has_one associations
  app/components/avo/fields/belongs_to_field/edit_component.rb
  app/components/avo/fields/has_one_field/show_component.rb
  app/components/avo/referrer_params_component.html.erb
  app/components/avo/views/resource_index_component.rb
  app/controllers/avo/base_controller.rb
  lib/avo/base_resource.rb
  lib/avo/fields/has_one_field.rb
  spec/dummy/app/models/team.rb
  spec/dummy/app/models/user.rb
  spec/features/avo/create_has_one_spec.rb
Labels: fix

#1655 fix: divider renders invisible by default
  lib/avo/dashboards/base_divider.rb
Labels: fix
