Repository avo-hq/avo, pull requests merged in 2023-04, with the labels that each got.

#1660 fix: resource generator enum model class naming
  lib/generators/avo/resource_generator.rb
Labels: fix

#1671 chore: add codeball action
  .github/workflows/codeball.yml
Labels: chore, codeball:needs-review

#1674 feature: display_filename option for file and files field
  app/components/avo/fields/common/single_file_viewer_component.html.erb
  app/components/avo/fields/common/single_file_viewer_component.rb
  lib/avo/fields/file_field.rb
  lib/avo/fields/files_field.rb
  spec/dummy/app/avo/resources/post_resource.rb
Labels: feature, codeball:needs-review

#1681 fix: allow field visible false
  lib/avo/fields/base_field.rb
Labels: fix, codeball:approved

#1682 security: update nokogiri
  Gemfile.lock
  gemfiles/rails_6.0_ruby_3.0.3.gemfile.lock
  gemfiles/rails_6.0_ruby_3.1.0.gemfile.lock
  gemfiles/rails_6.0_ruby_3.2.1.gemfile.lock
  gemfiles/rails_6.1_ruby_3.0.3.gemfile.lock
  gemfiles/rails_6.1_ruby_3.1.0.gemfile.lock
  gemfiles/rails_6.1_ruby_3.2.1.gemfile.lock
  gemfiles/rails_7.0_ruby_3.0.3.gemfile.lock
  gemfiles/rails_7.0_ruby_3.1.0.gemfile.lock
  gemfiles/rails_7.0_ruby_3.2.1.gemfile.lock
Labels: codeball:needs-review

#1684 fix: disable sorting on id field
  lib/avo/fields/id_field.rb
  spec/dummy/app/avo/resources/user_resource.rb
  spec/features/avo/field_sorting_spec.rb
Labels: fix, codeball:needs-review

#1667 improvement: another approach on attachments field level authorization
  app/controllers/avo/attachments_controller.rb
  lib/avo/fields/concerns/file_authorization.rb
  spec/dummy/app/policies/course_link_policy.rb
  spec/dummy/app/policies/course_policy.rb
  spec/dummy/app/policies/photo_comment_policy.rb
  spec/dummy/app/policies/post_policy.rb
  spec/dummy/app/policies/project_policy.rb
  spec/dummy/app/policies/team_policy.rb
  spec/dummy/app/policies/user_policy.rb
Labels: fix, refactor

#1687 Revert "refactor: change default as false on cache_resources_on_index_view"
  lib/avo/configuration.rb
  lib/generators/avo/templates/initializer/avo.tt
Labels: refactor, codeball:needs-review

#1690 Add helpers for encoding/decoding filter params
  app/helpers/avo/application_helper.rb
  lib/avo/filters/base_filter.rb
  spec/helpers/avo/application_helper_spec.rb
Labels: codeball:needs-review

#1683 feature: files view type
  app/components/avo/field_wrapper_component.html.erb
  app/components/avo/fields/common/files/controls_component.html.erb
  app/components/avo/fields/common/files/controls_component.rb
  app/components/avo/fields/common/files/list_viewer_component.html.erb
  app/components/avo/fields/common/files/list_viewer_component.rb
  app/components/avo/fields/common/files/view_type/grid_component.html.erb
  app/components/avo/fields/common/files/view_type/grid_component.rb
  app/components/avo/fields/common/files/view_type/list_component.html.erb
  app/components/avo/fields/common/files/view_type/list_component.rb
  app/components/avo/fields/common/files_list_viewer_component.html.erb
  app/components/avo/fields/common/files_list_viewer_component.rb
  app/components/avo/fields/common/single_file_viewer_component.html.erb
  app/components/avo/fields/file_field/edit_component.html.erb
  app/components/avo/fields/file_field/show_component.html.erb
  app/components/avo/fields/files_field/edit_component.html.erb
  app/components/avo/fields/files_field/show_component.html.erb
  app/controllers/avo/attachments_controller.rb
  app/views/avo/attachments/destroy.turbo_stream.erb
  app/views/avo/partials/_view_toggle_button.html.erb
  db/factories.rb
  lib/avo/fields/files_field.rb
  spec/dummy/app/avo/resources/project_resource.rb
  spec/dummy/db/migrate/20210603100519_add_service_name_to_active_storage_blobs.active_storage.rb
  spec/dummy/db/migrate/20210603100520_create_active_storage_variant_records.active_storage.rb
  spec/dummy/db/seed_files/dummy-video.mp4
  spec/system/avo/fields_view_type_spec.rb
Labels: feature, codeball:needs-careful-review

#1694 security: avoid form manipulation on non-visible fields
  lib/avo/fields/base_field.rb
Labels: fix, codeball:needs-review

#1698 Chore: support view component v3 by updating slot setter methods to new `with_*` API
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/workflows/test.yml
  Appraisals
  Gemfile
  Gemfile.lock
  app/components/avo/actions_component.rb
  app/components/avo/fields/has_many_field/show_component.html.erb
  app/components/avo/fields/has_one_field/show_component.html.erb
  app/components/avo/item_switcher_component.html.erb
  app/components/avo/views/resource_edit_component.html.erb
  app/components/avo/views/resource_index_component.html.erb
  app/components/avo/views/resource_show_component.html.erb
  app/views/avo/actions/show.html.erb
  app/views/avo/associations/new.html.erb
  app/views/avo/dashboards/show.html.erb
  app/views/avo/debug/index.html.erb
  app/views/avo/home/index.html.erb
  app/views/avo/private/design.html.erb
  avo.gemspec
  gemfiles/rails_6.0_ruby_3.0.3.gemfile
  gemfiles/rails_6.0_ruby_3.0.3.gemfile.lock
  gemfiles/rails_6.0_ruby_3.1.0.gemfile.lock
  gemfiles/rails_6.0_ruby_3.2.2.gemfile
  gemfiles/rails_6.0_ruby_3.2.2.gemfile.lock
  gemfiles/rails_6.1_ruby_3.0.3.gemfile
  gemfiles/rails_6.1_ruby_3.0.3.gemfile.lock
  gemfiles/rails_6.1_ruby_3.1.0.gemfile
  gemfiles/rails_6.1_ruby_3.1.0.gemfile.lock
  gemfiles/rails_6.1_ruby_3.2.1.gemfile
  gemfiles/rails_6.1_ruby_3.2.2.gemfile
  gemfiles/rails_6.1_ruby_3.2.2.gemfile.lock
  gemfiles/rails_7.0_ruby_3.0.3.gemfile
  gemfiles/rails_7.0_ruby_3.0.3.gemfile.lock
  gemfiles/rails_7.0_ruby_3.2.1.gemfile
  gemfiles/rails_7.0_ruby_3.2.1.gemfile.lock
  gemfiles/rails_7.0_ruby_3.2.2.gemfile
  gemfiles/rails_7.0_ruby_3.2.2.gemfile.lock
  lib/avo/engine.rb
  lib/generators/avo/templates/resource_tools/partial.tt
  lib/generators/avo/templates/tool/view.tt
  spec/components/avo/common/files_list_viewer_component_spec.rb
  spec/components/avo/common/single_file_viewer_component_spec.rb
  spec/dummy/app/views/avo/partials/_fish_review.html.erb
  spec/dummy/app/views/avo/resource_tools/_city_editor.html.erb
  spec/dummy/app/views/avo/resource_tools/_fish_information.html.erb
  spec/dummy/app/views/avo/resource_tools/_nested_fish_reviews.html.erb
  spec/dummy/app/views/avo/resource_tools/_team_membership_tool_playground.html.erb
  spec/dummy/app/views/avo/resource_tools/_user_tool.html.erb
  spec/dummy/app/views/avo/tools/custom_tool.html.erb
  spec/requests/avo/authorization/associations_spec.rb
Labels: codeball:needs-careful-review

#1705 fix: readonly as proc
  app/components/avo/resource_component.rb
  lib/avo/fields/base_field.rb
Labels: fix, codeball:needs-review

#1715 Add Rails 7.0.x to the test matrix
  .github/workflows/test.yml
  lib/avo/concerns/fetches_things.rb
Labels: codeball:needs-careful-review
