Repository avo-hq/avo, pull requests merged in 2023-10, with the labels that each got.

#1959 Avo typo fixes
  lib/avo/app.rb
Labels: fix

#1954 fix: broken readme demo link
  README.md
Labels: fix

#1935 fix: file image doesn't render in full size
  app/components/avo/fields/common/files/list_viewer_component.rb
  app/components/avo/fields/common/files/view_type/grid_item_component.html.erb
  app/components/avo/fields/common/files/view_type/grid_item_component.rb
  app/components/avo/fields/common/files/view_type/list_item_component.html.erb
  app/components/avo/fields/common/files/view_type/list_item_component.rb
  app/components/avo/fields/file_field/edit_component.html.erb
  app/components/avo/fields/file_field/show_component.html.erb
Labels: fix, Stale

#1957 feature: allow params on resource menu item
  app/components/avo/sidebar/item_switcher_component.html.erb
  lib/avo/menu/resource.rb
  spec/dummy/config/initializers/avo.rb
  spec/features/avo/menu_builder_spec.rb
  spec/features/avo/menu_item_spec.rb
Labels: feature

#1956 bug: Update fetches_things.rb to use custom policy if available
  lib/avo/concerns/fetches_things.rb
Labels: fix

#1964 fix: variant resize image
  app/components/avo/fields/common/files/view_type/grid_item_component.html.erb
  spec/dummy/app/avo/resources/post_resource.rb
Labels: fix

#1983 feature: allow custom cache store & improve the computed one
  lib/avo/app.rb
  lib/avo/configuration.rb
  lib/avo/execution_context.rb
  lib/generators/avo/templates/initializer/avo.tt
Labels: feature

#1876 Create a `belongs_to` record from the associated record screen
  app/components/avo/fields/belongs_to_field/edit_component.html.erb
  app/components/avo/fields/belongs_to_field/edit_component.rb
  app/components/avo/modal_component.html.erb
  app/components/avo/modal_component.rb
  app/components/avo/panel_component.html.erb
  app/components/avo/referrer_params_component.html.erb
  app/components/avo/views/resource_edit_component.html.erb
  app/components/avo/views/resource_edit_component.rb
  app/controllers/avo/actions_controller.rb
  app/controllers/avo/base_controller.rb
  app/helpers/avo/application_helper.rb
  app/javascript/js/controllers.js
  app/javascript/js/controllers/fields/reload_belongs_to_field_controller.js
  app/views/avo/actions/keep_modal_open.turbo_stream.erb
  app/views/avo/actions/show.html.erb
  app/views/avo/base/_new_via_belongs_to.html.erb
  app/views/avo/base/close_modal_and_reload_field.turbo_stream.erb
  app/views/avo/base/create_fail_action.turbo_stream.erb
  app/views/avo/partials/_flash_alerts.turbo_stream.erb
  spec/system/avo/create_via_belongs_to_spec.rb
Labels: Stale exempt

#1988 feature: allow suggestions_max_items option on tags field
  app/components/avo/fields/tags_field/edit_component.html.erb
  app/javascript/js/controllers/fields/tags_field_controller.js
  lib/avo/fields/tags_field.rb
  spec/dummy/app/avo/resources/post_resource.rb
Labels: feature

#1995 fix: move dummy controller
  spec/dummy/app/controllers/avo/team_users_controller.rb
Labels: fix

#1992 fix: actions and field hydration
  app/controllers/avo/actions_controller.rb
  app/views/avo/actions/show.html.erb
  lib/avo/action_model.rb
  lib/avo/base_action.rb
  lib/avo/fields/base_field.rb
  spec/dummy/app/avo/actions/toggle_inactive.rb
Labels: fix
