Repository avo-hq/avo, pull requests merged in 2024-02, with the labels that each got.

#2446 chore: new dashboard colors
  lib/avo/configuration/branding.rb
  scripts/export-tailwind-safelist.js
Labels: Chore

#2428 feature: override auto-generated data attributes
  app/components/avo/field_wrapper_component.rb
Labels: Feature

#2454 fix: fetch cards only when necessary
  lib/avo/base_resource.rb
Labels: Fix

#2436 fix: detach when using view *_fields api
  app/components/avo/index/resource_controls_component.rb
  app/components/avo/views/resource_index_component.rb
  spec/dummy/app/avo/resources/course.rb
  spec/features/avo/discreet_pagination_spec.rb
  spec/features/avo/fields_methods_for_views_spec.rb
Labels: Fix

#2459 fix: attach when using *_fields API
  app/views/avo/associations/new.html.erb
  spec/features/avo/fields_methods_for_views_spec.rb
Labels: Fix

#2466 fix: index destroy
  app/components/avo/index/resource_controls_component.rb
  app/controllers/avo/application_controller.rb
  spec/system/avo/app_spec.rb
Labels: Fix

#2462 fix: Trix field disable_attachments option unexpected behaviour
  lib/avo/fields/trix_field.rb
Labels: Fix

#2484 fix: tags with custom tailwind integration issue
  package.json
  yarn.lock
Labels: Fix

#2493 fix: actions hidden fields value not being passed
  app/components/avo/fields/hidden_field/edit_component.html.erb
Labels: Fix

#2500 fix: select_first_result_in_search selenium compatible
  lib/avo/test_helpers.rb
Labels: Fix

#2474 fix: Has one not persisting
  app/components/avo/views/resource_show_component.rb
  spec/system/has_one_persisting_spec.rb
Labels: Fix

#2505 fix: image in file field stretched
  app/components/avo/fields/common/files/view_type/grid_item_component.html.erb
  avo.gemspec
  spec/dummy/app/avo/resources/post.rb
Labels: Fix

#2507 refactor: remove dashboard path
  app/components/avo/sidebar_component.html.erb
Labels: Refactor

#2508 feature: load concerns to Avo's controllers & aid multitenancy
  RELEASE.MD
  app/views/avo/partials/_header.html.erb
  lib/avo.rb
  lib/avo/configuration.rb
  lib/avo/current.rb
  lib/generators/avo/templates/initializer/avo.tt
  spec/dummy/app/controllers/avo/switch_accounts_controller.rb
  spec/dummy/app/models/user.rb
  spec/dummy/config/routes.rb
Labels: Feature

#2488 fix: standard and dynamic filters work together
  app/components/avo/filters_component.rb
  app/helpers/avo/resources_helper.rb
  app/javascript/js/controllers/filter_controller.js
  lib/avo/concerns/filters_session_handler.rb
  lib/avo/filters/base_filter.rb
  spec/dummy/db/seeds.rb
  spec/rails_helper.rb
  spec/system/avo/filters/filters_spec.rb
Labels: Fix

#2509 fix: create and update when using `view.form?`
  lib/avo/view_inquirer.rb
Labels: Fix

#2489 Updated the default client authorization to nil
  lib/generators/avo/templates/initializer/avo.tt
Labels: Fix

#2521 fix: double download action
  app/helpers/avo/turbo_stream_actions_helper.rb
Labels: Fix

#2520 fix: remove duplicate create method
  app/controllers/avo/base_controller.rb
Labels: Fix

#2527 chore: pagy remove `keep_filters_panel_open` param
  lib/avo/concerns/pagination.rb
Labels: Chore

#2526 feature: Add `default_url_options` support
  app/controllers/avo/application_controller.rb
  lib/avo/configuration.rb
  spec/dummy/config/initializers/avo.rb
Labels: Feature

#2523 fix: resource on action handle
  app/controllers/avo/actions_controller.rb
Labels: Fix

#2465 chore: upgrade to Turbo 8
  app/components/avo/actions_component.html.erb
  app/components/avo/actions_component.rb
  app/components/avo/resource_component.rb
  app/controllers/avo/actions_controller.rb
  app/controllers/avo/base_controller.rb
  app/helpers/avo/turbo_stream_actions_helper.rb
  app/javascript/js/controllers/action_controller.js
  app/views/avo/actions/show.html.erb
  app/views/layouts/avo/application.html.erb
  lib/avo.rb
  lib/avo/base_action.rb
  lib/avo/configuration.rb
  lib/avo/fields/belongs_to_field.rb
  lib/avo/test_helpers.rb
  lib/generators/avo/templates/initializer/avo.tt
  package.json
  spec/dummy/app/avo/actions/city/pre_update.rb
  spec/dummy/app/avo/resources/city.rb
  spec/dummy/config/locales/avo.es.yml
  spec/support/wait_for_loaded.rb
  spec/system/avo/sign_out_dropdown_spec.rb
  yarn.lock
Labels: Chore

#2528 fix: avo:update task
  lib/tasks/avo_tasks.rake
Labels: Fix

#2522 feature: action name as proc
  lib/avo/base_action.rb
  spec/dummy/app/avo/actions/sub/dummy_action.rb
  spec/dummy/app/avo/resources/city.rb
  spec/system/avo/actions_spec.rb
Labels: Feature

#2537 fix: rename instantclick to instant_click
  app/views/layouts/avo/application.html.erb
  lib/avo/configuration.rb
  lib/generators/avo/templates/initializer/avo.tt
Labels: Fix

#2531 fix: Update error message in MissingResourceError class
  lib/avo.rb
Labels: Fix
