Repository avo-hq/avo, pull requests merged in 2024-06, with the labels that each got.

#2827 Use correct policy class in search controller
  app/controllers/avo/search_controller.rb
Labels: Needs backport

#2838 fix: Add default icon for action list
  app/components/avo/actions_component.rb
  lib/avo/resources/controls/actions_list.rb
Labels: Fix

#2855 fix: set_locale param not setting the locale properly
  app/components/avo/divider_component.html.erb
  app/controllers/avo/application_controller.rb
  app/controllers/avo/base_controller.rb
  lib/avo/configuration.rb
  spec/dummy/app/avo/resources/project.rb
  spec/dummy/config/initializers/avo.rb
  spec/features/action_icon_and_divider_spec.rb
  spec/features/avo/divider_spec.rb
Labels: Fix

#2862 fix: remove client-side validation on action forms
  app/views/avo/actions/show.html.erb
  spec/system/avo/tabs_spec.rb
Labels: Fix

#2874 feature: add meta to field
  lib/avo/fields/base_field.rb
  spec/dummy/app/avo/resources/event.rb
  spec/features/avo/fields_meta_spec.rb
Labels: Feature

#2873 fix: wrong for_attribute selection
  app/controllers/avo/application_controller.rb
  app/controllers/avo/associations_controller.rb
Labels: Fix

#2875 fix: associations for_attribute detach
  app/controllers/avo/associations_controller.rb
Labels: Fix

#2876 feature: extend `update_using` on tags
  lib/avo/fields/base_field.rb
  lib/avo/fields/tags_field.rb
Labels: Feature, Fix

#2861 fix: generators can run without prior migrations
  lib/generators/avo/all_resources_generator.rb
  lib/generators/avo/install_generator.rb
  lib/generators/avo/resource_generator.rb
Labels: Fix

#2882 fix: resource generator db check
  lib/generators/avo/resource_generator.rb
Labels: Fix

#2897 chore: fix date flaky test
  spec/system/avo/date_time_fields/date_spec.rb
Labels: Chore, Fix

#2888 fix: normalize tag labels
  app/components/avo/fields/concerns/item_labels.rb
  app/components/avo/fields/tags_field/edit_component.html.erb
  lib/avo/fields/tags_field.rb
  spec/dummy/app/avo/resources/course.rb
  spec/dummy/app/models/course.rb
  spec/system/avo/tags_spec.rb
Labels: Fix

#2896 fix: go back button after changing tabs
  app/javascript/js/controllers/tabs_controller.js
Labels: Fix

#2898 Add search_results_count to configuration
  app/controllers/avo/search_controller.rb
  lib/avo/configuration.rb
  lib/generators/avo/templates/initializer/avo.tt
  spec/dummy/config/initializers/avo.rb
Labels: Feature

#2906 chore: add CSV dep
  Gemfile
  Gemfile.lock
  app/views/layouts/avo/application.html.erb
Labels: Chore

#2907 refactor: confirm modal
  app/views/avo/partials/_confirm_dialog.html.erb
Labels: Refactor

#2902 fix: missing translations
  app/components/avo/fields/files_field/index_component.html.erb
  app/components/avo/fields/files_field/index_component.rb
  app/components/avo/filters_component.html.erb
  lib/generators/avo/templates/locales/avo.ar.yml
  lib/generators/avo/templates/locales/avo.en.yml
  lib/generators/avo/templates/locales/avo.es.yml
  lib/generators/avo/templates/locales/avo.fr.yml
  lib/generators/avo/templates/locales/avo.ja.yml
  lib/generators/avo/templates/locales/avo.nb.yml
  lib/generators/avo/templates/locales/avo.nn.yml
  lib/generators/avo/templates/locales/avo.pt-BR.yml
  lib/generators/avo/templates/locales/avo.pt.yml
  lib/generators/avo/templates/locales/avo.ro.yml
  lib/generators/avo/templates/locales/avo.tr.yml
  spec/dummy/config/locales/avo.en.yml
Labels: Fix

#2910 fix: code mirror does not disconnect properly
  app/javascript/js/controllers/fields/code_field_controller.js
Labels: Fix

#2911 refactor: preview field tweaks
  app/components/avo/field_wrapper_component.html.erb
  app/components/avo/field_wrapper_component.rb
  app/views/avo/base/preview.html.erb
Labels: Chore

#2915 test: fix bad validation test
  Appraisals
  RELEASE.MD
  gemfiles/rails_6.1_ruby_3.1.4.gemfile
  gemfiles/rails_6.1_ruby_3.1.4.gemfile.lock
  gemfiles/rails_6.1_ruby_3.2.2.gemfile
  gemfiles/rails_6.1_ruby_3.2.2.gemfile.lock
  gemfiles/rails_6.1_ruby_3.3.0.gemfile
  gemfiles/rails_6.1_ruby_3.3.0.gemfile.lock
  gemfiles/rails_7.1_ruby_3.1.4.gemfile
  gemfiles/rails_7.1_ruby_3.1.4.gemfile.lock
  gemfiles/rails_7.1_ruby_3.2.2.gemfile
  gemfiles/rails_7.1_ruby_3.2.2.gemfile.lock
  gemfiles/rails_7.1_ruby_3.3.0.gemfile
  gemfiles/rails_7.1_ruby_3.3.0.gemfile.lock
  gemfiles/rails_8.0_ruby_3.1.4.gemfile
  gemfiles/rails_8.0_ruby_3.1.4.gemfile.lock
  gemfiles/rails_8.0_ruby_3.2.2.gemfile
  gemfiles/rails_8.0_ruby_3.2.2.gemfile.lock
  gemfiles/rails_8.0_ruby_3.3.0.gemfile
  gemfiles/rails_8.0_ruby_3.3.0.gemfile.lock
  spec/system/avo/tags_spec.rb
Labels: test

#2912 chore: update appraisals and gemfiles - remove ruby 3.2
  .github/workflows/feature-tests.yml
  .github/workflows/release.yml-old
  .github/workflows/system-tests.yml
  .github/workflows/undercover.yml
  Appraisals
  gemfiles/rails_6.1_ruby_3.1.4.gemfile
  gemfiles/rails_6.1_ruby_3.1.4.gemfile.lock
  gemfiles/rails_6.1_ruby_3.2.2.gemfile
  gemfiles/rails_6.1_ruby_3.2.2.gemfile.lock
  gemfiles/rails_6.1_ruby_3.3.0.gemfile
  gemfiles/rails_6.1_ruby_3.3.0.gemfile.lock
  gemfiles/rails_7.1_ruby_3.1.4.gemfile
  gemfiles/rails_7.1_ruby_3.1.4.gemfile.lock
  gemfiles/rails_7.1_ruby_3.2.2.gemfile
  gemfiles/rails_7.1_ruby_3.2.2.gemfile.lock
  gemfiles/rails_7.1_ruby_3.3.0.gemfile
  gemfiles/rails_7.1_ruby_3.3.0.gemfile.lock
  gemfiles/rails_8.0_ruby_3.1.4.gemfile.lock
  gemfiles/rails_8.0_ruby_3.2.2.gemfile
  gemfiles/rails_8.0_ruby_3.2.2.gemfile.lock
  gemfiles/rails_8.0_ruby_3.3.0.gemfile.lock
Labels: Chore
