Repository avo-hq/avo, pull requests merged in 2024-12, with the labels that each got.

#3467 fix: Rename Turbo Stream helpers to avoid clashes in user apps (#3462)
  app/controllers/avo/actions_controller.rb
  app/controllers/avo/associations_controller.rb
  app/controllers/avo/base_controller.rb
  app/helpers/avo/turbo_stream_actions_helper.rb
  spec/helpers/avo/turbo_stream_actions_helper_spec.rb
Labels: Fix

#3428 feature: summarizable associations
  app/controllers/avo/charts_controller.rb
  app/views/avo/partials/_table_header.html.erb
  spec/features/avo/field_summarizing_spec.rb
Labels: Feature

#3477 chore: clean unused component type specs
  spec/components/avo/actions_component_spec.rb
  spec/components/avo/blank_field_component_spec.rb
  spec/components/avo/button_component_spec.rb
  spec/components/avo/common/badge_viewer_component_spec.rb
  spec/components/avo/common/boolean_check_component_spec.rb
  spec/components/avo/common/boolean_group_component_spec.rb
  spec/components/avo/common/files_list_viewer_component_spec.rb
  spec/components/avo/common/gravatar_viewer_component_spec.rb
  spec/components/avo/common/heading_component_spec.rb
  spec/components/avo/common/key_value_component_spec.rb
  spec/components/avo/common/single_file_viewer_component_spec.rb
  spec/components/avo/common/status_viewer_component_spec.rb
  spec/components/avo/filters_component_spec.rb
  spec/components/avo/flash_alerts_component_spec.rb
  spec/components/avo/loading_component_spec.rb
  spec/components/avo/modal_component_spec.rb
  spec/components/avo/paginator_component_spec.rb
  spec/components/avo/panel_component_spec.rb
  spec/components/avo/profile_item_component_spec.rb
  spec/components/avo/referrer_params_component_spec.rb
  spec/components/avo/sidebar/section_component_spec.rb
  spec/components/avo/sidebar_heading_component_spec.rb
  spec/components/avo/sidebar_item_component_spec.rb
  spec/components/avo/tab_group_component_spec.rb
  spec/components/avo/tab_switcher_component_spec.rb
  spec/components/avo/views/resource_edit_component_spec.rb
  spec/components/avo/views/resource_index_component_spec.rb
Labels: Chore

#3461 Don't refer to more content button if always_true is set
  app/components/avo/fields/trix_field/show_component.html.erb
  app/javascript/js/controllers/trix_body_controller.js
Labels: Fix

#3442 Feature: Title and description for tabs
  app/components/avo/panel_component.html.erb
  app/components/avo/panel_component.rb
  app/components/avo/panel_header_component.html.erb
  app/components/avo/panel_header_component.rb
  app/components/avo/tab_group_component.html.erb
  lib/avo/resources/items/holder.rb
  lib/avo/resources/items/tab_group.rb
  spec/dummy/app/avo/resources/user.rb
  spec/system/avo/tabs_spec.rb
Labels: Enhancement

#3480 fix: svg cache
  lib/avo/svg_finder.rb
Labels: Fix

#3478 feature: grid item badge
  .github/ISSUE_TEMPLATE/bug_report.md
  app/components/avo/index/grid_item_component.html.erb
  app/components/avo/index/grid_item_component.rb
  safelist.txt
  scripts/export-tailwind-safelist.js
  spec/dummy/app/avo/resources/product.rb
Labels: Feature

#3483 fix: profile menu position
  app/components/avo/sidebar_profile_component.html.erb
Labels: Fix

#3490 fix: maintain `per_page` param in associations
  app/controllers/avo/base_controller.rb
  spec/system/avo/tabs_spec.rb
Labels: Fix

#3493 chore: pin rails dependency
  Gemfile
  Gemfile.lock
  app/controllers/avo/base_application_controller.rb
Labels: Chore

#3504 chore: fix appraisal
  .github/workflows/feature-tests.yml
  .github/workflows/system-tests.yml
  Appraisals
  Gemfile
  Gemfile.lock
  gemfiles/rails_6.1_ruby_3.1.4.gemfile.lock
  gemfiles/rails_6.1_ruby_3.3.0.gemfile.lock
  gemfiles/rails_7.1_ruby_3.1.4.gemfile.lock
  gemfiles/rails_7.1_ruby_3.3.0.gemfile.lock
  gemfiles/rails_7.2.0.beta2_ruby_3.1.4.gemfile
  gemfiles/rails_7.2.0.beta2_ruby_3.1.4.gemfile.lock
  gemfiles/rails_7.2.0.beta2_ruby_3.3.0.gemfile
  gemfiles/rails_7.2.0.beta2_ruby_3.3.0.gemfile.lock
  gemfiles/rails_8.0_ruby_3.1.4.gemfile
  gemfiles/rails_8.0_ruby_3.1.4.gemfile.lock
  gemfiles/rails_8.0_ruby_3.3.0.gemfile
  gemfiles/rails_8.0_ruby_3.3.0.gemfile.lock
Labels: Chore

#3507 fix: session key for pagination
  app/controllers/avo/associations_controller.rb
  app/controllers/avo/base_controller.rb
Labels: Fix

#3512 fix: row actions after back from browser
  app/helpers/avo/turbo_stream_actions_helper.rb
  app/views/layouts/avo/application.html.erb
Labels: Fix

#3502 enhancement: keep all referrer_params on go back link
  app/components/avo/resource_component.rb
Labels: Enhancement

#3515 fix: search_controller null error
  app/javascript/js/controllers/search_controller.js
Labels: Fix

#3520 fix: standalone action disabled and enabled classes
  app/components/avo/button_component.rb
  app/components/avo/resource_component.rb
Labels: Fix

#3519 fix: classes on field wrapper component
  app/components/avo/field_wrapper_component.rb
  app/components/avo/index/field_wrapper_component.rb
  app/components/avo/panel_component.rb
Labels: Fix

#3528 fix: Pagy::OverflowError
  lib/avo/concerns/pagination.rb
Labels: Fix

#3532 feature: cmd+return to submit form
  app/components/avo/views/resource_edit_component.html.erb
  app/javascript/js/controllers.js
  app/javascript/js/controllers/form_controller.js
  spec/system/avo/avo_cmd_return_to_submits_spec.rb
Labels: Feature

#3540 enhancement: persistence setting
  app/controllers/avo/associations_controller.rb
  lib/avo/concerns/filters_session_handler.rb
  lib/avo/configuration.rb
  lib/generators/avo/templates/initializer/avo.tt
  spec/dummy/config/initializers/avo.rb
  spec/system/avo/filters/persist_filters_spec.rb
  spec/system/avo/tabs_spec.rb
Labels: Enhancement

#3542 fix: `break-words` on show content
  app/components/avo/field_wrapper_component.html.erb
  spec/dummy/app/avo/resources/user.rb
  spec/dummy/app/models/user.rb
Labels: Fix

#3554 fix: don't submit form on autocomplete
  app/javascript/js/controllers/form_controller.js
Labels: Fix

#3559 fix: field wrapper overflow
  app/components/avo/field_wrapper_component.html.erb
Labels: Fix
