Repository avo-hq/avo, pull requests merged in 2024-03, with the labels that each got.

#2545 fix: double download with turbo_temporary
  app/controllers/avo/base_controller.rb
  app/helpers/avo/turbo_stream_actions_helper.rb
  app/views/avo/actions/show.html.erb
  spec/dummy/app/avo/actions/toggle_inactive.rb
  spec/dummy/app/avo/resources/user.rb
  spec/system/avo/actions_spec.rb
Labels: Fix

#2548 fix: header partial
  app/views/avo/partials/_header.html.erb
  spec/dummy/app/views/avo/partials/_header.html.erb
Labels: Fix

#2547 fix: visible block
  app/components/avo/actions_component.html.erb
  app/components/avo/actions_component.rb
  app/controllers/avo/base_controller.rb
Labels: Fix

#2561 fix: routes
  app/components/avo/sidebar_component.html.erb
Labels: Fix

#2570 chore: add plugins to the layout
  app/views/layouts/avo/application.html.erb
  lib/avo/plugin_manager.rb
Labels: Chore

#2565 refactor: conditional fill field
  lib/avo/fields/base_field.rb
Labels: Refactor

#2572 refactor: remove `extend_controllers_with` API
  lib/avo.rb
  lib/avo/configuration.rb
  lib/generators/avo/templates/initializer/avo.tt
  spec/dummy/config/initializers/avo.rb
Labels: Refactor

#2574 Feature: reorder by drag and drop
  app/components/avo/index/grid_item_component.html.erb
  app/components/avo/index/grid_item_component.rb
  app/components/avo/index/resource_controls_component.html.erb
  app/components/avo/index/resource_controls_component.rb
  app/components/avo/index/resource_grid_component.html.erb
  app/components/avo/index/resource_grid_component.rb
  app/components/avo/index/resource_map_component.rb
  app/components/avo/index/resource_table_component.html.erb
  app/components/avo/index/resource_table_component.rb
  app/components/avo/index/table_row_component.html.erb
  app/components/avo/index/table_row_component.rb
  app/components/avo/resource_component.rb
  config/cable.yml
  lib/avo/concerns/can_reorder_items.rb
  lib/avo/concerns/checks_assoc_authorization.rb
  safelist.txt
  scripts/export-tailwind-safelist.js
Labels: Feature

#2502 feature: add Tiptap WYSIWYG field
  app/assets/stylesheets/avo.base.css
  app/assets/stylesheets/css/fields/tiptap.css
  app/assets/svgs/editor-bold.svg
  app/assets/svgs/editor-italic.svg
  app/assets/svgs/editor-link.svg
  app/assets/svgs/editor-list.svg
  app/assets/svgs/editor-ordered-list.svg
  app/assets/svgs/editor-strike.svg
  app/assets/svgs/editor-underline.svg
  app/components/avo/fields/tiptap_field/edit_component.html.erb
  app/components/avo/fields/tiptap_field/edit_component.rb
  app/components/avo/fields/tiptap_field/show_component.html.erb
  app/components/avo/fields/tiptap_field/show_component.rb
  app/javascript/js/controllers.js
  app/javascript/js/controllers/fields/tiptap_field_controller.js
  lib/avo/fields/tiptap_field.rb
  package.json
  spec/dummy/app/avo/resources/product.rb
  spec/system/avo/tiptap_field_spec.rb
  yarn.lock
Labels: Feature

#2394 Enable showing distribution on columns on index page
  app/components/avo/loading_component.html.erb
  app/controllers/avo/charts_controller.rb
  app/helpers/avo/application_helper.rb
  app/views/avo/partials/_table_header.html.erb
  app/views/avo/partials/distribution_chart.html.erb
  app/views/layouts/avo/blank.html.erb
  config/routes.rb
  lib/avo/fields/base_field.rb
  safelist.txt
  scripts/export-tailwind-safelist.js
  spec/dummy/app/avo/resources/project.rb
  spec/features/avo/field_sorting_spec.rb
  spec/features/avo/field_summarizing_spec.rb
  spec/helpers/avo/application_helper_spec.rb
Labels: Feature

#2582 Fix: Support for Numeric title search
  app/controllers/avo/search_controller.rb
Labels: Fix

#2590 chore: add missing breadcrumb
  app/controllers/avo/base_controller.rb
Labels: Chore

#2585 Hide search input when avo_search? policy is not defined
  app/components/avo/views/resource_index_component.rb
Labels: Fix

#2579 fix: ensure Account is an ActiveRecord model before generating Avo resource
  lib/generators/avo/install_generator.rb
Labels: Fix

#2598 fix: multiple word resources bad cache hash
  lib/avo/base_resource.rb
Labels: Fix

#2599 Fix/dnd visibility and associations
  app/components/avo/index/grid_item_component.html.erb
  app/components/avo/index/grid_item_component.rb
  app/components/avo/index/resource_controls_component.html.erb
  app/components/avo/index/resource_controls_component.rb
  app/components/avo/index/resource_grid_component.html.erb
  app/components/avo/index/resource_grid_component.rb
  app/components/avo/index/resource_table_component.html.erb
  app/components/avo/index/resource_table_component.rb
  app/components/avo/index/table_row_component.html.erb
  app/components/avo/index/table_row_component.rb
  app/components/avo/resource_component.rb
  lib/avo/concerns/can_reorder_items.rb
Labels: Fix

#2613 chore: update tags and fix styles
  app/assets/stylesheets/css/fields/tags.css
  app/components/avo/fields/tags_field/edit_component.html.erb
  package.json
  yarn.lock
Labels: Chore

#2611 fix: keep original view after run update or create actions
  app/controllers/avo/application_controller.rb
  spec/features/avo/controller_action_spec.rb
Labels: Fix

#2609 fix: search item title
  app/controllers/avo/search_controller.rb
Labels: Fix

#2623 fix: date_time fields timezone
  app/javascript/js/controllers/fields/date_field_controller.js
  lib/avo/fields/date_time_field.rb
  spec/system/avo/date_time_fields/timezone_spec.rb
Labels: Fix

#2610 fix: collect errors from record without exception
  app/controllers/avo/base_controller.rb
  spec/system/model_errors_spec.rb
Labels: Fix

#2641 fix: keep avo.custom.js template on build
  avo.gemspec
Labels: Fix

#2635 fix: search when link_to_child_resource
  app/controllers/avo/search_controller.rb
Labels: Fix
