Repository avo-hq/avo, pull requests merged in 2024-07, with the labels that each got.

#2925 fix: missing filter translations
  app/views/avo/base/_text_filter.html.erb
  config/i18n-tasks.yml
  lib/generators/avo/templates/locales/avo.ar.yml
  lib/generators/avo/templates/locales/avo.en.yml
  lib/generators/avo/templates/locales/avo.es.yml
  lib/generators/avo/templates/locales/avo.fr.yml
  lib/generators/avo/templates/locales/avo.ja.yml
  lib/generators/avo/templates/locales/avo.nb.yml
  lib/generators/avo/templates/locales/avo.nn.yml
  lib/generators/avo/templates/locales/avo.pt-BR.yml
  lib/generators/avo/templates/locales/avo.pt.yml
  lib/generators/avo/templates/locales/avo.ro.yml
  lib/generators/avo/templates/locales/avo.tr.yml
Labels: Fix

#2926 Change dummy photo service from unsplash to picsum
  spec/dummy/db/seeds.rb
Labels: Chore

#2722 feature: profile and cover photos
  .erb-lint_rubocop.yml
  .github/ISSUE_TEMPLATE/config.yml
  app/components/avo/cover_photo_component.html.erb
  app/components/avo/cover_photo_component.rb
  app/components/avo/items/panel_component.rb
  app/components/avo/panel_component.html.erb
  app/components/avo/panel_component.rb
  app/components/avo/panel_name_component.html.erb
  app/components/avo/profile_photo_component.html.erb
  app/components/avo/profile_photo_component.rb
  app/components/avo/views/resource_index_component.html.erb
  lib/avo/base_resource.rb
  lib/avo/concerns/has_cover_photo.rb
  lib/avo/concerns/has_profile_photo.rb
  lib/avo/configuration/branding.rb
  lib/avo/cover_photo.rb
  lib/avo/photo_object.rb
  lib/avo/profile_photo.rb
  lib/avo/view_inquirer.rb
  spec/components/avo/cover_photo_component_spec.rb
  spec/dummy/app/avo/resources/event.rb
  spec/dummy/app/avo/resources/store.rb
  spec/dummy/app/avo/resources/team.rb
  spec/dummy/app/models/event.rb
  spec/dummy/db/seed_files/dummy-image.jpg
  spec/features/avo/app_spec.rb
  spec/features/avo/cover_profile_photos_spec.rb
  tailwind.preset.js
Labels: Feature, Needs Tests

#2928 fix: cover photo visible_on broken
  lib/avo/photo_object.rb
  spec/dummy/app/avo/resources/event.rb
Labels: Fix

#2929 fix: mobile pagination style
  app/assets/stylesheets/css/pagination.css
Labels: Fix, Style

#2931 feature: hide empty menu groups and sections
  app/components/avo/sidebar/base_item_component.rb
Labels: Feature

#2933 fix: apply `edit_{association}?` policy
  app/components/avo/resource_component.rb
Labels: Fix

#2932 fix: tags delimiters
  app/javascript/js/controllers/fields/tags_field_controller.js
  lib/avo/fields/tags_field.rb
Labels: Fix

#2934 feature: apply target resource policy on belongs_to field create new link
  app/components/avo/fields/belongs_to_field/edit_component.html.erb
  lib/avo/fields/belongs_to_field.rb
Labels: Feature

#2953 chore: update readme
  README.md
Labels: Chore

#2954 performance: perf optimizations
  README.md
  app/components/avo/fields/common/files/view_type/grid_item_component.html.erb
  app/components/avo/index/grid_cover_empty_state_component.html.erb
  app/components/avo/index/grid_item_component.rb
  lib/avo/base_resource.rb
  lib/avo/fields/base_field.rb
Labels: Performance

#2941 feature: extra map markers
  app/components/avo/index/resource_map_component.rb
  spec/dummy/app/avo/resources/city.rb
Labels: Feature

#2952 Feature: alias close_modal action response to do_nothing
  lib/avo/base_action.rb
  spec/dummy/app/avo/actions/test/do_nothing.rb
  spec/dummy/app/avo/resources/user.rb
  spec/system/avo/actions_spec.rb
Labels: Feature

#2958 fix: trix and action text improvements
  app/components/avo/fields/trix_field/edit_component.html.erb
Labels: Fix

#2963 chore: rails 7.1 warning
  lib/avo.rb
Labels: Chore

#2956 feature: add attachments to record
  app/controllers/avo/base_controller.rb
  lib/avo/base_resource.rb
  lib/generators/avo/templates/resource/resource.tt
  spec/dummy/app/avo/resources/post.rb
  spec/dummy/app/avo/resources/project.rb
  spec/dummy/app/avo/resources/user.rb
Labels: Feature, Needs Tests

#2796 feature: allow actions to render turbo streams
  app/controllers/avo/actions_controller.rb
  lib/avo/base_action.rb
  spec/dummy/app/avo/actions/test/close_modal.rb
  spec/system/avo/actions_spec.rb
Labels: Feature

#2977 fix: debug_controller syntax error
  app/controllers/avo/debug_controller.rb
Labels: Fix

#2986 Fix margin for index row controls
  app/components/avo/index/table_row_component.html.erb
Labels: Fix

#2968 Render action controls without adding to actions method
  app/components/avo/resource_component.rb
Labels: Needs Tests

#2997 [#2996] - Change boolean field to show dash when null
  app/components/avo/fields/boolean_field/index_component.html.erb
  app/components/avo/fields/boolean_field/show_component.html.erb
  spec/system/avo/boolean_field_spec.rb
Labels: Fix

#2989 feature: add visible option to panels
  lib/avo/resources/items/item_group.rb
  spec/features/avo/tabs_panels_and_sidebar_visibility_spec.rb
Labels: Feature

#3022 Add comment and lint
  spec/dummy/app/models/user.rb
Labels: Fix

#2998 refactor: Restructure Avo::BaseResource for user customization
  lib/avo/base_resource.rb
  lib/avo/resources/base.rb
Labels: Feature

#2985 fix: boolean group field broken with setters
  README.md
  app/components/avo/fields/boolean_group_field/edit_component.rb
  app/components/avo/fields/common/boolean_group_component.html.erb
  lib/avo/fields/boolean_group_field.rb
  lib/avo/licensing/request.rb
  public/avo-assets/logo-on-white.png
  spec/dummy/app/avo/resources/user.rb
  spec/dummy/app/models/user.rb
  spec/system/avo/boolean_group_field_spec.rb
Labels: Fix, Needs Tests

#3016 fix: uninitialized constant Net::HTTP error
  lib/avo.rb
Labels: Fix

#3028 chore: fix tests for #2985
  spec/system/avo/tabs_spec.rb
Labels: Chore

#3017 feature: add visible option to tab
  lib/avo/resources/items/tab.rb
  spec/features/avo/tabs_panels_and_sidebar_visibility_spec.rb
Labels: Feature

#3018 feature: add `default_sort_column` configuration option
  app/controllers/avo/base_controller.rb
  lib/avo/resources/base.rb
  spec/dummy/app/avo/resources/course.rb
  spec/features/avo/default_sort_column_spec.rb
Labels: Feature

#3027 fix: assets outputted multiple times
  app/components/avo/turbo_frame_wrapper_component.html.erb
  lib/avo/asset_manager.rb
  lib/generators/avo/eject_generator.rb
Labels: Fix

#3032 fix: model assignment
  lib/avo/fields/date_time_field.rb
  lib/avo/fields/time_field.rb
Labels: Fix

#3034 feature: custom search results
  app/controllers/avo/search_controller.rb
  spec/features/avo/search_custom_results_spec.rb
Labels: Feature

#3044 fix: boolean dash when false
  app/components/avo/field_wrapper_component.html.erb
  app/components/avo/field_wrapper_component.rb
  app/components/avo/fields/boolean_field/edit_component.html.erb
  app/components/avo/index/field_wrapper_component.html.erb
  app/components/avo/index/field_wrapper_component.rb
Labels: Fix

#3041 Fix: css based solution for sidebar without js dependency
  app/assets/stylesheets/css/sidebar.css
  app/components/avo/sidebar_component.html.erb
  app/javascript/js/controllers/sidebar_controller.js
  app/views/avo/partials/_navbar.html.erb
Labels: Fix

#3037 fix: tiptap multiple versions of prosemirror-model were loaded
  package.json
  yarn.lock
Labels: dependencies, Fix

#3046 pagy v9 compatibility, backwards compatible
  app/components/avo/paginator_component.rb
  config/initializers/pagy.rb
  lib/avo/concerns/pagination.rb
Labels: Fix

#3042 fix: exclude rails 7.1 version error from production
  app/views/avo/partials/_custom_tools_alert.html.erb
  lib/avo.rb
  lib/avo/error_manager.rb
  spec/dummy/app/avo/resource_tools/team_membership_tool_playground.rb
  spec/dummy/app/avo/resources/membership.rb
Labels: Fix

#3033 refactor: rename `model` to `record` in `fill_field` methods
  lib/avo/fields/belongs_to_field.rb
  lib/avo/fields/date_time_field.rb
  lib/avo/fields/files_field.rb
  lib/avo/fields/has_one_field.rb
  lib/avo/fields/key_value_field.rb
  lib/avo/fields/location_field.rb
  lib/avo/fields/time_field.rb
Labels: Refactor

#3050 fix: check for pagy version
  app/components/avo/paginator_component.rb
  config/initializers/pagy.rb
Labels: Fix

#3051 fix: search
  app/controllers/avo/search_controller.rb
Labels: Fix

#3002 fix: errors when attaching
  app/controllers/avo/associations_controller.rb
  app/controllers/avo/base_controller.rb
  spec/dummy/app/models/team_membership.rb
  spec/dummy/app/models/user.rb
  spec/system/avo/attach_fail_spec.rb
  spec/system/avo/tabs_spec.rb
Labels: Fix

#3067 fix: sign_out test
  spec/system/avo/sign_out_dropdown_spec.rb
Labels: Fix

#3066 performance: don't fetch fields on action's initialization
  app/controllers/avo/actions_controller.rb
  lib/avo/base_action.rb
  spec/dummy/app/avo/actions/sub/dummy_action.rb
  spec/system/avo/actions_spec.rb
Labels: Performance

#3031 add visible option for tabs
  lib/avo/resources/items/tab_group.rb
  spec/dummy/app/avo/resources/fish.rb
  spec/features/avo/tabs_panels_and_sidebar_visibility_spec.rb
Labels: Feature

#2965 Feature: Add optional confirmation on save
  app/components/avo/button_component.rb
  app/components/avo/resource_component.rb
  app/javascript/js/controllers/loading_button_controller.js
  lib/avo/resources/base.rb
  spec/dummy/app/avo/resources/store.rb
  spec/features/avo/confirm_on_save_spec.rb
Labels: Feature

#3015 Fix: Always display persisted image in the edit view
  app/components/avo/fields/common/files/view_type/grid_item_component.html.erb
  lib/avo/fields/file_field.rb
  spec/dummy/db/seed_files/dummy-music-two.mp3
  spec/dummy/db/seed_files/dummy-music.mp3
  spec/system/avo/display_persisted_attachment_spec.rb
Labels: Fix

#3076 performance: use `@reflection` ivar on associations controller
  app/controllers/avo/associations_controller.rb
Labels: Performance
