Repository avo-hq/avo, pull requests merged in 2024-01, with the labels that each got.

#2316 fix: remove status field defaults and fix the neutral state
  app/controllers/avo/application_controller.rb
  lib/avo/fields/status_field.rb
  tailwind.preset.js
Labels: Fix

#2314 feature: delegate missing to view_context
  lib/avo/execution_context.rb
  spec/dummy/app/avo/resources/product.rb
Labels: Feature

#2319 chore: move scopes from pro to advanced
  app/components/avo/views/resource_index_component.rb
Labels: Chore

#2279 fix: invalid date_time
  app/components/avo/fields/has_many_field/show_component.html.erb
  app/components/avo/fields/has_many_field/show_component.rb
  app/components/avo/fields/has_one_field/show_component.html.erb
  app/components/avo/fields/has_one_field/show_component.rb
  app/javascript/js/controllers/fields/date_field_controller.js
  lib/avo/fields/concerns/frame_loading.rb
  spec/dummy/app/avo/resources/post.rb
  spec/dummy/app/avo/resources/user.rb
  spec/dummy/app/models/user.rb
  spec/system/avo/tabs_spec.rb
  spec/system/avo/test_helpers_spec.rb
Labels: Fix

#2320 fix: bad navbar display on firefox
  app/views/avo/partials/_logo.html.erb
  app/views/avo/partials/_navbar.html.erb
Labels: Fix

#2322 chore: add tailwindcss integration test
  .github/workflows/test-tailwindcss-integration.yml
Labels: Chore

#2325 chore: check tailwindcss integration with github repo
  .github/workflows/feature-tests.yml
  .github/workflows/system-tests.yml
  .github/workflows/test-tailwindcss-integration.yml
  lib/generators/avo/templates/tailwindcss/avo.tailwind.css
  lib/tasks/avo_tasks.rake
  spec/dummy/config/application.rb
  tailwind.preset.js
Labels: Chore

#2269 fix: actions download
  app/controllers/avo/actions_controller.rb
  app/controllers/avo/base_controller.rb
  app/helpers/avo/turbo_stream_actions_helper.rb
  app/javascript/js/controllers/modal_controller.js
  app/javascript/js/custom-stream-actions.js
  app/views/avo/actions/show.html.erb
  app/views/avo/partials/_flash_alerts.turbo_stream.erb
  lib/avo/base_action.rb
  package.json
  spec/dummy/app/avo/actions/download_file.rb
  spec/dummy/app/avo/actions/export_csv.rb
  yarn.lock
Labels: Fix

#2332 feature: better sidebar scroll positioning
  .github/PULL_REQUEST_TEMPLATE.md
  app/javascript/avo.base.js
  app/javascript/js/application.js
  app/views/avo/partials/_javascript.html.erb
  spec/support/wait_for_loaded.rb
  spec/system/avo/key_value_field/key_value_field_spec.rb
Labels: Feature

#2362 Set z-index for navbar to the highest value, equal only to flash alerts
  app/views/avo/partials/_navbar.html.erb
Labels: Fix

#2369 feature: tags field in the Community tier
  .github/workflows/feature-tests.yml
  .github/workflows/system-tests.yml
  Appraisals
  app/assets/stylesheets/css/fields/tags.css
  app/components/avo/fields/tags_field/edit_component.html.erb
  app/components/avo/fields/tags_field/edit_component.rb
  app/components/avo/fields/tags_field/index_component.html.erb
  app/components/avo/fields/tags_field/index_component.rb
  app/components/avo/fields/tags_field/show_component.html.erb
  app/components/avo/fields/tags_field/show_component.rb
  app/components/avo/fields/tags_field/tag_component.html.erb
  app/components/avo/fields/tags_field/tag_component.rb
  app/javascript/js/controllers.js
  app/javascript/js/controllers/fields/tags_field_controller.js
  gemfiles/rails_7.0_ruby_3.1.4.gemfile
  gemfiles/rails_7.0_ruby_3.1.4.gemfile.lock
  gemfiles/rails_7.0_ruby_3.2.2.gemfile
  gemfiles/rails_7.0_ruby_3.2.2.gemfile.lock
  gemfiles/rails_7.0_ruby_3.3.0.gemfile
  gemfiles/rails_7.0_ruby_3.3.0.gemfile.lock
  lib/avo/fields/tags_field.rb
  lib/avo/test_helpers.rb
  spec/dummy/app/avo/actions/toggle_inactive.rb
  spec/dummy/app/avo/resources/course.rb
  spec/dummy/app/avo/resources/post.rb
  spec/dummy/app/controllers/avo/courses_controller.rb
  spec/dummy/app/controllers/avo/users_controller.rb
  spec/support/wait_for_loaded.rb
  spec/system/avo/tags_spec.rb
  spec/system/avo/test_helpers_spec.rb
Labels: Chore

#2323 feature: remove all scope ( V2 )
  app/components/avo/views/resource_index_component.rb
  lib/avo/base_resource.rb
  lib/avo/loaders/scopes_loader.rb
Labels: Feature

#2373 chore: bring back appraisals file
  Appraisals
Labels: Chore

#2382 security: v2 CVE-2024-22191
  app/javascript/js/controllers/fields/key_value_controller.js
  package.json
  yarn.lock
Labels: Chore, Security

#2397 fix: return valid attributes for html options
  lib/avo/fields/concerns/has_html_attributes.rb
  lib/avo/html/builder.rb
  lib/tasks/avo_tasks.rake
  scripts/export-tailwind-safelist.js
  spec/dummy/app/avo/resources/project.rb
  spec/dummy/config/environments/test.rb
Labels: Fix

#2398 fix: actions download
  app/controllers/avo/actions_controller.rb
  app/javascript/js/custom-stream-actions.js
  spec/dummy/app/avo/actions/download_file.rb
  spec/dummy/dummy-file.pdf
  spec/system/avo/actions_spec.rb
Labels: Fix

#2410 fix: search highlight
  app/javascript/js/controllers/search_controller.js
Labels: Fix

#2419 refactor: tool-manager-tweaks
  lib/avo/tools/tool_manager.rb
  spec/dummy/app/avo/actions/export_csv.rb
Labels: Refactor

#2420 refactor: sidebar remember scroll move to controller
  app/javascript/avo.base.js
  app/javascript/js/controllers/sidebar_controller.js
Labels: Refactor

#2422 fix: double defined constanta in CI
  lib/tasks/tailwindcss_rails.rake
Labels: Fix

#2415 fix: destroy when using forms and display fields API
  Gemfile.lock
  app/components/avo/index/resource_controls_component.rb
  app/controllers/avo/application_controller.rb
  spec/dummy/app/avo/resources/course.rb
  spec/features/avo/fields_methods_for_views_spec.rb
Labels: Fix

#2423 fix: searchable belongs_to field keep html tags on selected option
  app/javascript/js/controllers/search_controller.js
Labels: Fix

#2432 feature: expose resource in resource tools intializers
  lib/avo/base_resource_tool.rb
  lib/avo/concerns/has_items.rb
  lib/avo/resources/items/holder.rb
Labels: Feature
