Repository avo-hq/avo, pull requests merged in 2024-04, with the labels that each got.

#2657 feature: callable `default_view_type`
  app/controllers/avo/base_controller.rb
  spec/dummy/app/avo/resources/post.rb
Labels: Feature

#2659 fix: hydrate resource with record when detect_fields on new
  app/controllers/avo/base_controller.rb
Labels: Fix

#2656 fix: resource search
  app/components/avo/views/resource_index_component.rb
Labels: Fix

#2662 fix: select boolean false value
  app/components/avo/fields/select_field/show_component.html.erb
Labels: Fix

#2542 feature: prevent overriding internal controllers
  lib/generators/avo/concerns/override_controller.rb
  lib/generators/avo/controller_generator.rb
  lib/generators/avo/resource_generator.rb
  lib/generators/rails/avo_resource_generator.rb
Labels: Feature

#2645 Support composite primary keys on show, edit, update and destroy actions
  app/controllers/avo/application_controller.rb
Labels: Feature

#2669 refactor: tweaks and money field preparations
  Gemfile
  Gemfile.lock
  gemfiles/rails_6.1_ruby_3.1.4.gemfile
  gemfiles/rails_6.1_ruby_3.1.4.gemfile.lock
  gemfiles/rails_6.1_ruby_3.2.2.gemfile
  gemfiles/rails_6.1_ruby_3.2.2.gemfile.lock
  gemfiles/rails_6.1_ruby_3.3.0.gemfile
  gemfiles/rails_6.1_ruby_3.3.0.gemfile.lock
  gemfiles/rails_7.1_ruby_3.1.4.gemfile
  gemfiles/rails_7.1_ruby_3.1.4.gemfile.lock
  gemfiles/rails_7.1_ruby_3.2.2.gemfile
  gemfiles/rails_7.1_ruby_3.2.2.gemfile.lock
  gemfiles/rails_7.1_ruby_3.3.0.gemfile
  gemfiles/rails_7.1_ruby_3.3.0.gemfile.lock
  lib/avo/concerns/has_items.rb
  lib/avo/fields/base_field.rb
  lib/avo/fields/concerns/use_view_components.rb
  lib/avo/fields/field_manager.rb
  lib/avo/fields/has_base_field.rb
  spec/dummy/app/avo/resources/product.rb
  spec/dummy/app/helpers/application_helper.rb
  spec/dummy/app/models/product.rb
  spec/dummy/app/views/avo/partials/_footer.html.erb
  spec/dummy/config/initializers/avo.rb
  spec/dummy/config/initializers/money.rb
  spec/dummy/db/migrate/20240322003900_change_price_in_products.rb
Labels: Refactor

#2667 Layout tweaks to Resource header area
  app/components/avo/panel_component.html.erb
Labels: Fix, Front end

#2652 fix: preserve page when go back from resource show page (#1555)
  app/components/avo/resource_component.rb
  app/components/avo/views/resource_edit_component.rb
  app/components/avo/views/resource_show_component.rb
  lib/avo/concerns/request_methods.rb
  spec/components/avo/views/resource_show_component_spec.rb
Labels: Fix

#2682 chore: performance tweak on boolean group field and select field
  lib/avo/fields/boolean_group_field.rb
  lib/avo/fields/select_field.rb
Labels: Chore

#2583 feature: resource controls dynamic width
  app/components/avo/index/grid_item_component.html.erb
  app/components/avo/index/resource_controls_component.html.erb
  app/components/avo/index/table_row_component.html.erb
  app/views/avo/partials/_table_header.html.erb
Labels: Feature

#2639 fix: ActionText support for trix field
  app/components/avo/fields/trix_field/edit_component.html.erb
  app/components/avo/fields/trix_field/edit_component.rb
  app/controllers/avo/attachments_controller.rb
  app/javascript/js/controllers/fields/trix_field_controller.js
  lib/avo/fields/trix_field.rb
  spec/dummy/app/avo/resources/event.rb
Labels: Fix, Stale

#2684 chore: prepare for record_link field
  Gemfile
  Gemfile.lock
  spec/dummy/app/avo/resources/comment.rb
  spec/dummy/app/avo/resources/event.rb
  spec/dummy/app/models/event.rb
Labels: Chore

#2554 Autofocus first field
  app/components/avo/fields/area_field/edit_component.html.erb
  app/components/avo/fields/boolean_field/edit_component.html.erb
  app/components/avo/fields/code_field/edit_component.html.erb
  app/components/avo/fields/edit_component.rb
  app/components/avo/fields/external_image_field/edit_component.html.erb
  app/components/avo/fields/file_field/edit_component.html.erb
  app/components/avo/fields/files_field/edit_component.html.erb
  app/components/avo/fields/markdown_field/edit_component.html.erb
  app/components/avo/fields/number_field/edit_component.html.erb
  app/components/avo/fields/password_field/edit_component.html.erb
  app/components/avo/fields/progress_bar_field/edit_component.html.erb
  app/components/avo/fields/select_field/edit_component.html.erb
  app/components/avo/fields/status_field/edit_component.html.erb
  app/components/avo/fields/text_field/edit_component.html.erb
  app/components/avo/fields/textarea_field/edit_component.html.erb
  app/controllers/avo/actions_controller.rb
  app/views/avo/actions/show.html.erb
  spec/dummy/app/components/avo/fields/color_picker_field/edit_component.html.erb
Labels: Feature

#2694 fix: leaky global default_url_options
  app/controllers/avo/application_controller.rb
  spec/system/avo/reload_button_spec.rb
Labels: Fix

#2692 fix: actions layout
  app/controllers/avo/actions_controller.rb
  app/controllers/avo/application_controller.rb
  app/controllers/avo/associations_controller.rb
  spec/system/avo/reload_button_spec.rb
Labels: Fix

#2695 feature: add sidebar collapse animation
  app/components/avo/sidebar/base_item_component.rb
  app/components/avo/sidebar/group_component.html.erb
  app/components/avo/sidebar/section_component.html.erb
  app/javascript/js/controllers/menu_controller.js
Labels: Feature

#2690 fix: detach action record
  app/controllers/avo/associations_controller.rb
Labels: Fix

#2560 feature: `for_attribute` option for fields
  app/components/avo/base_component.rb
  app/components/avo/fields/has_one_field/show_component.rb
  app/components/avo/views/resource_index_component.rb
  app/controllers/avo/application_controller.rb
  app/controllers/avo/associations_controller.rb
  app/javascript/js/controllers/item_select_all_controller.js
  app/views/avo/associations/new.html.erb
  lib/avo/concerns/has_items.rb
  lib/avo/fields/base_field.rb
  lib/avo/fields/has_base_field.rb
  spec/dummy/app/avo/resources/fish.rb
  spec/dummy/app/avo/resources/project.rb
  spec/system/avo/for_attribute_spec.rb
Labels: Feature

#2549 fix: index header and rows visibility
  app/components/avo/index/resource_table_component.html.erb
  app/components/avo/index/resource_table_component.rb
  app/components/avo/index/table_row_component.html.erb
  app/components/avo/index/table_row_component.rb
  app/controllers/avo/base_controller.rb
  lib/avo/concerns/has_items.rb
  lib/avo/fields/base_field.rb
  spec/dummy/app/avo/resources/project.rb
Labels: Fix

#2700 performance: memoize a few things
  app/components/avo/resource_component.rb
  app/controllers/avo/base_controller.rb
  lib/avo/concerns/hydration.rb
  lib/avo/fields/belongs_to_field.rb
  lib/avo/resources/resource_manager.rb
Labels: Performance

#2663 Add disable_editing_values for key_value field
  app/javascript/js/controllers/fields/key_value_controller.js
  lib/avo/fields/key_value_field.rb
  spec/dummy/app/avo/resources/project.rb
  spec/system/avo/key_value_field/key_value_field_spec.rb
Labels: Bug, Enhancement

#2704 fix: bad animation for menu on reload
  app/javascript/js/controllers/menu_controller.js
Labels: Fix

#2705 chore: add record_link field to gemfile
  gemfiles/rails_6.1_ruby_3.1.4.gemfile
  gemfiles/rails_6.1_ruby_3.1.4.gemfile.lock
  gemfiles/rails_6.1_ruby_3.2.2.gemfile
  gemfiles/rails_6.1_ruby_3.2.2.gemfile.lock
  gemfiles/rails_6.1_ruby_3.3.0.gemfile
  gemfiles/rails_6.1_ruby_3.3.0.gemfile.lock
  gemfiles/rails_7.1_ruby_3.1.4.gemfile
  gemfiles/rails_7.1_ruby_3.1.4.gemfile.lock
  gemfiles/rails_7.1_ruby_3.2.2.gemfile
  gemfiles/rails_7.1_ruby_3.2.2.gemfile.lock
  gemfiles/rails_7.1_ruby_3.3.0.gemfile
  gemfiles/rails_7.1_ruby_3.3.0.gemfile.lock
Labels: Chore

#2712 fix: check proper dir for internal controller override
  lib/generators/avo/concerns/override_controller.rb
Labels: Fix

#2717 feature: configurable default pagination
  lib/avo/concerns/pagination.rb
  lib/avo/configuration.rb
  lib/generators/avo/templates/initializer/avo.tt
  spec/dummy/config/initializers/avo.rb
Labels: Feature

#2591 feature: linkable association titles
  app/components/avo/views/resource_index_component.html.erb
  app/components/avo/views/resource_index_component.rb
  lib/avo/base_resource.rb
  spec/dummy/app/avo/resources/team.rb
Labels: Feature, Stale

#2719 fix: eager load actions
  lib/avo.rb
Labels: Fix

#2726 fix: actions eager loader
  lib/avo.rb
Labels: Fix
