Repository avo-hq/avo, pull requests merged in 2024-08, with the labels that each got.

#3080 feature: popovers in action lists
  app/components/avo/actions_component.html.erb
  app/components/avo/actions_component.rb
  app/components/avo/resource_component.rb
  app/javascript/avo.base.js
Labels: Feature

#2919 Use literal properties for `ActionsComponent`
  app/components/avo/actions_component.html.erb
  app/components/avo/actions_component.rb
  app/components/avo/button_component.rb
Labels: Stale

#3084 chore: check if defined `ActiveRecord::ConnectionAdapters::PostgreSQLAdapter`
  spec/dummy/config/environments/test.rb
Labels: Chore

#3087 fix: MissingResourceError on polymorphic field
  lib/avo.rb
  lib/avo/fields/base_field.rb
Labels: Fix

#3088 feature: kanban boards (preparation)
  app/components/avo/fields/common/files/list_viewer_component.rb
  app/components/avo/paginator_component.html.erb
  app/components/avo/panel_component.html.erb
  app/views/avo/actions/show.html.erb
  app/views/layouts/avo/application.html.erb
  lib/avo.rb
  lib/generators/avo/templates/initializer/avo.tt
  lib/tasks/avo_tasks.rake
  spec/dummy/app/models/user.rb
  spec/dummy/config/initializers/avo.rb
  tailwind.preset.js
Labels: Feature

#3089 fix: menu test on `avo_warining_spec.rb`
  spec/dummy/config/initializers/avo.rb
Labels: Fix

#3090 fix: pagy 9 support
  Gemfile.lock
  app/components/avo/paginator_component.rb
  app/components/avo/views/resource_index_component.html.erb
  config/initializers/pagy.rb
  spec/system/avo/filters/filters_spec.rb
Labels: Fix

#3077 fix: base resource overriding
  app/avo/base_resource.rb
  lib/avo/engine.rb
  spec/features/avo/resource_extension_spec.rb
Labels: Fix

#3092 fix: panel component orientation
  app/components/avo/panel_component.html.erb
Labels: Fix

#2564 feature: full IDs obfuscation (friendly_id/hashids/prefixed_ids)
  Appraisals
  Gemfile
  Gemfile.lock
  app/components/avo/actions_component.html.erb
  app/components/avo/fields/belongs_to_field/edit_component.html.erb
  app/components/avo/fields/belongs_to_field/show_component.rb
  app/components/avo/fields/has_one_field/show_component.rb
  app/components/avo/index/resource_controls_component.rb
  app/components/avo/resource_component.rb
  app/components/avo/resource_sidebar_component.html.erb
  app/components/avo/views/resource_edit_component.html.erb
  app/components/avo/views/resource_show_component.html.erb
  app/controllers/avo/associations_controller.rb
  app/controllers/avo/search_controller.rb
  app/helpers/avo/application_helper.rb
  app/views/avo/base/close_modal_and_reload_field.turbo_stream.erb
  gemfiles/rails_6.1_ruby_3.1.4.gemfile
  gemfiles/rails_6.1_ruby_3.1.4.gemfile.lock
  gemfiles/rails_6.1_ruby_3.3.0.gemfile
  gemfiles/rails_6.1_ruby_3.3.0.gemfile.lock
  gemfiles/rails_7.1_ruby_3.1.4.gemfile
  gemfiles/rails_7.1_ruby_3.1.4.gemfile.lock
  gemfiles/rails_7.1_ruby_3.3.0.gemfile
  gemfiles/rails_7.1_ruby_3.3.0.gemfile.lock
  gemfiles/rails_7.2.0.beta2_ruby_3.1.4.gemfile
  gemfiles/rails_7.2.0.beta2_ruby_3.1.4.gemfile.lock
  gemfiles/rails_7.2.0.beta2_ruby_3.3.0.gemfile
  gemfiles/rails_7.2.0.beta2_ruby_3.3.0.gemfile.lock
  gemfiles/rails_8.0_ruby_3.1.4.gemfile
  gemfiles/rails_8.0_ruby_3.1.4.gemfile.lock
  gemfiles/rails_8.0_ruby_3.3.0.gemfile
  gemfiles/rails_8.0_ruby_3.3.0.gemfile.lock
  lib/avo/fields/belongs_to_field.rb
  lib/avo/fields/has_one_field.rb
  lib/avo/resources/base.rb
  spec/dummy/app/avo/resources/city.rb
  spec/dummy/app/models/city.rb
  spec/dummy/app/models/user.rb
  spec/dummy/app/views/avo/resource_tools/_fish_information.html.erb
  spec/features/avo/has_many_field_spec.rb
  spec/features/avo/record_passed_to_scope_spec.rb
  spec/features/avo/search_has_many_scope_spec.rb
  spec/system/avo/belongs_to_polymorphic_spec.rb
  spec/system/avo/create_via_belongs_to_spec.rb
Labels: Feature, Stale

#3093 fix: `set_record` when fetching `fields` on actions' `handle`
  app/components/avo/actions_component.rb
  app/controllers/avo/actions_controller.rb
  app/views/avo/actions/show.html.erb
  lib/avo/base_action.rb
Labels: Feature, Fix

#3100 fix: hide empty menu groups and sections
  app/components/avo/sidebar/base_item_component.rb
Labels: Fix

#3099 chore: gh actions' concurrency
  .github/workflows/codeql.yml
  .github/workflows/feature-tests.yml
  .github/workflows/i18n-tests.yml
  .github/workflows/lint.yml
  .github/workflows/system-tests.yml
  .github/workflows/test-tailwindcss-integration.yml
Labels: Chore

#3106 fix: Some cookies are misusing the recommended “SameSite“ attribute
  app/controllers/avo/application_controller.rb
  app/javascript/js/controllers/sidebar_controller.js
Labels: Fix

#3108 Chore: Test Sidebar
  spec/system/sidebar_spec.rb
Labels: Chore

#3096 Feature: Add back button to association pages
  app/components/avo/views/resource_index_component.rb
  lib/avo/concerns/has_controls.rb
  spec/features/avo/breadcrumbs_spec.rb
Labels: Feature

#3098 feature: informative development error when search misconfigured
  app/controllers/avo/search_controller.rb
  app/javascript/js/controllers/search_controller.js
Labels: Feature

#3110 performance: sym_link
  lib/tasks/avo_tasks.rake
Labels: Performance

#3097 fix: false positive on unpermitted parameters
  app/controllers/avo/actions_controller.rb
  app/controllers/avo/associations_controller.rb
  app/views/avo/home/failed_to_load.html.erb
  lib/avo/resources/base.rb
  spec/dummy/app/avo/resources/fish.rb
  spec/features/avo/controller_action_spec.rb
  spec/features/avo/custom_fields_in_resource_tools_spec.rb
  spec/rails_helper.rb
  spec/support/avo_helpers.rb
  spec/system/avo/create_via_belongs_to_spec.rb
  spec/system/avo/tags_spec.rb
Labels: Fix

#3117 fix: pagy 9 `data-turbo-frame`
  app/components/avo/paginator_component.html.erb
  app/components/avo/paginator_component.rb
  spec/system/avo/filters/filters_spec.rb
Labels: Fix

#3122 chore: update CI files and a few tweaks
  .github/pr-labeler.yml
  .github/release-drafter.yml
  Gemfile
  Gemfile.lock
  spec/dummy/config/initializers/amazing_print.rb
  spec/dummy/config/puma.rb
Labels: Chore

#3121 chore: change pagy default size to integer
  lib/avo/concerns/pagination.rb
  lib/generators/avo/templates/initializer/avo.tt
Labels: Chore

#3124 chore: appraisal amazing_print
  gemfiles/rails_6.1_ruby_3.1.4.gemfile
  gemfiles/rails_6.1_ruby_3.1.4.gemfile.lock
  gemfiles/rails_6.1_ruby_3.3.0.gemfile
  gemfiles/rails_6.1_ruby_3.3.0.gemfile.lock
  gemfiles/rails_7.1_ruby_3.1.4.gemfile
  gemfiles/rails_7.1_ruby_3.1.4.gemfile.lock
  gemfiles/rails_7.1_ruby_3.3.0.gemfile
  gemfiles/rails_7.1_ruby_3.3.0.gemfile.lock
  gemfiles/rails_7.2.0.beta2_ruby_3.1.4.gemfile
  gemfiles/rails_7.2.0.beta2_ruby_3.1.4.gemfile.lock
  gemfiles/rails_7.2.0.beta2_ruby_3.3.0.gemfile
  gemfiles/rails_7.2.0.beta2_ruby_3.3.0.gemfile.lock
  gemfiles/rails_8.0_ruby_3.1.4.gemfile
  gemfiles/rails_8.0_ruby_3.1.4.gemfile.lock
  gemfiles/rails_8.0_ruby_3.3.0.gemfile
  gemfiles/rails_8.0_ruby_3.3.0.gemfile.lock
Labels: Chore

#3127 chore: tweak tailwind variants
  tailwind.preset.js
Labels: Chore

#3128 refactor: add modal component overflow option
  app/components/avo/modal_component.html.erb
  app/components/avo/modal_component.rb
  spec/dummy/app/avo/resources/store.rb
  spec/dummy/app/avo/resources/team.rb
  spec/dummy/db/schema.rb
Labels: Refactor

#3130 fix: `avo:sym_link`
  lib/tasks/avo_tasks.rake
Labels: Fix

#3123 dx: information on global search
  app/controllers/avo/search_controller.rb
Labels: Developer Experience (DX)

#3144 fix: actions arguments
  app/components/avo/actions_component.rb
  spec/system/avo/actions_spec.rb
Labels: Fix

#3153 chore: drop dry-initializer dependency
  app/components/avo/profile_item_component.rb
  app/components/avo/sidebar/base_item_component.rb
  app/components/avo/sidebar/group_component.html.erb
  app/components/avo/sidebar/heading_component.rb
  app/components/avo/sidebar/section_component.html.erb
Labels: Chore

#3132 feature: date time filter
  app/javascript/js/controllers.js
  app/javascript/js/controllers/date_time_filter_controller.js
  app/views/avo/base/_date_time_filter.html.erb
  app/views/avo/base/_multiple_select_filter.html.erb
  lib/avo/filters/base_filter.rb
  lib/avo/filters/date_time_filter.rb
  lib/avo/filters/text_filter.rb
  lib/generators/avo/filter_generator.rb
  lib/generators/avo/templates/filters/date_time_filter.tt
  spec/dummy/app/avo/filters/birthday.rb
  spec/dummy/app/avo/filters/starting_at.rb
  spec/dummy/app/avo/resources/course.rb
  spec/dummy/app/avo/resources/user.rb
  spec/system/avo/filters/filters_spec.rb
Labels: Feature

#3156 feature: command+click opens url in a new tab
  app/javascript/js/controllers/table_row_controller.js
Labels: Feature

#3160 fix: temporary fix for turbo bug with lazy loading
  app/javascript/avo.base.js
Labels: Fix

#3177 refactor: better and more performant svg finder
  app/assets/stylesheets/css/fields/trix.css
  app/components/avo/actions_component.rb
  app/helpers/avo/application_helper.rb
  lib/avo/configuration.rb
  lib/avo/svg_finder.rb
Labels: Refactor

#3178 chore: prep for rhino field
  app/assets/config/avo_manifest.js
Labels: Chore

#3179 refactor: revert inline_svg optimization
  app/assets/config/avo_manifest.js
  app/helpers/avo/application_helper.rb
  lib/avo/svg_finder.rb
Labels: Refactor

#3176 feature: resource custom components
  app/components/avo/index/resource_grid_component.html.erb
  app/components/avo/index/resource_map_component.html.erb
  app/components/avo/index/resource_table_component.rb
  app/components/avo/index/table_row_component.rb
  app/components/avo/views/resource_index_component.html.erb
  app/controllers/avo/base_controller.rb
  lib/avo/resources/base.rb
  spec/components/avo/index/field_wrapper_component_spec.rb
  spec/components/avo/index/grid_item_component_spec.rb
  spec/components/avo/index/resource_grid_component_spec.rb
  spec/components/avo/index/resource_table_component_spec.rb
  spec/components/avo/index/table_row_component_spec.rb
  spec/dummy/app/components/avo/for_test/grid_item_component.html.erb
  spec/dummy/app/components/avo/for_test/grid_item_component.rb
  spec/dummy/app/components/avo/for_test/resource_edit_component.html.erb
  spec/dummy/app/components/avo/for_test/resource_edit_component.rb
  spec/dummy/app/components/avo/for_test/resource_index_component.html.erb
  spec/dummy/app/components/avo/for_test/resource_index_component.rb
  spec/dummy/app/components/avo/for_test/resource_map_component.html.erb
  spec/dummy/app/components/avo/for_test/resource_map_component.rb
  spec/dummy/app/components/avo/for_test/resource_new_component.html.erb
  spec/dummy/app/components/avo/for_test/resource_new_component.rb
  spec/dummy/app/components/avo/for_test/resource_show_component.html.erb
  spec/dummy/app/components/avo/for_test/resource_show_component.rb
  spec/dummy/app/components/avo/for_test/resource_table_component.html.erb
  spec/dummy/app/components/avo/for_test/resource_table_component.rb
  spec/dummy/app/components/avo/for_test/table_row_component.html.erb
  spec/dummy/app/components/avo/for_test/table_row_component.rb
  spec/features/avo/resource_custom_components_spec.rb
Labels: Feature

#3183 fix: paginator component turbo_frame
  app/components/avo/paginator_component.rb
  app/components/avo/views/resource_index_component.html.erb
Labels: Fix
