Repository avo-hq/avo, pull requests merged in 2024-10, with the labels that each got.

#3287 refactor: plugins reporting and versions hiding
  app/controllers/avo/application_controller.rb
  app/controllers/avo/debug_controller.rb
  app/controllers/avo/private_controller.rb
  app/views/avo/debug/status.html.erb
  app/views/avo/debug/status.text.erb
  app/views/layouts/avo/application.html.erb
  lib/avo/plugin.rb
  lib/avo/plugin_manager.rb
  lib/generators/avo/templates/initializer/avo.tt
Labels: Refactor

#3290 fix: undefined local variable or method `resource` for an instance of Avo::Index::TableRowComponent
  app/components/avo/index/table_row_component.rb
Labels: Fix

#3289 chore: update `view_component` to `3.15.1`
  Gemfile.lock
  gemfiles/rails_6.1_ruby_3.1.4.gemfile.lock
  gemfiles/rails_6.1_ruby_3.3.0.gemfile.lock
  gemfiles/rails_7.1_ruby_3.1.4.gemfile.lock
  gemfiles/rails_7.1_ruby_3.3.0.gemfile.lock
  gemfiles/rails_7.2.0.beta2_ruby_3.1.4.gemfile.lock
  gemfiles/rails_7.2.0.beta2_ruby_3.3.0.gemfile.lock
  gemfiles/rails_8.0_ruby_3.1.4.gemfile.lock
  gemfiles/rails_8.0_ruby_3.3.0.gemfile.lock
Labels: Chore

#3288 chore: remove unused methods
  lib/avo/plugin_manager.rb
Labels: Chore

#3295 fix: remove type from query
  app/components/avo/index/resource_table_component.rb
  app/components/avo/views/resource_index_component.rb
Labels: Fix

#3306 fix: tags filters closing on tag selection
  app/javascript/js/controllers/toggle_controller.js
Labels: Fix

#3310 feature: process search results
  app/controllers/avo/search_controller.rb
  lib/avo/resources/resource_manager.rb
Labels: Feature

#3309 feature: customizable first sorting option
  app/views/avo/partials/_table_header.html.erb
  lib/avo/configuration.rb
  lib/generators/avo/templates/initializer/avo.tt
  spec/features/avo/default_sort_column_and_direction_spec.rb
Labels: Feature, hacktoberfest, Needs Tests

#2703 feature: audit logs
  app/controllers/avo/actions_controller.rb
Labels: Feature, Stale exempt, Task, Enterprise

#3292 feature: implicit authorization
  app/controllers/avo/associations_controller.rb
  lib/avo/concerns/checks_assoc_authorization.rb
  lib/avo/configuration.rb
  lib/avo/fields/has_base_field.rb
  lib/generators/avo/templates/initializer/avo.tt
Labels: Feature

#3318 Add a comment to notice about security
  lib/generators/avo/tool_generator.rb
Labels: Chore

#3319 refactor: callable `disabled_features`
  lib/avo/configuration.rb
Labels: Refactor

#3323 Fix typographical errors from app directory
  CONTRIBUTING.MD
  Gemfile
  app/components/avo/fields/boolean_group_field/edit_component.rb
  app/components/avo/index/resource_controls_component.rb
  app/components/avo/resource_component.rb
  app/javascript/avo.base.js
  app/javascript/js/controllers/copy_to_clipboard_controller.js
  app/javascript/js/controllers/sidebar_controller.js
  lib/tasks/avo_tasks.rake
Labels: Refactor

#3331 chore: update `prop_initializer` dependency
  Gemfile.lock
  avo.gemspec
  gemfiles/rails_6.1_ruby_3.1.4.gemfile
  gemfiles/rails_6.1_ruby_3.1.4.gemfile.lock
  gemfiles/rails_6.1_ruby_3.3.0.gemfile
  gemfiles/rails_6.1_ruby_3.3.0.gemfile.lock
  gemfiles/rails_7.1_ruby_3.1.4.gemfile
  gemfiles/rails_7.1_ruby_3.1.4.gemfile.lock
  gemfiles/rails_7.1_ruby_3.3.0.gemfile
  gemfiles/rails_7.1_ruby_3.3.0.gemfile.lock
  gemfiles/rails_7.2.0.beta2_ruby_3.1.4.gemfile
  gemfiles/rails_7.2.0.beta2_ruby_3.1.4.gemfile.lock
  gemfiles/rails_7.2.0.beta2_ruby_3.3.0.gemfile
  gemfiles/rails_7.2.0.beta2_ruby_3.3.0.gemfile.lock
  gemfiles/rails_8.0_ruby_3.1.4.gemfile
  gemfiles/rails_8.0_ruby_3.1.4.gemfile.lock
  gemfiles/rails_8.0_ruby_3.3.0.gemfile
  gemfiles/rails_8.0_ruby_3.3.0.gemfile.lock
Labels: Chore

#3325 Made TestHelpers include methods from WaitForLoaded
  lib/avo/test_helpers.rb
  lib/avo/wait_for_loaded.rb
  spec/rails_helper.rb
  spec/support/wait_for_loaded.rb
Labels: Refactor

#3320 ✨ Controls placement on resource level
  app/components/avo/index/table_row_component.html.erb
  app/views/avo/partials/_table_header.html.erb
  lib/avo/concerns/controls_placement.rb
  lib/avo/configuration/resource_configuration.rb
  lib/avo/resources/base.rb
  spec/features/avo/resource_controls_placement_spec.rb
Labels: Enhancement, Needs Tests

#3279 refactor: boolean group and checkbox improvements
  app/components/avo/fields/common/boolean_check_component.html.erb
  app/components/avo/fields/common/boolean_check_component.rb
  app/components/avo/fields/common/boolean_group_component.html.erb
  app/components/avo/fields/common/boolean_group_component.rb
  spec/system/avo/boolean_group_field_spec.rb
Labels: Refactor, Stale exempt

#3355 fix: implicit_authorization on default authorization service
  app/controllers/avo/associations_controller.rb
  lib/avo/concerns/checks_assoc_authorization.rb
  lib/avo/fields/has_base_field.rb
  spec/dummy/config/initializers/avo.rb
Labels: Fix

#3360 chore: update tagify
  package.json
  yarn.lock
Labels: Chore

#3330 feature: translate trix field controller js warnings
  app/components/avo/fields/trix_field/edit_component.rb
  app/javascript/js/controllers/fields/trix_field_controller.js
  lib/generators/avo/templates/locales/avo.ar.yml
  lib/generators/avo/templates/locales/avo.en.yml
  lib/generators/avo/templates/locales/avo.es.yml
  lib/generators/avo/templates/locales/avo.fr.yml
  lib/generators/avo/templates/locales/avo.ja.yml
  lib/generators/avo/templates/locales/avo.nb.yml
  lib/generators/avo/templates/locales/avo.nn.yml
  lib/generators/avo/templates/locales/avo.pt-BR.yml
  lib/generators/avo/templates/locales/avo.pt.yml
  lib/generators/avo/templates/locales/avo.ro.yml
  lib/generators/avo/templates/locales/avo.tr.yml
  spec/system/avo/trix_field_spec.rb
Labels: Enhancement

#3362 fix: consider browser dynamic toolbar state for sidebar height
  app/components/avo/sidebar_component.html.erb
Labels: Fix

#3365 fix: disable non standalone actions on custom controls
  app/components/avo/actions_component.rb
  app/components/avo/resource_component.rb
  app/javascript/js/controllers/item_selector_controller.js
  lib/avo/base_action.rb
Labels: Fix

#3369 Fix issue with loading dynamic routes
  config/routes.rb
  config/routes/dynamic_routes.rb
  lib/avo/dynamic_router.rb
Labels: Fix

#3371 Fix typographical errors from spec directory
  spec/dummy/app/avo/resources/review.rb
  spec/dummy/app/avo/resources/user.rb
  spec/dummy/config/initializers/friendly_id.rb
  spec/features/avo/app_spec.rb
  spec/features/avo/create_has_one_spec.rb
  spec/features/avo/field_setter_missing_spec.rb
  spec/features/avo/link_to_child_resource_spec.rb
  spec/features/avo/number_spec.rb
  spec/features/avo/search_has_many_scope_spec.rb
  spec/features/avo/textarea_spec.rb
  spec/features/avo/use_resource_spec.rb
  spec/system/avo/attach_and_attach_another_spec.rb
  spec/system/avo/resource_sidebar_spec.rb
  spec/system/avo/select_all_spec.rb
Labels: Refactor
