Repository avo-hq/avo, pull requests merged in 2024-05, with the labels that each got.

#2730 fix: render background context when accessing extrernal action links
  app/controllers/avo/actions_controller.rb
  app/views/avo/actions/show.html.erb
  lib/avo.rb
Labels: Fix

#2733 fix: cache_table_rows
  app/components/avo/index/resource_table_component.rb
Labels: Fix

#2734 fix: table cache
  app/components/avo/index/resource_table_component.rb
Labels: Fix

#2740 fix: resource controls spacing issue
  app/components/avo/index/resource_controls_component.html.erb
  app/components/avo/views/resource_index_component.html.erb
  tailwind.preset.js
Labels: Fix

#2741 fix: check if ActionText::RichText is defined
  lib/avo/fields/trix_field.rb
Labels: Fix

#2750 chore: require ostruct
  .github/release-drafter.yml
  lib/avo.rb
Labels: Chore

#2752 chore: pagy 8 support
  .ruby-version
  Gemfile
  Gemfile.lock
  app/assets/stylesheets/css/pagination.css
  app/components/avo/paginator_component.html.erb
  app/components/avo/paginator_component.rb
  lib/avo/concerns/pagination.rb
  spec/dummy/db/seeds.rb
Labels: Chore

#2755 feature: html classes for heading wrapper
  app/components/avo/fields/common/heading_component.html.erb
  app/components/avo/fields/common/heading_component.rb
Labels: Feature

#2756 security: prevent SQL injection in sorting param
  app/components/avo/base_component.rb
  app/controllers/avo/associations_controller.rb
  app/controllers/avo/base_controller.rb
  app/controllers/avo/search_controller.rb
Labels: Security

#2757 security: prevent SQL injection in sorting param
  app/controllers/avo/base_controller.rb
Labels: Security

#2759 fix: active sidebar menu js error with custom menu
  app/javascript/js/controllers/sidebar_controller.js
Labels: Fix

#2758 fix: wrong label on `belongs_to`field
  app/components/avo/field_wrapper_component.html.erb
  lib/avo/concerns/breadcrumbs.rb
  lib/avo/concerns/can_replace_items.rb
  lib/avo/concerns/checks_assoc_authorization.rb
  lib/avo/concerns/has_items.rb
  lib/avo/concerns/visible_in_different_views.rb
  lib/avo/fields/base_field.rb
  lib/avo/fields/belongs_to_field.rb
  lib/avo/fields/concerns/frame_loading.rb
Labels: Fix

#2760 fix: default sort
  app/controllers/avo/base_controller.rb
Labels: Fix

#2772 fix: tags dissapearing when using fetch_valeus_from option
  app/javascript/js/controllers/fields/tags_field_controller.js
Labels: Fix

#2762 fix: wrong label to belongs_to
  app/components/avo/field_wrapper_component.html.erb
  app/components/avo/field_wrapper_component.rb
  app/components/avo/fields/belongs_to_field/edit_component.html.erb
  app/components/avo/fields/belongs_to_field/edit_component.rb
  app/javascript/js/controllers/fields/belongs_to_field_controller.js
  app/javascript/js/controllers/fields/reload_belongs_to_field_controller.js
  lib/avo/fields/belongs_to_field.rb
  spec/dummy/.ruby-version
  spec/dummy/config/initializers/money.rb
  spec/features/avo/allow_via_detaching_spec.rb
Labels: Fix

#2776 tweaks for https://github.com/avo-hq/avo/pull/2564
  app/components/avo/actions_component.html.erb
  app/components/avo/fields/belongs_to_field/edit_component.html.erb
  app/components/avo/fields/belongs_to_field/show_component.rb
  app/components/avo/fields/has_one_field/show_component.rb
  app/components/avo/index/grid_item_component.html.erb
  app/components/avo/index/resource_controls_component.rb
  app/components/avo/index/table_row_component.html.erb
  app/components/avo/resource_component.rb
  app/components/avo/resource_sidebar_component.html.erb
  app/components/avo/views/resource_edit_component.html.erb
  app/components/avo/views/resource_show_component.html.erb
  app/controllers/avo/base_controller.rb
  lib/avo/base_resource.rb
  lib/avo/fields/belongs_to_field.rb
  spec/dummy/app/avo/resources/comment.rb
  spec/dummy/app/views/avo/resource_tools/_fish_information.html.erb
  spec/features/avo/belongs_to_spec.rb
  spec/system/avo/belongs_to_polymorphic_spec.rb
  spec/system/avo/create_via_belongs_to_spec.rb
  spec/system/avo/tabs_spec.rb
Labels: Feature

#2767 fix: boolean group field on actions
  app/components/avo/fields/boolean_group_field/edit_component.html.erb
  app/components/avo/fields/boolean_group_field/edit_component.rb
  lib/avo/fields/boolean_group_field.rb
  spec/dummy/app/avo/actions/sub/dummy_action.rb
  spec/system/avo/actions_spec.rb
Labels: Fix

#2773 fix: truncate long action messages to avoid overflow
  lib/avo/base_action.rb
Labels: Feature, Fix

#2754 feature: JS for dashboard wide filters
  Gemfile.lock
  app/helpers/avo/application_helper.rb
  app/javascript/js/controllers.js
  app/javascript/js/controllers/card_filters_controller.js
  app/javascript/js/controllers/dashboard_card_controller.js
Labels: Feature

#2777 chore: organize specs
  spec/features/avo/belongs_to_polymorphic_spec.rb
  spec/features/avo/dynamic_filters/boolean_filter_spec.rb
  spec/features/avo/dynamic_filters/date_filter_spec.rb
  spec/features/avo/dynamic_filters/number_filter_spec.rb
  spec/features/avo/dynamic_filters/select_filter_spec.rb
  spec/features/avo/dynamic_filters/text_filter_spec.rb
  spec/features/avo/exposed_methods_base_controller_spec.rb
  spec/system/avo/avo_dynamic_filters_spec.rb
  spec/system/avo/belongs_to_polymorphic_spec.rb
  spec/system/avo/exposed_methods_base_controller_spec.rb
Labels: Chore

#2791 chore: remove symlink from dev script
  bin/dev
  spec/dummy/config/environments/development.rb
Labels: Chore

#2794 chore: add erb_lint
  .erb-lint.yml
  .erb-lint_rubocop.yml
  Gemfile
  Gemfile.lock
  gemfiles/rails_6.1_ruby_3.1.4.gemfile
  gemfiles/rails_6.1_ruby_3.1.4.gemfile.lock
  gemfiles/rails_6.1_ruby_3.2.2.gemfile
  gemfiles/rails_6.1_ruby_3.2.2.gemfile.lock
  gemfiles/rails_6.1_ruby_3.3.0.gemfile
  gemfiles/rails_6.1_ruby_3.3.0.gemfile.lock
  gemfiles/rails_7.1_ruby_3.1.4.gemfile
  gemfiles/rails_7.1_ruby_3.1.4.gemfile.lock
  gemfiles/rails_7.1_ruby_3.2.2.gemfile
  gemfiles/rails_7.1_ruby_3.2.2.gemfile.lock
  gemfiles/rails_7.1_ruby_3.3.0.gemfile
  gemfiles/rails_7.1_ruby_3.3.0.gemfile.lock
  spec/system/avo/filters/filters_spec.rb
  spec/system/avo/filters_panel_open_spec.rb
  spec/system/avo/select_all_spec.rb
Labels: Chore

#2780 fix: move default_url_options to controller extension
  app/components/avo/fields/common/files/controls_component.html.erb
  app/components/avo/sidebar/link_component.rb
  app/components/avo/sidebar_component.html.erb
  app/controllers/avo/application_controller.rb
  app/controllers/concerns/avo/common_controller.rb
  lib/avo.rb
Labels: Fix

#2808 fix: add model-unrelated errors to alerts
  app/views/avo/base/create_fail_action.turbo_stream.erb
  spec/dummy/app/avo/filters/course_city_filter.rb
  spec/system/avo/has_many_spec.rb
Labels: Fix

#2793 refactor: accesibility improvements
  app/components/avo/button_component.rb
  app/components/avo/index/grid_item_component.html.erb
  app/components/avo/index/resource_controls_component.rb
  app/components/avo/index/table_row_component.html.erb
  app/components/avo/paginator_component.html.erb
  app/components/avo/resource_component.rb
  app/components/avo/row_selector_component.html.erb
  app/components/avo/row_selector_component.rb
  app/helpers/avo/resources_helper.rb
  app/views/avo/partials/_navbar.html.erb
  app/views/avo/partials/_table_header.html.erb
  app/views/layouts/avo/application.html.erb
  spec/system/avo/tabs_spec.rb
  spec/system/avo/test_helpers_spec.rb
Labels: Refactor

#2812 Add icon to actions_list
  app/components/avo/actions_component.html.erb
  app/components/avo/actions_component.rb
  app/components/avo/resource_component.rb
  lib/avo/resources/controls/actions_list.rb
Labels: Feature

#2815 feature: custom data-confirm modal with the `dialog` element
  app/assets/stylesheets/avo.base.css
  app/javascript/avo.base.js
  app/javascript/js/custom-confirm.js
  app/views/avo/partials/_confirm_dialog.html.erb
  app/views/layouts/avo/application.html.erb
  lib/avo/test_helpers.rb
  lib/generators/avo/templates/locales/avo.ar.yml
  lib/generators/avo/templates/locales/avo.en.yml
  lib/generators/avo/templates/locales/avo.es.yml
  lib/generators/avo/templates/locales/avo.fr.yml
  lib/generators/avo/templates/locales/avo.ja.yml
  lib/generators/avo/templates/locales/avo.nb.yml
  lib/generators/avo/templates/locales/avo.nn.yml
  lib/generators/avo/templates/locales/avo.pt-BR.yml
  lib/generators/avo/templates/locales/avo.pt.yml
  lib/generators/avo/templates/locales/avo.ro.yml
  lib/generators/avo/templates/locales/avo.tr.yml
  spec/dummy/config/locales/avo.en.yml
  spec/system/avo/app_spec.rb
  spec/system/avo/destroy_record_spec.rb
  spec/system/avo/exposed_methods_base_controller_spec.rb
  spec/system/avo/fields_view_type_spec.rb
  spec/system/avo/has_and_belongs_to_many_field_spec.rb
  spec/system/avo/has_many_spec.rb
  spec/system/avo/has_one_field_name_spec.rb
  spec/system/avo/skip_show_view_spec.rb
  spec/system/avo/test_helpers_spec.rb
  spec/system/model_errors_spec.rb
Labels: Feature

#2819 fix: unescape search query
  app/controllers/avo/search_controller.rb
Labels: Fix

#2820 Add textarea autogrow
  app/components/avo/fields/textarea_field/edit_component.html.erb
  app/javascript/js/application.js
  package.json
  yarn.lock
Labels: Feature

#2823 refactor: reorder data attributes
  app/components/avo/index/grid_item_component.html.erb
  app/components/avo/index/resource_grid_component.html.erb
  app/components/avo/index/resource_table_component.html.erb
  app/components/avo/index/table_row_component.html.erb
  app/helpers/avo/resources_helper.rb
Labels: Refactor

#2826 fix: add a few more svg prefixes
  app/components/avo/index/resource_controls_component.rb
  lib/generators/avo/templates/initializer/avo.tt
Labels: Fix
