Repository avo-hq/avo, pull requests merged in 2024-09, with the labels that each got.

#3207 fix: constantize `model_class` on reader
  lib/avo/concerns/model_class_constantized.rb
  lib/avo/resources/base.rb
Labels: Fix

#3209 dx: disable select all feature when serialization raises error
  app/components/avo/index/resource_table_component.rb
  spec/dummy/app/models/post.rb
Labels: Developer Experience (DX)

#3195 fix: remove type inferences from components
  app/components/avo/fields/common/badge_viewer_component.rb
  app/components/avo/filters_component.rb
  app/components/avo/index/grid_item_component.rb
  app/components/avo/index/resource_controls_component.rb
  app/components/avo/index/resource_grid_component.rb
  app/components/avo/index/resource_table_component.rb
  app/components/avo/index/table_row_component.rb
  app/components/avo/items/panel_component.rb
  app/components/avo/paginator_component.rb
  app/components/avo/panel_component.rb
  app/components/avo/panel_name_component.rb
  app/components/avo/sidebar/base_item_component.rb
  app/components/avo/sidebar_profile_component.rb
  app/components/avo/views/resource_edit_component.rb
  app/components/avo/views/resource_index_component.rb
  app/components/avo/views/resource_show_component.rb
Labels: Fix

#3208 fix: resource fails to show when title is numeric
  lib/avo/resources/base.rb
  spec/features/avo/resource_title_spec.rb
Labels: Fix

#3210 fix: unknown keyword rel on menu link
  app/components/avo/sidebar/link_component.html.erb
  app/components/avo/sidebar/link_component.rb
Labels: Fix

#3213 feature: apply `show` policy on `click_row_to_view_record`
  app/components/avo/index/resource_controls_component.rb
  app/components/avo/index/table_row_component.rb
  lib/avo/concerns/checks_show_authorization.rb
Labels: Feature

#3215 Work without ActiveStorage
  app/components/avo/fields/common/files/controls_component.rb
  app/components/avo/fields/common/files/view_type/grid_item_component.rb
Labels: Bug

#3227 chore: update actions version
  .github/workflows/feature-tests.yml
  .github/workflows/i18n-tests.yml
  .github/workflows/system-tests.yml
  .github/workflows/test-tailwindcss-integration.yml
Labels: Chore

#3205 [2.x] Remove last usage of _reflections in favor of reflect_on_association.
  .github/workflows/test.yml
  app/components/avo/fields/belongs_to_field/autocomplete_component.rb
  app/components/avo/fields/has_one_field/show_component.rb
  app/components/avo/index/resource_controls_component.rb
  app/components/avo/views/resource_index_component.rb
  app/controllers/avo/application_controller.rb
  app/controllers/avo/associations_controller.rb
  app/controllers/avo/base_controller.rb
  gemfiles/rails_6.0_ruby_3.0.3.gemfile.lock
  gemfiles/rails_6.0_ruby_3.2.2.gemfile.lock
  gemfiles/rails_6.1_ruby_3.0.3.gemfile.lock
  gemfiles/rails_6.1_ruby_3.2.2.gemfile.lock
  gemfiles/rails_7.0_ruby_3.0.3.gemfile.lock
  gemfiles/rails_7.0_ruby_3.2.2.gemfile.lock
  spec/dummy/app/models/user.rb
  spec/features/avo/breadcrumbs_spec.rb
  spec/system/avo/dashboards_spec.rb
  spec/system/avo/tabs_spec.rb
Labels: Avo 2

#3236 fix: allow `Symbol` on `Avo::ProfileItemComponent` `method`
  app/components/avo/profile_item_component.rb
Labels: Fix

#3231 fix: verify type when fetching associations fields
  app/components/avo/base_component.rb
  app/controllers/avo/application_controller.rb
  app/controllers/avo/associations_controller.rb
  lib/avo/concerns/find_association_field.rb
  spec/dummy/app/avo/resources/store.rb
  spec/system/avo/has_many_spec.rb
Labels: Fix

#3226 fix: no link on breadcrumb when visiting from an association
  app/controllers/avo/base_controller.rb
  spec/features/avo/breadcrumbs_spec.rb
Labels: Fix

#3246 chore: remove unwanted development deps
  Gemfile
  Gemfile.lock
  gemfiles/rails_6.1_ruby_3.1.4.gemfile
  gemfiles/rails_6.1_ruby_3.1.4.gemfile.lock
  gemfiles/rails_6.1_ruby_3.3.0.gemfile
  gemfiles/rails_6.1_ruby_3.3.0.gemfile.lock
  gemfiles/rails_7.1_ruby_3.1.4.gemfile
  gemfiles/rails_7.1_ruby_3.1.4.gemfile.lock
  gemfiles/rails_7.1_ruby_3.3.0.gemfile
  gemfiles/rails_7.1_ruby_3.3.0.gemfile.lock
  gemfiles/rails_7.2.0.beta2_ruby_3.1.4.gemfile
  gemfiles/rails_7.2.0.beta2_ruby_3.1.4.gemfile.lock
  gemfiles/rails_7.2.0.beta2_ruby_3.3.0.gemfile
  gemfiles/rails_7.2.0.beta2_ruby_3.3.0.gemfile.lock
  gemfiles/rails_8.0_ruby_3.1.4.gemfile
  gemfiles/rails_8.0_ruby_3.1.4.gemfile.lock
  gemfiles/rails_8.0_ruby_3.3.0.gemfile
  gemfiles/rails_8.0_ruby_3.3.0.gemfile.lock
  lib/generators/avo/resource_generator.rb
  spec/dummy/config/initializers/avo.rb
Labels: Chore

#3218 feature: custom list control
  app/components/avo/actions_component.rb
Labels: Feature, Stale

#3270 refactor: maintain page in associations
  app/controllers/avo/base_controller.rb
  lib/avo/concerns/pagination.rb
  spec/system/avo/tabs_spec.rb
Labels: Refactor

#3268 refactor: add `resource` and `parent_resource` on associations `scope` block
  app/controllers/avo/associations_controller.rb
  spec/dummy/app/avo/resources/user.rb
  spec/features/avo/has_many_field_spec.rb
Labels: Refactor

#3275 refactor: join attach and actions modal to use the same `turbo_frame`
  app/components/avo/actions_component.rb
  app/components/avo/fields/has_one_field/show_component.html.erb
  app/components/avo/resource_component.rb
  app/controllers/avo/actions_controller.rb
  app/controllers/avo/associations_controller.rb
  app/controllers/avo/base_controller.rb
  app/helpers/avo/turbo_stream_actions_helper.rb
  app/javascript/js/controllers/actions_picker_controller.js
  app/views/avo/actions/show.html.erb
  app/views/avo/associations/new.html.erb
  app/views/avo/partials/_attach_modal.html.erb
  app/views/avo/partials/_javascript.html.erb
  app/views/layouts/avo/application.html.erb
  lib/avo.rb
  lib/avo/base_action.rb
  spec/system/avo/actions_spec.rb
Labels: Refactor

#3259 refactor: plugin rework
  app/components/avo/resource_component.rb
  app/components/avo/sidebar_component.html.erb
  app/components/avo/sidebar_component.rb
  app/components/avo/sidebar_profile_component.html.erb
  app/controllers/concerns/avo/initializes_avo.rb
  lib/avo.rb
  lib/avo/plugin.rb
  lib/avo/plugin_manager.rb
  pluggy/lib/pluggy/plugin.rb
  pluggy/lib/pluggy/railtie.rb
  spec/dummy/config/initializers/avo.rb
Labels: Refactor

#3269 refactor: improve has_many interactions + add & add another
  app/components/avo/views/resource_index_component.rb
  app/controllers/avo/associations_controller.rb
  app/controllers/avo/base_controller.rb
  app/views/avo/associations/new.html.erb
  spec/features/avo/fields_methods_for_views_spec.rb
  spec/features/avo/has_many_field_spec.rb
  spec/features/avo/use_resource_spec.rb
  spec/system/avo/associations_using_fields_api_spec.rb
  spec/system/avo/attach_and_attach_another_spec.rb
  spec/system/avo/for_attribute_spec.rb
  spec/system/avo/has_many_spec.rb
  spec/system/avo/has_one_field_name_spec.rb
  spec/system/avo/use_resource_spec.rb
Labels: Refactor

#3283 fix: verify `exemptionContainerTarget` presence
  app/javascript/js/controllers/toggle_controller.js
Labels: Fix

#3284 fix: improve tippy tooltip to support browser back button
  app/javascript/avo.base.js
Labels: Fix

#3285 fix: multiple tippy renders
  app/javascript/avo.base.js
Labels: Fix

#3286 refactor: tippy data
  app/javascript/avo.base.js
Labels: Refactor
