Repository avo-hq/avo, pull requests merged in 2024-11, with the labels that each got.

#3370 chore: fix cache store display
  app/views/avo/debug/status.html.erb
  lib/avo/licensing/h_q.rb
  lib/avo/services/debug_service.rb
Labels: Chore

#3307 refactor: replace OpenStruct with Data for performance and readability improvement
  lib/avo.rb
  lib/avo/licensing/h_q.rb
  spec/dummy/app/models/user.rb
Labels: Refactor

#3315 fix: undefined tags in field when editing
  app/javascript/js/controllers/fields/tags_field_helpers.js
Labels: Fix, Stale

#3374 refactor: extract breadcrumbs partial
  app/components/avo/panel_component.html.erb
  app/views/avo/partials/_panel_breadcrumbs.html.erb
Labels: Refactor

#3193 Feature: Add the ability to clear the file input before form submit #3164
  app/components/avo/fields/file_field/edit_component.html.erb
  app/components/avo/fields/files_field/edit_component.html.erb
  app/javascript/js/controllers.js
  app/javascript/js/controllers/fields/clear_input_controller.js
Labels: Feature

#3382 feature: callable filter `name` and `button_label`
  lib/avo/filters/base_filter.rb
  spec/dummy/app/avo/filters/user_names_filter.rb
  spec/dummy/config/locales/avo.en.yml
Labels: Enhancement

#3377 feature: eject controllers
  app/controllers/avo/application_controller.rb
  app/controllers/avo/base_application_controller.rb
  lib/generators/avo/eject_generator.rb
Labels: Feature

#3379 feature: action dynamic backdrop option
  app/components/avo/modal_component.html.erb
  app/components/avo/modal_component.rb
  app/javascript/js/controllers/modal_controller.js
  app/views/avo/actions/show.html.erb
  lib/avo/base_action.rb
  spec/dummy/app/avo/actions/export_csv.rb
  spec/system/avo/actions_spec.rb
Labels: Feature

#3372 feature: action response to reload records
  app/components/avo/index/table_row_component.html.erb
  lib/avo/base_action.rb
  spec/dummy/app/avo/actions/city/update.rb
  spec/dummy/app/avo/actions/toggle_inactive.rb
Labels: Feature

#3402 chore: update locales on i18n-tasks
  config/i18n-tasks.yml
  lib/generators/avo/templates/locales/avo.de.yml
  lib/generators/avo/templates/locales/avo.it.yml
  lib/generators/avo/templates/locales/avo.nl.yml
  lib/generators/avo/templates/locales/avo.pl.yml
  lib/generators/avo/templates/locales/avo.ru.yml
  lib/generators/avo/templates/locales/avo.uk.yml
  lib/generators/avo/templates/locales/avo.zh.yml
Labels: Chore

#3359 Refactor : change trix field show
  app/assets/stylesheets/css/fields/trix.css
  app/components/avo/fields/trix_field/show_component.html.erb
  app/javascript/js/controllers.js
  app/javascript/js/controllers/trix_body_controller.js
  lib/generators/avo/templates/locales/avo.ar.yml
  lib/generators/avo/templates/locales/avo.de.yml
  lib/generators/avo/templates/locales/avo.en.yml
  lib/generators/avo/templates/locales/avo.es.yml
  lib/generators/avo/templates/locales/avo.fr.yml
  lib/generators/avo/templates/locales/avo.it.yml
  lib/generators/avo/templates/locales/avo.ja.yml
  lib/generators/avo/templates/locales/avo.nb.yml
  lib/generators/avo/templates/locales/avo.nl.yml
  lib/generators/avo/templates/locales/avo.nn.yml
  lib/generators/avo/templates/locales/avo.pl.yml
  lib/generators/avo/templates/locales/avo.pt-BR.yml
  lib/generators/avo/templates/locales/avo.pt.yml
  lib/generators/avo/templates/locales/avo.ro.yml
  lib/generators/avo/templates/locales/avo.ru.yml
  lib/generators/avo/templates/locales/avo.tr.yml
  lib/generators/avo/templates/locales/avo.uk.yml
  lib/generators/avo/templates/locales/avo.zh.yml
  spec/dummy/config/locales/avo.en.yml
  spec/system/avo/trix_field_spec.rb
Labels: Enhancement

#3397 fix: SVG breaks buton in Safari
  app/components/avo/button_component.rb
  app/javascript/js/controllers/loading_button_controller.js
Labels: Fix

#3405 chore: normalize i18n
  lib/generators/avo/templates/locales/avo.de.yml
  lib/generators/avo/templates/locales/avo.it.yml
  lib/generators/avo/templates/locales/avo.nl.yml
  lib/generators/avo/templates/locales/avo.pl.yml
  lib/generators/avo/templates/locales/avo.ru.yml
  lib/generators/avo/templates/locales/avo.uk.yml
  lib/generators/avo/templates/locales/avo.zh.yml
Labels: Chore

#3398 Correct how the tags helper gets the text for tags
  lib/avo/test_helpers.rb
  spec/dummy/app/models/post.rb
  spec/system/avo/test_helpers_spec.rb
Labels: Fix

#3408 enhancement: extra params on global search
  app/javascript/js/controllers/search_controller.js
  app/views/avo/partials/_navbar.html.erb
  app/views/layouts/avo/application.html.erb
Labels: Enhancement

#3414 dx: raise informative error when `inverse_of` is missing on STI
  app/controllers/avo/associations_controller.rb
Labels: Developer Experience (DX)

#3418 fix: associations query limit on select options
  app/components/avo/fields/belongs_to_field/edit_component.html.erb
  app/controllers/avo/associations_controller.rb
  app/views/avo/associations/new.html.erb
  lib/avo/configuration.rb
  lib/avo/fields/belongs_to_field.rb
  lib/generators/avo/templates/initializer/avo.tt
  lib/generators/avo/templates/locales/avo.ar.yml
  lib/generators/avo/templates/locales/avo.de.yml
  lib/generators/avo/templates/locales/avo.en.yml
  lib/generators/avo/templates/locales/avo.es.yml
  lib/generators/avo/templates/locales/avo.fr.yml
  lib/generators/avo/templates/locales/avo.it.yml
  lib/generators/avo/templates/locales/avo.ja.yml
  lib/generators/avo/templates/locales/avo.nb.yml
  lib/generators/avo/templates/locales/avo.nl.yml
  lib/generators/avo/templates/locales/avo.nn.yml
  lib/generators/avo/templates/locales/avo.pl.yml
  lib/generators/avo/templates/locales/avo.pt-BR.yml
  lib/generators/avo/templates/locales/avo.pt.yml
  lib/generators/avo/templates/locales/avo.ro.yml
  lib/generators/avo/templates/locales/avo.ru.yml
  lib/generators/avo/templates/locales/avo.tr.yml
  lib/generators/avo/templates/locales/avo.uk.yml
  lib/generators/avo/templates/locales/avo.zh.yml
  spec/dummy/config/initializers/avo.rb
  spec/dummy/config/locales/avo.en.yml
  spec/system/avo/associations_using_fields_api_spec.rb
  spec/system/avo/create_via_belongs_to_spec.rb
Labels: Fix

#3407 enhancement: add divider to custom list (custom controls)
  app/components/avo/actions_component.rb
  lib/avo/divider.rb
  lib/avo/resources/base.rb
Labels: Enhancement

#3437 fix: radio field
  lib/avo/fields/radio_field.rb
  lib/avo/plugin_manager.rb
  spec/features/avo/radio_field_spec.rb
Labels: Fix

#3444 enhancement: eject components from plugins
  lib/generators/avo/eject_generator.rb
Labels: Enhancement

#3450 fix: i18n on resource class
  lib/avo/resources/base.rb
  spec/dummy/config/locales/avo.pt.yml
  spec/features/avo/generators/locales_generator_spec.rb
  spec/features/avo/localization_spec.rb
Labels: Fix

#3452 Fix Turbo.config.forms.confirm deprecation message
  app/javascript/js/custom-confirm.js
Labels: Fix

#3453 fix: explicit authorization
  app/controllers/avo/associations_controller.rb
  lib/avo/concerns/checks_assoc_authorization.rb
  lib/avo/configuration.rb
  lib/avo/fields/has_base_field.rb
Labels: Fix

#3457 fix: broken attach and attach another button for searchable associations
  app/views/avo/associations/new.html.erb
Labels: Fix

#3470 perf: svg loading improvements
  app/helpers/avo/application_helper.rb
  lib/avo.rb
Labels: Performance
