Repository avo-hq/avo, pull requests merged in 2025-08, with the labels that each got.

#4013 fix: leaking `id` when using obfuscated ids
  app/components/avo/index/grid_item_component.html.erb
  spec/dummy/app/avo/resources/post.rb
  spec/dummy/app/avo/resources/z_post.rb
  spec/features/avo/belongs_to_spec.rb
  spec/features/avo/find_record_method_spec.rb
  spec/features/avo/invalid_field_spec.rb
  spec/features/avo/use_resource_spec.rb
  spec/features/avo/via_resource_class_is_a_resource_class_spec.rb
  spec/features/avo/views_spec.rb
  spec/system/avo/actions_spec.rb
  spec/system/avo/boolean_field_spec.rb
  spec/system/avo/has_field_discovery_spec.rb
  spec/system/avo/has_many_spec.rb
  spec/system/avo/tags_spec.rb
  spec/system/avo/trix_field_spec.rb
Labels: Fix

#4023 set sensible db names for dummy app
  spec/dummy/config/database.yml
Labels: Fix

#4030 fix: fail to load frame
  app/javascript/avo.base.js
Labels: Fix

#4031 chore: revert debug code in the `render_error?` method
  app/controllers/avo/search_controller.rb
Labels: Chore

#3780 enhancement: extend `reload_records` to support grid view
  app/components/avo/index/grid_item_component.html.erb
  app/controllers/avo/actions_controller.rb
  lib/avo/base_action.rb
  spec/dummy/app/avo/actions/toggle_published.rb
  spec/dummy/app/avo/resources/post.rb
  spec/system/avo/actions_spec.rb
Labels: Enhancement
