Repository avo-hq/avo, pull requests merged in 2025-07, with the labels that each got.

#3956 chore: fix tests
  spec/dummy/app/avo/resources/city.rb
  spec/dummy/config/environments/test.rb
  spec/system/avo/alert_backtrace_spec.rb
Labels: Chore

#3964 chore: add dotenv gem for test env
  Gemfile
  gemfiles/rails_6.1_ruby_3.1.4.gemfile
  gemfiles/rails_6.1_ruby_3.3.0.gemfile
  gemfiles/rails_7.1_ruby_3.1.4.gemfile
  gemfiles/rails_7.1_ruby_3.3.0.gemfile
  gemfiles/rails_8.0_ruby_3.3.0.gemfile
Labels: Chore

#3963 enhancement: introduce q for searching and strip it
  app/controllers/avo/search_controller.rb
  lib/generators/avo/templates/resource/resource.tt
  spec/dummy/app/avo/resources/course.rb
  spec/dummy/app/avo/resources/course_link.rb
  spec/features/avo/record_passed_to_scope_spec.rb
  spec/features/avo/search_custom_results_spec.rb
  spec/features/avo/search_has_many_scope_spec.rb
  spec/features/avo/search_with_q_unstripped_spec.rb
  spec/features/avo/views_spec.rb
Labels: Enhancement

#3978 Add i18n tests to 4-dev branch
  .github/workflows/i18n-tests.yml
  lib/generators/avo/templates/locales/avo.ar.yml
  lib/generators/avo/templates/locales/avo.de.yml
  lib/generators/avo/templates/locales/avo.en.yml
  lib/generators/avo/templates/locales/avo.es.yml
  lib/generators/avo/templates/locales/avo.fr.yml
  lib/generators/avo/templates/locales/avo.it.yml
  lib/generators/avo/templates/locales/avo.ja.yml
  lib/generators/avo/templates/locales/avo.nb.yml
  lib/generators/avo/templates/locales/avo.nl.yml
  lib/generators/avo/templates/locales/avo.nn.yml
  lib/generators/avo/templates/locales/avo.pl.yml
  lib/generators/avo/templates/locales/avo.pt-BR.yml
  lib/generators/avo/templates/locales/avo.pt.yml
  lib/generators/avo/templates/locales/avo.ro.yml
  lib/generators/avo/templates/locales/avo.ru.yml
  lib/generators/avo/templates/locales/avo.tr.yml
  lib/generators/avo/templates/locales/avo.uk.yml
  lib/generators/avo/templates/locales/avo.zh-TW.yml
  lib/generators/avo/templates/locales/avo.zh.yml
Labels: Chore

#3980 fix: adjust sym_link to the new assets approach
  lib/tasks/avo_tasks.rake
Labels: Fix

#3985 ship application.js and application.js.map
  avo.gemspec
Labels: Chore

#3996 fix: missing method `color_scheme_path`
  app/views/avo/partials/_color_scheme_switcher.html.erb
Labels: Fix
