Repository avo-hq/avo, pull requests merged in 2025-01, with the labels that each got.

#3566 fix: eject generator failing due to undefined source_location method
  lib/generators/avo/eject_generator.rb
Labels: Fix

#3574 chore: actions flaky test
  lib/avo/wait_for_loaded.rb
  spec/system/avo/actions_spec.rb
Labels: Fix

#3454 enhancement: display a label with the next action for the ordering button
  app/views/avo/partials/_sortable_component.html.erb
  app/views/avo/partials/_table_header.html.erb
  lib/generators/avo/templates/locales/avo.ar.yml
  lib/generators/avo/templates/locales/avo.de.yml
  lib/generators/avo/templates/locales/avo.en.yml
  lib/generators/avo/templates/locales/avo.es.yml
  lib/generators/avo/templates/locales/avo.fr.yml
  lib/generators/avo/templates/locales/avo.it.yml
  lib/generators/avo/templates/locales/avo.ja.yml
  lib/generators/avo/templates/locales/avo.nb.yml
  lib/generators/avo/templates/locales/avo.nl.yml
  lib/generators/avo/templates/locales/avo.nn.yml
  lib/generators/avo/templates/locales/avo.pl.yml
  lib/generators/avo/templates/locales/avo.pt-BR.yml
  lib/generators/avo/templates/locales/avo.pt.yml
  lib/generators/avo/templates/locales/avo.ro.yml
  lib/generators/avo/templates/locales/avo.ru.yml
  lib/generators/avo/templates/locales/avo.tr.yml
  lib/generators/avo/templates/locales/avo.uk.yml
  lib/generators/avo/templates/locales/avo.zh.yml
  spec/system/avo/field_sorting_spec.rb
Labels: Enhancement

#3567 enhancement: remove requirement for `attachment_key` on trix fields when field is `ActionText`
  lib/avo/fields/trix_field.rb
Labels: Enhancement

#3576 fix: tags value on select mode
  app/components/avo/fields/tags_field/edit_component.html.erb
  lib/avo/fields/tags_field.rb
  spec/system/avo/tags_spec.rb
Labels: Fix

#3492 feature: shift select multiple records
  Gemfile.lock
  app/assets/stylesheets/avo.base.css
  app/components/avo/index/resource_table_component.rb
  app/components/avo/index/table_row_component.html.erb
  app/components/avo/index/table_row_component.rb
  app/components/avo/row_selector_component.html.erb
  app/components/avo/row_selector_component.rb
  app/javascript/avo.base.js
  app/javascript/js/controllers.js
  app/javascript/js/controllers/item_select_all_controller.js
  app/javascript/js/controllers/item_selector_controller.js
  app/javascript/js/controllers/record_selector_controller.js
  app/javascript/js/controllers/table_row_controller.js
  lib/avo.rb
  lib/avo/concerns/has_resource_stimulus_controllers.rb
  tailwind.preset.js
Labels: Feature, Task

#3581 enhancement: access to the `query` on all action blocks
  app/controllers/avo/actions_controller.rb
  app/javascript/js/controllers/item_select_all_controller.js
  lib/avo/base_action.rb
  spec/dummy/app/avo/actions/test/query.rb
  spec/dummy/app/avo/resources/user.rb
  spec/system/avo/actions_spec.rb
Labels: Enhancement

#3593 Add `mapkick_options` to location field
  app/components/avo/fields/location_field/show_component.html.erb
  lib/avo/fields/location_field.rb
  spec/dummy/app/avo/resources/city.rb
Labels: Enhancement

#3595 refactor: fields mapping refactor
  .gitignore
  db/factories.rb
  lib/avo/mappings.rb
  lib/generators/avo/resource_generator.rb
Labels: Refactor

#3600 fix: radio field on actions & improve accessibility
  app/components/avo/fields/radio_field/edit_component.html.erb
  spec/dummy/app/avo/actions/sub/dummy_action.rb
  spec/features/avo/radio_field_spec.rb
Labels: Fix

#3599 chore: rename markdown field to easy_mde
  app/components/avo/fields/easy_mde_field/edit_component.html.erb
  app/components/avo/fields/easy_mde_field/edit_component.rb
  app/components/avo/fields/easy_mde_field/show_component.html.erb
  app/components/avo/fields/easy_mde_field/show_component.rb
  app/components/avo/fields/markdown_field/edit_component.rb
  app/components/avo/fields/markdown_field/show_component.rb
  app/components/avo/views/resource_show_component.html.erb
  lib/avo/fields/easy_mde_field.rb
  lib/avo/resources/items/holder.rb
  spec/dummy/app/avo/resources/city.rb
  spec/dummy/app/avo/resources/project.rb
  spec/dummy/app/views/avo/resource_tools/_city_editor.html.erb
Labels: Refactor

#3602 enhancement: location field on preview & static option
  Gemfile
  Gemfile.lock
  app/components/avo/fields/location_field/show_component.html.erb
  lib/avo/fields/location_field.rb
  spec/dummy/app/avo/resources/city.rb
  spec/system/avo/location_field_spec.rb
Labels: Enhancement

#3603 fix: tags field in select mode
  app/components/avo/fields/tags_field/edit_component.html.erb
  lib/avo/fields/tags_field.rb
  spec/dummy/app/models/project.rb
  spec/dummy/db/schema.rb
  spec/system/avo/tags_spec.rb
Labels: Fix

#3612 chore: fix time flaky tests
  spec/system/avo/date_time_fields/date_time_spec.rb
  spec/system/avo/date_time_fields/time_spec.rb
  spec/system/avo/date_time_fields/timezone_spec.rb
Labels: Chore

#3606 fix: strip data-controller attribute
  app/components/avo/panel_component.rb
  lib/avo/concerns/has_resource_stimulus_controllers.rb
  spec/system/avo/date_time_fields/date_time_spec.rb
Labels: Fix

#3613 fix: grid view item selector
  app/javascript/js/controllers/item_selector_controller.js
  spec/system/avo/actions_spec.rb
Labels: Fix

#3614 chore: add invalid license log notification.
  app/controllers/concerns/avo/initializes_avo.rb
Labels: Chore

#3608 chore: register stimulus controllers from plugins
  app/components/avo/asset_manager/javascript_component.html.erb
  app/components/avo/asset_manager/javascript_component.rb
  app/javascript/avo.base.js
  app/javascript/js/application.js
  app/javascript/late-registration.js
  app/views/avo/partials/_javascript.html.erb
  lib/avo/asset_manager.rb
Labels: Chore

#3280 enhancement: floating resource controls in table rows
  app/assets/stylesheets/avo.base.css
  app/components/avo/index/table_row_component.html.erb
  app/views/avo/partials/_table_header.html.erb
  app/views/layouts/avo/application.html.erb
  lib/avo/concerns/controls_placement.rb
  lib/avo/concerns/row_controls_configuration.rb
  lib/avo/configuration.rb
  lib/avo/configuration/resource_configuration.rb
  lib/avo/resources/base.rb
  lib/generators/avo/templates/initializer/avo.tt
  spec/dummy/.env.sample
  spec/dummy/app/avo/resources/event.rb
  spec/dummy/app/avo/resources/team.rb
  spec/dummy/app/avo/resources/user.rb
  spec/dummy/config/initializers/avo.rb
  spec/features/avo/resource_controls_placement_spec.rb
  spec/system/avo/date_time_fields/date_time_spec.rb
  spec/system/avo/date_time_fields/time_spec.rb
  spec/system/avo/date_time_fields/timezone_spec.rb
  tailwind.preset.js
Labels: Enhancement

#3619 fix: pass wrapper data on heading field
  app/components/avo/fields/common/heading_component.rb
Labels: Fix

#3620 enhancement: add `saveButton` stimulus target to save button
  app/components/avo/resource_component.rb
  lib/avo/concerns/has_resource_stimulus_controllers.rb
Labels: Enhancement

#3561 feature: media library/gallery
  app/assets/stylesheets/avo.base.css
  app/assets/stylesheets/css/fields/trix.css
  app/components/avo/base_component.rb
  app/components/avo/fields/tiptap_field/show_component.html.erb
  app/components/avo/fields/trix_field/edit_component.html.erb
  app/components/avo/fields/trix_field/edit_component.rb
  app/components/avo/fields/trix_field/show_component.html.erb
  app/components/avo/media_library/item_details_component.html.erb
  app/components/avo/media_library/item_details_component.rb
  app/components/avo/media_library/list_component.html.erb
  app/components/avo/media_library/list_component.rb
  app/components/avo/media_library/list_item_component.html.erb
  app/components/avo/media_library/list_item_component.rb
  app/components/avo/paginator_component.html.erb
  app/components/avo/paginator_component.rb
  app/components/avo/sidebar_component.html.erb
  app/controllers/avo/actions_controller.rb
  app/controllers/avo/media_library_controller.rb
  app/helpers/avo/application_helper.rb
  app/helpers/avo/resources_helper.rb
  app/javascript/js/controllers.js
  app/javascript/js/controllers/copy_to_clipboard_controller.js
  app/javascript/js/controllers/fields/trix_field_controller.js
  app/javascript/js/controllers/media_library_attach_controller.js
  app/javascript/js/controllers/media_library_controller.js
  app/javascript/js/controllers/modal_controller.js
  app/javascript/js/helpers/index.js
  app/views/avo/actions/show.html.erb
  app/views/avo/media_library/_form.html.erb
  app/views/avo/media_library/_information.html.erb
  app/views/avo/media_library/index.html.erb
  app/views/avo/media_library/show.html.erb
  app/views/avo/partials/_javascript.html.erb
  config/routes.rb
  lib/avo.rb
  lib/avo/media_library/configuration.rb
  lib/generators/avo/templates/locales/avo.ar.yml
  lib/generators/avo/templates/locales/avo.de.yml
  lib/generators/avo/templates/locales/avo.en.yml
  lib/generators/avo/templates/locales/avo.es.yml
  lib/generators/avo/templates/locales/avo.fr.yml
  lib/generators/avo/templates/locales/avo.it.yml
  lib/generators/avo/templates/locales/avo.ja.yml
  lib/generators/avo/templates/locales/avo.nb.yml
  lib/generators/avo/templates/locales/avo.nl.yml
  lib/generators/avo/templates/locales/avo.nn.yml
  lib/generators/avo/templates/locales/avo.pl.yml
  lib/generators/avo/templates/locales/avo.pt-BR.yml
  lib/generators/avo/templates/locales/avo.pt.yml
  lib/generators/avo/templates/locales/avo.ro.yml
  lib/generators/avo/templates/locales/avo.ru.yml
  lib/generators/avo/templates/locales/avo.tr.yml
  lib/generators/avo/templates/locales/avo.uk.yml
  lib/generators/avo/templates/locales/avo.zh.yml
  package.json
  spec/dummy/app/views/avo/resource_tools/_fish_information.html.erb
  spec/dummy/config/initializers/avo.rb
  spec/dummy/config/locales/avo.en.yml
  tailwind.preset.js
  yarn.lock
Labels: Feature, Task, 😎 Cool

#3622 fix: `late-registration` javascript tag
  app/components/avo/asset_manager/javascript_component.html.erb
Labels: Fix

#3624 fix: tailwind integration
  lib/tasks/avo_tasks.rake
Labels: Fix

#3625 chore: media library and asset tweaks
  app/components/avo/asset_manager/javascript_component.html.erb
  app/controllers/avo/media_library_controller.rb
  app/javascript/js/controllers/fields/trix_field_controller.js
  app/views/avo/partials/_javascript.html.erb
  app/views/layouts/avo/application.html.erb
  lib/avo/media_library/configuration.rb
Labels: Chore

#3627 chore: media library to expose path and URL
  app/components/avo/media_library/list_component.rb
  app/components/avo/media_library/list_item_component.rb
  app/javascript/js/controllers/media_library_controller.js
Labels: Chore

#3628 fix: don't check action's authorization on render if `visible` return false
  lib/avo/base_action.rb
Labels: Fix

#3516 feature: add automatic field detection in resources
  lib/avo/concerns/has_field_discovery.rb
  lib/avo/configuration.rb
  lib/avo/resources/base.rb
  lib/avo/resources/items/sidebar.rb
  spec/dummy/app/avo/resources/compact_user.rb
  spec/dummy/app/avo/resources/field_discovery_user.rb
  spec/dummy/app/controllers/avo/field_discovery_users_controller.rb
  spec/dummy/config/initializers/avo.rb
  spec/system/avo/has_field_discovery_spec.rb
Labels: Feature, Stale exempt
