Repository avo-hq/avo, pull requests merged in 2025-06, with the labels that each got.

#3920 fix: mark `BaseResource` as abstract in resource manager `fetch_resources`
  lib/avo/resources/resource_manager.rb
Labels: Fix

#3924 enhancement: discreet_information visible setting
  app/components/avo/discreet_information_component.rb
  lib/avo/discreet_information.rb
  spec/dummy/app/avo/resources/project.rb
Labels: Enhancement

#3885 enhancement: grouped options for select
  app/components/avo/fields/select_field/edit_component.html.erb
  app/components/avo/fields/select_field/edit_component.rb
  db/factories.rb
  lib/avo/fields/select_field.rb
  spec/dummy/app/avo/resources/volunteer.rb
  spec/dummy/app/models/volunteer.rb
  spec/dummy/db/migrate/20250619140631_add_grouped_select_fields_to_volunteers.rb
  spec/dummy/db/schema.rb
  spec/features/avo/select_field_spec.rb
Labels: Enhancement, Stale exempt

#3948 fix: eject generator for components ejection
  lib/generators/avo/eject_generator.rb
Labels: Fix

#3941 Make External Image field options work for the show view
  app/components/avo/fields/external_image_field/show_component.html.erb
  lib/avo/fields/external_image_field.rb
Labels: Enhancement, Breaking change
