Repository avo-hq/avo, pull requests merged in 2025-03, with the labels that each got.

#3704 chore: slimmer dummy files
  db/factories.rb
  spec/dummy/app/avo/actions/download_file.rb
  spec/dummy/db/seed_files/dummy-audio.mp3
  spec/dummy/db/seed_files/dummy-file.pdf
  spec/dummy/db/seed_files/dummy-file.txt
  spec/dummy/db/seed_files/dummy-music-two.mp3
  spec/dummy/db/seed_files/dummy-music.mp3
  spec/dummy/db/seed_files/dummy-video.mp4
  spec/dummy/dummy-audio.mp3
  spec/system/avo/actions_spec.rb
  spec/system/avo/direct_upload_spec.rb
  spec/system/avo/display_persisted_attachment_spec.rb
Labels: Chore

#3708 fix: text selection on table row triggers visit
  app/javascript/js/controllers/table_row_controller.js
Labels: Fix

#3533 🚨 refactor: better engine mounting
  Gemfile
  app/components/avo/resource_component.rb
  app/components/avo/row_selector_component.rb
  app/components/avo/sidebar_component.html.erb
  app/components/avo/sidebar_component.rb
  app/components/avo/sidebar_profile_component.html.erb
  config/routes.rb
  lib/avo.rb
  lib/avo/configuration.rb
  lib/avo/engine.rb
  lib/avo/plugin_manager.rb
  lib/generators/avo/install_generator.rb
  lib/generators/avo/templates/initializer/avo.tt
  spec/dummy/config/initializers/avo.rb
  spec/dummy/config/routes.rb
Labels: Refactor, Stale exempt, Developer Experience (DX), Breaking change

#3687 🚨 fix: coherence within associations fields authorization
  app/components/avo/fields/has_one_field/show_component.html.erb
Labels: Fix, Breaking change

#3703 refactor: start using `Avo::ResourceNotFoundError` instead `ActionController::RoutingError`
  app/controllers/avo/base_application_controller.rb
  lib/avo.rb
Labels: Refactor

#3710 fix: add options_for_filter method to `BadgeField`
  lib/avo/fields/badge_field.rb
Labels: Fix

#3705 chore: add app_id if provided
  lib/generators/avo/install_generator.rb
  lib/generators/avo/templates/initializer/avo.tt
Labels: Chore

#3699 enhancement: add `@index_query` access in actions
  app/controllers/avo/actions_controller.rb
  app/javascript/js/controllers/action_controller.js
  app/javascript/js/controllers/item_select_all_controller.js
  app/views/avo/actions/show.html.erb
  lib/avo/base_action.rb
  spec/dummy/app/avo/actions/export_csv.rb
Labels: Enhancement

#3721 fix: missing locale keys for `created_at_timestamp` and `updated_at_timestamp`
  CONTRIBUTING.MD
  lib/generators/avo/templates/locales/avo.ar.yml
  lib/generators/avo/templates/locales/avo.de.yml
  lib/generators/avo/templates/locales/avo.en.yml
  lib/generators/avo/templates/locales/avo.es.yml
  lib/generators/avo/templates/locales/avo.fr.yml
  lib/generators/avo/templates/locales/avo.it.yml
  lib/generators/avo/templates/locales/avo.ja.yml
  lib/generators/avo/templates/locales/avo.nb.yml
  lib/generators/avo/templates/locales/avo.nl.yml
  lib/generators/avo/templates/locales/avo.nn.yml
  lib/generators/avo/templates/locales/avo.pl.yml
  lib/generators/avo/templates/locales/avo.pt-BR.yml
  lib/generators/avo/templates/locales/avo.pt.yml
  lib/generators/avo/templates/locales/avo.ro.yml
  lib/generators/avo/templates/locales/avo.ru.yml
  lib/generators/avo/templates/locales/avo.tr.yml
  lib/generators/avo/templates/locales/avo.uk.yml
  lib/generators/avo/templates/locales/avo.zh.yml
Labels: Fix

#3733 enhancement: Improve message when missing resource for array fields
  app/controllers/avo/base_application_controller.rb
  lib/avo.rb
  lib/avo/fields/base_field.rb
  spec/dummy/app/avo/resources/store.rb
  spec/features/avo/model_missing_resource_spec.rb
Labels: Enhancement

#3735 chore: update pr-labeler
  .github/pr-labeler.yml
  spec/dummy/config/environments/test.rb
Labels: Chore

#3736 chore: fix tabs_spec.rb
  spec/dummy/config/environments/test.rb
Labels: Chore

#3744 fix: badge alignment
  app/components/avo/fields/common/badge_viewer_component.rb
Labels: Fix

#3746 refactor: use ivar for related_record
  app/controllers/avo/base_controller.rb
Labels: Refactor

#3750 refactor: turbo stream helpers
  app/helpers/avo/turbo_stream_actions_helper.rb
  lib/avo.rb
Labels: Refactor

#3749 fix: index field wrapper extra div
  app/components/avo/clipboard_component.html.erb
  app/components/avo/field_wrapper_component.html.erb
  app/components/avo/index/field_wrapper_component.html.erb
Labels: Fix

#3748 refactor: rename `/dashboards` and `/resources` redirect path helpers
  config/routes.rb
Labels: Refactor

#3753 enhancement: StoreModel::Model support for array resources
  app/components/avo/index/table_row_component.html.erb
  app/controllers/avo/actions_controller.rb
  app/controllers/avo/base_application_controller.rb
  lib/avo/resources/array_resource.rb
  spec/system/avo/has_many_spec.rb
Labels: Enhancement

#3761 fix: array field on array resource
  app/controllers/avo/associations_controller.rb
  spec/dummy/app/avo/resources/movie.rb
Labels: Fix

#3756 Fix: No cancel button showing when creating new user via new review
  app/components/avo/resource_component.rb
  app/components/avo/views/resource_edit_component.rb
Labels: Fix
