Repository avo-hq/avo, pull requests merged in 2025-02, with the labels that each got.

#3634 fix: tailwind integration dependencies
  lib/tasks/avo_tasks.rake
Labels: Fix

#3635 Removed defer attribute from the avo.base.css stylesheet tag
  app/views/layouts/avo/application.html.erb
Labels: Fix

#3636 fix: has many record selection disables parent's actions
  app/components/avo/actions_component.rb
  app/components/avo/resource_component.rb
  app/javascript/js/controllers/item_selector_controller.js
Labels: Fix

#3637 chore: move media library menu entry
  app/components/avo/sidebar_component.html.erb
Labels: Chore

#3643 fix: global search warning
  app/controllers/avo/search_controller.rb
Labels: Fix

#3572 feature: Implement multiple option for select field
  app/components/avo/fields/select_field/edit_component.html.erb
  app/components/avo/fields/select_field/show_component.html.erb
  db/migrate/20250103192051_add_sizes_to_products.rb
  lib/avo/fields/select_field.rb
  spec/dummy/app/avo/resources/product.rb
  spec/dummy/db/schema.rb
  spec/features/avo/select_field_spec.rb
Labels: Feature

#3646 fix: array resource authorization
  lib/avo/resources/array_resource.rb
Labels: Fix

#3654 chore: drop `universalid` dependency
  Gemfile.lock
  app/helpers/avo/application_helper.rb
  avo.gemspec
Labels: Chore

#3658 enhancement: log errors rescued in `perform_action_and_record_errors`
  app/controllers/avo/base_controller.rb
Labels: Enhancement

#3666 fix: radio field accessibility
  app/components/avo/fields/radio_field/edit_component.html.erb
  spec/dummy/app/avo/actions/sub/dummy_action.rb
  spec/features/avo/radio_field_spec.rb
Labels: Fix

#3675 fix: `change_items_per_page_url` on paginator component
  app/components/avo/paginator_component.rb
  app/components/avo/views/resource_index_component.html.erb
  app/helpers/avo/url_helpers.rb
Labels: Fix

#3685 fix: modify array resource constant registration to use Avo namespace
  lib/avo/resources/array_resource.rb
Labels: Fix

#3694 fix: warning: already initialized constant Avo::Concerns::HasFieldDiscovery::COLUMN_NAMES_TO_IGNORE
  lib/avo/concerns/has_field_discovery.rb
Labels: Fix

#3691 Remove unnecessary blank lines in resource template
  lib/generators/avo/templates/resource/resource.tt
Labels: Chore

#3693 enhancement: allow dynamic content in `description` and `name`
  Gemfile.lock
  app/components/avo/views/resource_index_component.rb
  lib/avo/concerns/has_description.rb
  lib/avo/fields/base_field.rb
  spec/dummy/app/avo/resources/user.rb
  spec/features/avo/has_many_field_spec.rb
Labels: Enhancement

#3696 enhancement: namespaced actions generator
  lib/generators/avo/action_generator.rb
Labels: Enhancement

#3669 refactor: alias `row` to `cluster`
  lib/avo/concerns/has_items.rb
  lib/avo/resources/items/holder.rb
  lib/avo/resources/items/item_group.rb
  spec/dummy/app/avo/resources/person.rb
Labels: Refactor
