Repository avo-hq/avo, pull requests merged in 2025-04, with the labels that each got.

#3763 fix: allow `nested: false`
  lib/avo/fields/concerns/nested.rb
Labels: Fix

#3777 refactor: abstract resources
  app/avo/base_resource.rb
  lib/avo/concerns/abstract_resource.rb
  lib/avo/resources/array_resource.rb
  lib/avo/resources/base.rb
  lib/avo/resources/resource_manager.rb
Labels: Refactor

#3779 refactor: http generator
  lib/generators/avo/concerns/parent_controller.rb
  lib/generators/avo/resource_generator.rb
  lib/generators/avo/templates/resource/resource.tt
Labels: Refactor

#3765 Add support for decoration in base field handling
  lib/avo/fields/base_field.rb
  lib/avo/fields/heading_field.rb
  spec/dummy/app/avo/resources/city.rb
  spec/features/avo/text_field_spec.rb
  spec/system/avo/multiple_actions_flux_spec.rb
Labels: Enhancement

#3783 fix: avoid engine options mutation on mount
  lib/avo/engine.rb
Labels: Fix

#3787 enhancement: access `record` on array block
  app/controllers/avo/associations_controller.rb
  lib/avo/resources/array_resource.rb
  spec/dummy/app/avo/resources/event.rb
  spec/dummy/app/models/event.rb
Labels: Enhancement

#3789 fix: `belongs_to` resource generator
  lib/avo/mappings.rb
  spec/dummy/app/models/city.rb
  spec/dummy/app/models/post.rb
  spec/dummy/app/models/product.rb
  spec/dummy/app/models/project.rb
Labels: Fix

#3792 fix: nested records hidden class
  Gemfile.lock
  app/javascript/js/controllers/nested_form_controller.js
Labels: Fix

#3794 refactor: default alert component background class
  app/components/avo/alert_component.rb
Labels: Refactor

#3791 feature: reactive fields
  app/components/avo/field_wrapper_component.html.erb
  app/components/avo/views/resource_edit_component.html.erb
  app/components/avo/views/resource_edit_component.rb
  app/controllers/avo/base_controller.rb
  app/views/avo/base/edit.turbo_stream.erb
  app/views/avo/base/new.turbo_stream.erb
  config/routes/dynamic_routes.rb
  lib/avo/concerns/form_builder.rb
  lib/avo/fields/base_field.rb
  lib/avo/fields/concerns/dom_id.rb
Labels: Feature

#3796 refactor: migrate `logo.clearbit` to `logo.dev`
  spec/dummy/app/avo/resources/team.rb
Labels: Refactor

#3665 fix: belongs_to field should use association primary_key
  db/factories.rb
  lib/avo/fields/belongs_to_field.rb
  spec/dummy/app/avo/resources/volunteer.rb
  spec/dummy/app/controllers/avo/volunteers_controller.rb
  spec/dummy/app/models/event.rb
  spec/dummy/app/models/volunteer.rb
  spec/dummy/db/migrate/20250310175239_add_uuid_to_events.rb
  spec/dummy/db/migrate/20250310175357_create_volunteers.rb
  spec/dummy/db/schema.rb
  spec/features/avo/belongs_to_spec.rb
Labels: Fix, Stale exempt

#3808 fix: access `record` inside field on update requests
  lib/avo/concerns/has_items.rb
  spec/dummy/app/avo/resources/user.rb
Labels: Fix

#3814 refactor: access `view_type` from resource
  app/components/avo/views/resource_index_component.html.erb
  app/components/avo/views/resource_index_component.rb
  app/controllers/avo/base_controller.rb
  lib/avo/resources/base.rb
Labels: Refactor

#3681 enhancement: add open attachment without download
  app/components/avo/fields/common/files/view_type/grid_item_component.html.erb
  app/components/avo/fields/common/files/view_type/grid_item_component.rb
  spec/dummy/db/seed_files/sample.csv
  spec/system/avo/open_field_attachment_spec.rb
Labels: Enhancement

#3804 fix: apply `scope` on `has_many` fields while searching on the association table
  app/controllers/avo/search_controller.rb
  spec/features/avo/search_has_many_scope_spec.rb
Labels: Fix
