Repository avo-hq/avo, pull requests merged in 2025-05, with the labels that each got.

#3824 add jsonb to fields mapping
  lib/avo/mappings.rb
Labels: Enhancement

#3829 fix: array resource actions query
  lib/avo/resources/array_resource.rb
  spec/dummy/app/avo/resources/movie.rb
  spec/system/avo/array_resource_spec.rb
Labels: Fix

#3830 fix: allow textarea index field
  lib/avo/fields/textarea_field.rb
Labels: Fix

#3831 fix: copyable date style
  app/components/avo/fields/date_field/index_component.html.erb
Labels: Fix

#3856 refactor: allow progress field to submit nil values
  app/components/avo/fields/progress_bar_field/edit_component.html.erb
  app/javascript/js/controllers/fields/progress_bar_field_controller.js
  spec/system/avo/progress_bar_field_spec.rb
Labels: Refactor

#3861 fix: populate `self.query` for standalone `index_control` actions
  app/javascript/js/controllers/item_select_all_controller.js
Labels: Fix

#3862 Fix filters on association field
  app/javascript/js/controllers/filter_controller.js
Labels: Fix

#3854 enhancement: `mount_avo` accepts custom routes block
  lib/avo/engine.rb
  spec/dummy/config/routes.rb
Labels: Enhancement

#3863 fix: row actions on array resources
  lib/avo/base_action.rb
Labels: Fix

#3847 fix: `belongs_to` when using `for_attribute`
  app/views/avo/partials/_table_header.html.erb
  lib/avo/fields/base_field.rb
  lib/avo/fields/belongs_to_field.rb
  lib/avo/fields/file_field.rb
  lib/avo/fields/frame_base_field.rb
Labels: Fix

#3864 fix: add `avo-` prefix to `nested-form`
  app/javascript/js/controllers.js
Labels: Fix

#3874 Fix: Keep actions dropdown visible and on top when opened
  app/assets/stylesheets/avo.base.css
Labels: Fix

#3878 fix: hide polymorphic holder div
  app/components/avo/fields/belongs_to_field/edit_component.html.erb
  app/javascript/js/controllers/fields/belongs_to_field_controller.js
Labels: Fix

#3887 refactor: remove dead code
  app/components/avo/items/panel_component.rb
  app/components/avo/views/resource_edit_component.rb
  app/components/avo/views/resource_show_component.rb
Labels: Refactor

#3898 chore: fix tests
  .github/workflows/feature-tests.yml
  .github/workflows/system-tests.yml
  Gemfile
  Gemfile.lock
  app/assets/stylesheets/avo.base.css
  app/components/avo/fields/time_field/edit_component.html.erb
  app/controllers/avo/base_controller.rb
  app/javascript/js/controllers/fields/tags_field_controller.js
  app/views/avo/base/edit.turbo_stream.erb
  app/views/avo/base/new.turbo_stream.erb
  spec/system/avo/key_value_field/key_value_field_spec.rb
Labels: Chore
